In [1]:
import pandas_gbq
import pickle
import pandas as pd
import numpy as np

# TODO: Set project_id to your Google Cloud Platform project ID.
# project_id = "xxxxxx-yyyyyy-######"

In [26]:
# use this to get the table definition of individual tables in Big Query's tables

# substitute the table name you want the schema for in the "table_name = " line below


sql = """

SELECT column_name
FROM `bigquery-public-data`.stackoverflow.INFORMATION_SCHEMA.COLUMNS  
WHERE table_name = 'posts_questions' 

"""
df=pandas_gbq.read_gbq(sql, project_id=project_id)

In [27]:
df

                 column_name
0                         id
1                      title
2                       body
3         accepted_answer_id
4               answer_count
5              comment_count
6       community_owned_date
7              creation_date
8             favorite_count
9         last_activity_date
10            last_edit_date
11  last_editor_display_name
12       last_editor_user_id
13        owner_display_name
14             owner_user_id
15                 parent_id
16              post_type_id
17                     score
18                      tags
19                view_count

In [3]:
# Here is the code to extract the records from one table and load it into a pandas data frame

# note that this can run a long time, depending on the number of records you are trying to load


sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%d3%' 
OR tags LIKE '%tableau%'
OR tags LIKE '%ggplot%'
OR tags LIKE '%plotly%'
OR tags LIKE '%matplotlib%'
OR tags LIKE '%excel%'
OR tags LIKE '%sheets%'
OR tags LIKE '%seaborn%'
OR tags LIKE '%altair%'
OR tags LIKE '%powerbi%'
OR tags LIKE '%qlik%'
OR tags LIKE '%chart%'
OR tags LIKE '%graph%'
OR tags LIKE '%sas%'
OR tags LIKE '%spss%'
OR tags LIKE '%plot%'
OR tags LIKE '%stata%'
OR tags LIKE '%line%'
OR tags LIKE '%visual%'
OR tags LIKE '%viz%'
OR tags LIKE '%linechart%'
OR tags LIKE '%diagram%'
OR tags LIKE '%map%')
AND
tags NOT LIKE '%visual-studio%'
AND
tags NOT LIKE '%visual-c++%'
"""
dfPostQuestionsFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [4]:
np.shape(dfPostQuestionsFiltered)

(971729, 20)

In [6]:
dfPostQuestionsFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,32514327,Compiling graph-tool on RHEL,<p>I need to use Python's graph-tool on a RHEL...,32525566.0,1,5,NaT,2015-09-11 01:57:28.747000+00:00,NaN,2015-09-11 14:13:49.777000+00:00,2015-09-11 11:59:28.830000+00:00,None,1159005.0,None,1159005.0,None,1,1,boostcompilationconfigurerhelgraph-tool,465
1,32770176,"in Java, how can I map String to a Set<String>...","<p>I need a HashMap, which the key is String a...",32770240.0,4,5,NaT,2015-09-24 20:18:56.413000+00:00,NaN,2018-07-29 14:58:39.143000+00:00,NaT,None,NaN,None,4839810.0,None,1,1,javaoopobjecthashmapset,3281
2,32743621,Bypass Google Maps Directions limits,<p>I've to make a map with multiple directions...,32755498.0,1,5,NaT,2015-09-23 15:26:13.510000+00:00,NaN,2015-09-24 07:15:26.967000+00:00,NaT,None,NaN,None,2435421.0,None,1,-1,google-mapsdirectionslimits,468
3,32610422,React and d3.js - attaching event handlers,<p>I'm working on a project using React for my...,NaN,0,5,NaT,2015-09-16 13:45:13.790000+00:00,NaN,2015-09-16 13:45:13.790000+00:00,NaT,None,NaN,None,645070.0,None,1,0,javascriptd3.jsreactjs,473
4,32740005,JavaFX Chart axis label formatting,<p>I wrote a simple program to monitor my ping...,32741170.0,1,5,NaT,2015-09-23 12:45:32.097000+00:00,0.0,2015-09-23 16:26:39.820000+00:00,2015-09-23 16:26:39.820000+00:00,None,3941856.0,None,3941856.0,None,1,3,javachartsjavafxlabellinechart,8952
5,32508423,VBA return 2 variants in MsgBox,<p>This is the start to a simple mathematical ...,32508634.0,1,5,NaT,2015-09-10 17:41:18.993000+00:00,NaN,2015-09-10 17:55:05.300000+00:00,2015-09-10 17:48:01.113000+00:00,None,4974730.0,None,4974730.0,None,1,0,excelvbaexcel-vbamathoffice-2013,252
6,32798477,MatPlotLib on Tkinter finished with exit code ...,<p>The following code works well in Python 2.7...,32800404.0,2,6,NaT,2015-09-26 14:53:55.597000+00:00,NaN,2016-12-04 23:08:34.743000+00:00,NaT,None,NaN,None,5181181.0,None,1,1,python-3.xmatplotlibtkinter,532
7,32773539,AssertionError during idle_check in IMAPClient,<p>I am attempting to have a python script tha...,NaN,0,6,NaT,2015-09-25 01:48:18.060000+00:00,1.0,2015-09-25 10:46:43.070000+00:00,2015-09-25 10:46:43.070000+00:00,None,2689797.0,None,2689797.0,None,1,2,pythonemailgmail-imapimapclient,299
8,32415262,How to let the command window open while execu...,<p>I am facing a strange issue. I have an appl...,NaN,0,6,NaT,2015-09-05 16:25:12.270000+00:00,1.0,2015-09-05 16:27:05.873000+00:00,2015-09-05 16:27:05.873000+00:00,None,354974.0,None,3655102.0,None,1,0,c#command-line,48
9,32587276,Use VBA and Shell (CMD) to launch R script and...,<p>I have an R script named <code>plot.R</code...,NaN,0,6,NaT,2015-09-15 13:23:27.993000+00:00,NaN,2015-09-15 13:23:27.993000+00:00,NaT,None,NaN,None,5202253.0,None,1,0,rvbaplotcmd,305
10,32704383,Make Highcharts column chart bars as wide as m...,<p>I have this Highcharts column chart:</p>\n\...,NaN,1,6,NaT,2015-09-21 20:53:39.377000+00:00,NaN,2015-09-22 01:17:34.020000+00:00,NaT,None,NaN,None,2023979.0,None,1,0,highcharts,51
11,32604064,Grab data from graph,"<p>I have a graph saved as *.jpeg, and I would...",NaN,0,6,NaT,2015-09-16 09:01:43.167000+00:00,NaN,2015-09-16 09:01:43.167000+00:00,NaT,None,NaN,None,3551644.0,None,1,0,rplotextract,56
12,32679974,"Creating 33 URLs from 169 Values, without dupl...","<p>I had previously used Excel for this, but w...",NaN,0,6,NaT,2015-09-20 13:34:31.663000+00:00,NaN,2015-09-20 14:43:23.597000+00:00,2018-07-09 18:41:45.953000+00:00,None,-1.0,None,915204.0,None,1,1,arraysrubyexcel-vba23andme-apivba,62
13,32694330,Save .xls file in Java,<p>I made an application that reads some data ...,NaN,0,6,NaT,2015-09-21 11:41:20.077000+00:00,NaN,2015-09-21 15:06:34.643000+00:00,2015-09-21 15:06:34.643000+00:00,None,1505120.0,None,4382433.0,None,1,0,javaexceljxl,65
14,32509528,'if' statement sometimes doesn't work,"<p><div class=""snippet"" data-lang=""js"" data-hi...",NaN,1,6,NaT,2015-09-10 18:47:24.840000+00:00,NaN,2015-09-10 21:49:41.360000+00:00,2015-09-10 21:49:41.360000+00:00,None,1505120.0,None,4354142.0,None,1,0,javascriptif-statementgoogle-sheets,68
15,32568942,How to disable cut/copy option for all cells i...,<p>/*****\n<strong>--EDIT--</strong>\n<strong>...,NaN,1,6,NaT,2015-09-14 15:53:26.533000+00:00,1.0,2015-09-16 11:58:19.323000+00:00,2015-09-16 11:58:19.323000+00:00,None,5334563.0,None,5334563.0,None,1,1,c#wpfexcel,837
16,32638244,Create function but only for use in VBA enviro...,<p>This is new to me - I've created a function...,32638594.0,2,6,NaT,2015-09-17 19:11:17.123000+00:00,1.0,2015-09-17 20:05:47.300000+00:00,2015-09-17 19:59:22.627000+00:00,None,1505120.0,None,1693085.0,None,1,1,excelvbafunctionexcel-vba,77
17,32489205,How to programmatically overlap arbitrary stat...,<p>I am looking for a way to automatically plo...,32498175.0,1,6,NaT,2015-09-09 21:08:51.507000+00:00,NaN,2015-09-10 15:16:51.900000+00:00,2015-09-10 15:16:51.900000+00:00,None,992358.0,None,992358.0,None,1,3,rggplot2,91
18,32481356,recursive call in looping a list,<p>I m trying to loop a list of users to find ...,32482671.0,3,6,NaT,2015-09-09 13:48:56.197000+00:00,NaN,2015-09-09 15:12:36.270000+00:00,2015-09-09 14:23:43.167000+00:00,None,4317989.0,None,4317989.0,None,1,1,javaalgorithmgraph-algorithm,96
19,32598820,Get all the nodes connected to a node in Apach...,<p>Suppose we have got the input in Apache Gra...,32601726.0,1,6,NaT,2015-09-16 02:36:51.033000+00:00,3.0,2015-09-16 06:58:50.317000+00:00,2015-09-16 06:44:40.860000+00:00,None,1560062.0,None,3398339.0,None,1,6,scalagraphapache-sparkspark-graphx,2144
20,32776920,Take snapshot of HighChart with render.text.css,<p>I have a simple highChart with x-axis label...,32841169.0,1,6,NaT,2015-09-25 07:25:48.020000+00:00,1.0,2015-09-29 10:03:19.927000+00:00,2015-09-29 04:37:34.930000+00:00,None,4753301.0,None,4753301.0,None,1,0,javascriptsvghighchartsscreenshotcanvg,359
21,32429292,"Get user's home, work and starred locations li...",<p>When in Google Inbox you go to snooze a mes...,NaN,2,6,NaT,2015-09-06 23:28:59.850000+00:00,10.0,2015-11-19 19:22:33.967000+00:00,2015-09-08 00:13:09.457000+00:00,None,13163.0,None,13163.0,None,1,27,androidgoogle-mapsgoogle-apigoogle-now,3175
22,32570299,Bash: How to capture Filename Expansion? (expa...,<p>--<strong>Disclaimer</strong>--<br>\nI am o...,32570707.0,1,6,NaT,2015-09-14 17:15:54.303000+00:00,NaN,2015-09-14 18:03:29.947000+00:00,2017-04-13 12:36:24.867000+00:00,None,-1.0,None,843542.0,None,1,0,bashshellcommand-linewildcardglob,616
23,32841258,"android getting local image path as https, how...",<p>I've fetched a user selected image from gal...,32862356.0,3,6,NaT,2015-09-29 10:07:56.157000+00:00,NaN,2015-09-30 09:18:39.847000+00:00,2015-09-29 17:26:37.027000+00:00,None,5155835.0,None,5155835.0,None,1,0,androidandroid-imageviewandroid-imageandroid-b...,882
24,32640005,Google maps coordinates view,"<p>I have a regular map I can zoom in/out, mov...",32641068.0,1,6,NaT,2015-09-17 21:07:40.677000+00:00,NaN,2015-09-17 22:40:04.547000+00:00,2015-09-17 21:40:50.237000+00:00,None,956575.0,None,956575.0,None,1,0,google-maps,131
25,32492118,NSOutlineViewDelegate rowViewForItem being cal...,<p>I have a custom subclass of NSOutlineView i...,NaN,0,6,NaT,2015-09-10 02:26:52.483000+00:00,NaN,2015-09-10 08:52:46.980000+00:00,2015-09-10 08:52:46.980000+00:00,None,1527934.0,None,2488130.0,None,1,0,objective-cmacoscocoaappkitnsoutlineview,388
26,32552845,Count the data inside Map conditionally,"<p>I have a <code>Map&lt;String, List&lt;Strin...",NaN,1,6,NaT,2015-09-13 18:04:30.643000+00:00,NaN,2015-09-14 04:41:38.500000+00:00,2015-09-14 04:41:38.500000+00:00,None,1275683.0,None,1275683.0,None,1,0,javahashmap,145
27,32600880,ggplot2 apply different color with matching ar...,<p>Step 1: get the index price from 1990-01-01...,NaN,1,6,NaT,2015-09-16 06:04:14.853000+00:00,NaN,2015-09-16 11:02:05.957000+00:00,2015-09-16 08:37:29.373000+00:00,None,5125810.0,None,5125810.0,None,1,0,rggplot2,169
28,32415415,Google Maps API must now use a Server Key?,<p>My website makes use of Google Maps API. I ...,NaN,1,6,NaT,2015-09-05 16:40:46.043000+00:00,NaN,2015-09-07 16:16:47.597000+00:00,2015-09-05 18:31:26.493000+00:00,None,2070775.0,None,2070775.0,None,1,0,google-maps,681
29,32636123,JSON data undefined from external file in d3.js?,<p>I'm developing a d3.js app that reads data ...,32636551.0,1,6,NaT,2015-09-17 17:07:49.613000+00:00,1.0,2015-09-17 17:34:11.713000+00:00,2015-09-17 17:26:39.893000+00:00,None,2740614.0,None,2740614.0,None,1,0,javascriptjsond3.js,187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971699,2221052,Import query results into tool through VB.NET,<p>I am writing a tool to import a database qu...,NaN,2,1,NaT,2010-02-08 10:57:43.953000+00:00,NaN,2011-12-02 11:58:50.087000+00:00,2010-07-16 23:45:04.727000+00:00,None,63550.0,None,238147.0,None,1,0,vb.netexcel,405
971700,2321728,how to map SampleCount property using NHibernate,"<p>I have two tables - Run and Sample, where S...",2325964.0,2,0,NaT,2010-02-23 21:09:08.703000+00:00,NaN,2010-02-24 12:36:53.127000+00:00,NaT,None,NaN,None,80002.0,None,1,0,nhibernatenhibernate-mapping,104
971701,1426146,How to extract numbers from text file using Wi...,<p>I need to do the following using cmd (Windo...,1426593.0,2,1,NaT,2009-09-15 09:31:58.550000+00:00,NaN,2009-10-17 23:42:18.083000+00:00,2009-10-17 23:15:53.133000+00:00,None,100754.0,None,154180.0,None,1,1,windowscommand-linecmd,4087
971702,1437780,Google maps satellite view,<p>I'm using the <em>google maps API</em> with...,1458000.0,2,2,NaT,2009-09-17 09:49:39.907000+00:00,2.0,2009-09-22 03:38:07.860000+00:00,2009-09-21 11:28:56.190000+00:00,None,15255.0,None,146864.0,None,1,1,google-mapsmapsopenstreetmap,3711
971703,1441748,Best way to stop Firefox pipe-lining from mess...,<p>I've noticed that my pageview counts are be...,1441881.0,2,0,NaT,2009-09-17 23:01:27.990000+00:00,NaN,2009-09-18 00:40:26.683000+00:00,NaT,None,NaN,None,84387.0,None,1,1,phpapachefirefoxpipeline,468
971704,1456266,Clone existing recordset to excel recordset,<p>I have a recordset that contains all of the...,1458534.0,2,0,NaT,2009-09-21 19:09:21.113000+00:00,NaN,2009-09-23 03:11:20.163000+00:00,2009-09-22 06:56:00.723000+00:00,None,17516.0,None,141594.0,None,1,1,excelasp-classicvbscriptadodbrecordset,1811
971705,1476978,creating charts in jquery,<p>I'd like to create a chart that breaks down...,NaN,2,0,NaT,2009-09-25 12:15:23.557000+00:00,2.0,2009-09-27 17:47:49.433000+00:00,NaT,None,NaN,rashcroft1,NaN,None,1,1,javascriptjquerycharts,2991
971706,1533183,Wrapping an image around 3d object for easy 2d...,<p>Looking for method for wrapping a 2d image ...,NaN,2,2,NaT,2009-10-07 17:52:06.950000+00:00,NaN,2010-02-03 07:00:15.303000+00:00,NaT,None,NaN,None,121461.0,None,1,1,algorithmimagegraphics3ddistortion,1872
971707,1551276,Need JET 4.0 Drivers,<p>I am using an ExcelProvider with Microsoft....,1551939.0,2,0,NaT,2009-10-11 17:51:29.203000+00:00,NaN,2013-07-24 17:09:32.920000+00:00,2013-07-24 17:09:32.920000+00:00,None,1065525.0,None,24333.0,None,1,1,excelms-officeoledbjet,362
971708,1552438,Working with Data.frames in R (Using SAS code ...,"<p>I've been mostly working in SAS of late, bu...",NaN,2,0,NaT,2009-10-12 02:37:07.560000+00:00,NaN,2011-10-24 09:09:10.280000+00:00,2011-10-24 09:09:10.280000+00:00,None,709619.0,user188181,NaN,None,1,1,rsasdataframe,818
971709,1576714,Redirect all HTTP-Requests with *.asp to one s...,<p>Is it possible on an IIS to redirect all fi...,1581717.0,2,2,NaT,2009-10-16 07:57:07.027000+00:00,NaN,2011-12-01 19:23:10.033000+00:00,2011-12-01 19:23:10.033000+00:00,None,3043.0,None,191075.0,None,1,1,iisasp-classiccoldfusionhttp-redirect,739
971710,1582968,How would I position a marker at the bottom of...,"<p>I have a webpage that <a href=""http://www.b...",1583100.0,2,1,NaT,2009-10-17 19:07:30.190000+00:00,2.0,2010-02-23 11:03:00.040000+00:00,2010-02-23 11:03:00.040000+00:00,None,184842.0,None,147731.0,None,1,1,javascriptgoogle-mapsgoogle-maps-markersgoogle...,2539
971711,1608399,ASP.Net MVC Wildcard Mappings IIS 6.0 - Page C...,<p>I added wildcard mappings to my website in ...,1609434.0,2,0,NaT,2009-10-22 16:23:54.827000+00:00,0.0,2009-11-24 06:21:49.670000+00:00,NaT,None,NaN,None,46780.0,None,1,1,asp.net-mvciiswildcard-mapping,1139
971712,1629054,Excel formula for time comparision,<p>while writing an formula for data in a exce...,1629087.0,2,2,NaT,2009-10-27 06:32:48.907000+00:00,NaN,2009-10-27 06:51:34.353000+00:00,2009-10-27 06:51:34.353000+00:00,None,166686.0,None,193133.0,None,1,1,exceldatetime,400
971713,1630012,Automapper Mapping,<p>I'm trying to map an object with property n...,NaN,2,1,NaT,2009-10-27 10:49:35.520000+00:00,1.0,2009-10-27 13:10:12.330000+00:00,2009-10-27 11:40:05.330000+00:00,None,5853.0,None,5853.0,None,1,1,.netautomapper,2369
971714,1633810,Image series (animation) over Google Maps,<p>I'm new to Google map api. My goal is to ov...,1635707.0,2,0,NaT,2009-10-27 21:33:23.560000+00:00,2.0,2009-10-28 07:48:02.407000+00:00,2009-10-28 07:48:02.407000+00:00,None,41983.0,None,182843.0,None,1,1,asp.netgoogle-maps,1594
971715,1697356,How to transition between two images using a g...,"<p>Imagine you have two images A and B, and a ...",1697564.0,2,0,NaT,2009-11-08 17:58:11.270000+00:00,2.0,2009-11-09 17:02:14.970000+00:00,2009-11-09 17:02:14.970000+00:00,None,39926.0,None,39926.0,None,1,1,language-agnosticgraphicstransitions,641
971716,1704369,PHP Excel Reader : get strikeout / strikethrou...,<p>I am looking for way to parse the strikeout...,1704660.0,2,1,NaT,2009-11-09 22:28:22.193000+00:00,1.0,2014-06-19 13:27:17.487000+00:00,2009-11-10 02:09:32.080000+00:00,None,2766176.0,None,401323.0,None,1,1,phpexcelparsing,2475
971717,1720169,What does this Python code do: shell=(sys.plat...,"<p>I don't understand what this code is doing,...",1720192.0,2,0,NaT,2009-11-12 05:51:49.013000+00:00,NaN,2009-11-12 06:08:08.930000+00:00,2009-11-12 05:59:44.660000+00:00,None,207258.0,None,207258.0,None,1,1,pythonmacoscommand-line,450
971718,1723943,Easiest way to get the image of a map from goo...,<p>I have a hundred of UK postcodes and need t...,NaN,2,0,NaT,2009-11-12 17:25:29.120000+00:00,NaN,2009-11-12 17:28:41.797000+00:00,NaT,None,NaN,ORA600,NaN,None,1,1,google-maps,72
971719,1728852,Mysql Importing new codes from excel,<p>I have a CSV file with mappings from projec...,1728924.0,2,0,NaT,2009-11-13 12:11:05.777000+00:00,NaN,2009-11-13 12:33:07.020000+00:00,2009-11-13 12:30:11.423000+00:00,None,112517.0,None,111052.0,None,1,1,mysqlexcelimport,142
971720,1744406,what is the name of the convention used in thi...,<p>I found this diagram in the JSON specificat...,1744430.0,2,0,NaT,2009-11-16 19:44:07.833000+00:00,NaN,2019-05-09 07:04:40.167000+00:00,2019-05-09 07:04:40.167000+00:00,None,4751173.0,None,42223.0,None,1,1,jsondiagramspecificationsbnf,129
971721,1748902,Linux inter-process reentrant semaphore,<p>I'm porting a Windows application to Linux ...,1749086.0,2,1,NaT,2009-11-17 13:34:04.997000+00:00,1.0,2009-11-17 14:16:22.273000+00:00,NaT,None,NaN,None,212865.0,None,1,1,c++clinuxsemaphoreinterprocess,2635
971722,1775697,C# DataTable: Add new row throws error using A...,<p>I have a collection </p>\n\n<pre><code>Lis...,1776616.0,2,0,NaT,2009-11-21 15:00:09.100000+00:00,1.0,2009-11-21 20:09:02.127000+00:00,NaT,None,NaN,None,198544.0,None,1,1,c#collectionsdatatableauto-incrementdatarow,6763
971723,1778868,Access and classic ASP error 80004005 System r...,<p>An old site on shared hosting has developed...,1778951.0,2,2,NaT,2009-11-22 14:37:06.903000+00:00,NaN,2012-12-07 14:13:21.357000+00:00,2011-11-19 05:08:22.227000+00:00,None,50776.0,None,7315.0,None,1,1,ms-accessasp-classic,3877
971724,1806077,painting ticks on a zoomable timeline,<p>I am creating a timeline where I want to pa...,NaN,2,2,NaT,2009-11-26 23:13:20.640000+00:00,1.0,2014-06-18 15:51:56.300000+00:00,2014-06-18 15:51:56.300000+00:00,None,2246344.0,None,97688.0,None,1,1,painttimelinetimelinemarkers,525
971725,1839830,Subgraph algorithm,<p>I would like to know if there is an efficie...,1839857.0,2,3,NaT,2009-12-03 13:21:27.060000+00:00,NaN,2009-12-04 09:50:28.653000+00:00,2009-12-04 09:50:28.653000+00:00,None,208171.0,None,208171.0,None,1,1,algorithmdata-structuresgraph,2018
971726,1895811,Creating an Excel workbook in isolated storage,<p>Can I create an Excel workbook in the isola...,NaN,2,0,NaT,2009-12-13 07:07:26.630000+00:00,NaN,2012-06-12 01:08:36.673000+00:00,2012-06-12 01:08:36.673000+00:00,None,651104.0,None,228533.0,None,1,1,silverlightexcelstorage,502
971727,1898313,Rails foreign key is nil in nested form,<p>I have a couple models (Site and Server) th...,1898828.0,2,1,NaT,2009-12-14 00:12:34.577000+00:00,0.0,2009-12-14 03:57:48.380000+00:00,2009-12-14 03:37:49.330000+00:00,None,65311.0,None,65311.0,None,1,1,ruby-on-railsassociations,2469
971728,1950250,"Is there a better, less cumbersome way to extr...",<p>Let's say I am working in a .aspx page (or ...,NaN,2,0,NaT,2009-12-23 01:45:01.577000+00:00,0.0,2013-02-25 20:42:38.050000+00:00,2013-02-25 20:42:38.050000+00:00,None,889949.0,None,7173.0,None,1,1,c#asp.netasp.net-mvcinline-code,199

In [5]:
# write the dataframe to a tsv
dfPostQuestionsFiltered.to_csv("data/stackoverflow/PostQuestionsFiltered.tsv", sep='\t')

In [18]:
del dfPostQuestionsFiltered

In [20]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST QUESTIONS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfPostQuestionsFiltered = pd.read_csv("data/stackoverflow/PostQuestionsFiltered.tsv", sep='\t')

In [21]:
dfPostQuestionsFiltered

,Unnamed: 0,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,...,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,0,32514327,Compiling graph-tool on RHEL,<p>I need to use Python's graph-tool on a RHEL...,32525566.0,1,5,NaN,2015-09-11 01:57:28.747000+00:00,NaN,...,2015-09-11 11:59:28.830000+00:00,NaN,1159005.0,NaN,1159005.0,NaN,1,1,boostcompilationconfigurerhelgraph-tool,465
1,1,32770176,"in Java, how can I map String to a Set<String>...","<p>I need a HashMap, which the key is String a...",32770240.0,4,5,NaN,2015-09-24 20:18:56.413000+00:00,NaN,...,NaN,NaN,NaN,NaN,4839810.0,NaN,1,1,javaoopobjecthashmapset,3281
2,2,32743621,Bypass Google Maps Directions limits,<p>I've to make a map with multiple directions...,32755498.0,1,5,NaN,2015-09-23 15:26:13.510000+00:00,NaN,...,NaN,NaN,NaN,NaN,2435421.0,NaN,1,-1,google-mapsdirectionslimits,468
3,3,32610422,React and d3.js - attaching event handlers,<p>I'm working on a project using React for my...,NaN,0,5,NaN,2015-09-16 13:45:13.790000+00:00,NaN,...,NaN,NaN,NaN,NaN,645070.0,NaN,1,0,javascriptd3.jsreactjs,473
4,4,32740005,JavaFX Chart axis label formatting,<p>I wrote a simple program to monitor my ping...,32741170.0,1,5,NaN,2015-09-23 12:45:32.097000+00:00,0.0,...,2015-09-23 16:26:39.820000+00:00,NaN,3941856.0,NaN,3941856.0,NaN,1,3,javachartsjavafxlabellinechart,8952
5,5,32508423,VBA return 2 variants in MsgBox,<p>This is the start to a simple mathematical ...,32508634.0,1,5,NaN,2015-09-10 17:41:18.993000+00:00,NaN,...,2015-09-10 17:48:01.113000+00:00,NaN,4974730.0,NaN,4974730.0,NaN,1,0,excelvbaexcel-vbamathoffice-2013,252
6,6,32798477,MatPlotLib on Tkinter finished with exit code ...,<p>The following code works well in Python 2.7...,32800404.0,2,6,NaN,2015-09-26 14:53:55.597000+00:00,NaN,...,NaN,NaN,NaN,NaN,5181181.0,NaN,1,1,python-3.xmatplotlibtkinter,532
7,7,32773539,AssertionError during idle_check in IMAPClient,<p>I am attempting to have a python script tha...,NaN,0,6,NaN,2015-09-25 01:48:18.060000+00:00,1.0,...,2015-09-25 10:46:43.070000+00:00,NaN,2689797.0,NaN,2689797.0,NaN,1,2,pythonemailgmail-imapimapclient,299
8,8,32415262,How to let the command window open while execu...,<p>I am facing a strange issue. I have an appl...,NaN,0,6,NaN,2015-09-05 16:25:12.270000+00:00,1.0,...,2015-09-05 16:27:05.873000+00:00,NaN,354974.0,NaN,3655102.0,NaN,1,0,c#command-line,48
9,9,32587276,Use VBA and Shell (CMD) to launch R script and...,<p>I have an R script named <code>plot.R</code...,NaN,0,6,NaN,2015-09-15 13:23:27.993000+00:00,NaN,...,NaN,NaN,NaN,NaN,5202253.0,NaN,1,0,rvbaplotcmd,305
10,10,32704383,Make Highcharts column chart bars as wide as m...,<p>I have this Highcharts column chart:</p>\r\...,NaN,1,6,NaN,2015-09-21 20:53:39.377000+00:00,NaN,...,NaN,NaN,NaN,NaN,2023979.0,NaN,1,0,highcharts,51
11,11,32604064,Grab data from graph,"<p>I have a graph saved as *.jpeg, and I would...",NaN,0,6,NaN,2015-09-16 09:01:43.167000+00:00,NaN,...,NaN,NaN,NaN,NaN,3551644.0,NaN,1,0,rplotextract,56
12,12,32679974,"Creating 33 URLs from 169 Values, without dupl...","<p>I had previously used Excel for this, but w...",NaN,0,6,NaN,2015-09-20 13:34:31.663000+00:00,NaN,...,2018-07-09 18:41:45.953000+00:00,NaN,-1.0,NaN,915204.0,NaN,1,1,arraysrubyexcel-vba23andme-apivba,62
13,13,32694330,Save .xls file in Java,<p>I made an application that reads some data ...,NaN,0,6,NaN,2015-09-21 11:41:20.077000+00:00,NaN,...,2015-09-21 15:06:34.643000+00:00,NaN,1505120.0,NaN,4382433.0,NaN,1,0,javaexceljxl,65
14,14,32509528,'if' statement sometimes doesn't work,"<p><div class=""snippet"" data-lang=""js"" data-hi...",NaN,1,6,NaN,2015-09-10 18:47:24.840000+00:00,NaN,...,2015-09-10 21:49:41.360000+00:00,NaN,1505120.0,NaN,4354142.0,NaN,1,0,javascriptif-statementgoogle-sheets,68
15,15,32568942,How to disable cut/copy option for all cells i...,<p>/*****\r\n<strong>--EDIT--</strong>\r\n<str...,NaN,1,6,NaN,2015-09-14 15:53:26.533000+00:00,1.0,...,2015-09-16 11:58:19.323000+00:00,NaN,5334563.0,NaN,5334563.0,NaN,1,1,c#wpfexcel,837
16,16,32638244,Create function but only for use in VBA enviro...,<p>This is new to me - I've created a function...,32638594.0,2,6,NaN,2015-09-17 19:11:17.123000+00:00,1.0,...,2015-09-17 19:59:22.627000+00:00,NaN,1505120.0,NaN,1693085.0,NaN,1,1,excelvbafunctionexcel-vba,77
17,17,32489205,How to programmatically overlap arbitrary stat...,<p>I am looking for a way to automatically plo...,32498175.0,1,6,NaN,2015-09-09 21:08:51.507000+00:00,NaN,...,2015-09-10 15:16:51.900000+00:00,NaN,992358.0,NaN,992358.0,NaN,1,3,rggplot2,91
18,18,32481356,recursive call in looping a list,<p>I m trying to loop a list of users to find ...,32482671.0,3,6,NaN,2015-09-09 13:48:56.197000+00:00,NaN,...,2015-09-09 14:23:43.167000+00:00,NaN,4317989.0,NaN,4317989.0,NaN,1,1,javaalgorithmgraph-algorithm,96
19,19,32598820,Get all the nodes connected to a node in Apach...,<p>Suppose we have got the input in Apache Gra...,32601726.0,1,6,NaN,2015-09-16 02:36:51.033000+00:00,3.0,...,2015-09-16 06:44:40.860000+00:00,NaN,1560062.0,NaN,3398339.0,NaN,1,6,scalagraphapache-sparkspark-graphx,2144
20,20,32776920,Take snapshot of HighChart with render.text.css,<p>I have a simple highChart with x-axis label...,32841169.0,1,6,NaN,2015-09-25 07:25:48.020000+00:00,1.0,...,2015-09-29 04:37:34.930000+00:00,NaN,4753301.0,NaN,4753301.0,NaN,1,0,javascriptsvghighchartsscreenshotcanvg,359
21,21,32429292,"Get user's home, work and starred locations li...",<p>When in Google Inbox you go to snooze a mes...,NaN,2,6,NaN,2015-09-06 23:28:59.850000+00:00,10.0,...,2015-09-08 00:13:09.457000+00:00,NaN,13163.0,NaN,13163.0,NaN,1,27,androidgoogle-mapsgoogle-apigoogle-now,3175
22,22,32570299,Bash: How to capture Filename Expansion? (expa...,<p>--<strong>Disclaimer</strong>--<br>\r\nI am...,32570707.0,1,6,NaN,2015-09-14 17:15:54.303000+00:00,NaN,...,2017-04-13 12:36:24.867000+00:00,NaN,-1.0,NaN,843542.0,NaN,1,0,bashshellcommand-linewildcardglob,616
23,23,32841258,"android getting local image path as https, how...",<p>I've fetched a user selected image from gal...,32862356.0,3,6,NaN,2015-09-29 10:07:56.157000+00:00,NaN,...,2015-09-29 17:26:37.027000+00:00,NaN,5155835.0,NaN,5155835.0,NaN,1,0,androidandroid-imageviewandroid-imageandroid-b...,882
24,24,32640005,Google maps coordinates view,"<p>I have a regular map I can zoom in/out, mov...",32641068.0,1,6,NaN,2015-09-17 21:07:40.677000+00:00,NaN,...,2015-09-17 21:40:50.237000+00:00,NaN,956575.0,NaN,956575.0,NaN,1,0,google-maps,131
25,25,32492118,NSOutlineViewDelegate rowViewForItem being cal...,<p>I have a custom subclass of NSOutlineView i...,NaN,0,6,NaN,2015-09-10 02:26:52.483000+00:00,NaN,...,2015-09-10 08:52:46.980000+00:00,NaN,1527934.0,NaN,2488130.0,NaN,1,0,objective-cmacoscocoaappkitnsoutlineview,388
26,26,32552845,Count the data inside Map conditionally,"<p>I have a <code>Map&lt;String, List&lt;Strin...",NaN,1,6,NaN,2015-09-13 18:04:30.643000+00:00,NaN,...,2015-09-14 04:41:38.500000+00:00,NaN,1275683.0,NaN,1275683.0,NaN,1,0,javahashmap,145
27,27,32600880,ggplot2 apply different color with matching ar...,<p>Step 1: get the index price from 1990-01-01...,NaN,1,6,NaN,2015-09-16 06:04:14.853000+00:00,NaN,...,2015-09-16 08:37:29.373000+00:00,NaN,5125810.0,NaN,5125810.0,NaN,1,0,rggplot2,169
28,28,32415415,Google Maps API must now use a Server Key?,<p>My website makes use of Google Maps API. I ...,NaN,1,6,NaN,2015-09-05 16:40:46.043000+00:00,NaN,...,2015-09-05 18:31:26.493000+00:00,NaN,2070775.0,NaN,2070775.0,NaN,1,0,google-maps,681
29,29,32636123,JSON data undefined from external file in d3.js?,<p>I'm developing a d3.js app that reads data ...,32636551.0,1,6,NaN,2015-09-17 17:07:49.613000+00:00,1.0,...,2015-09-17 17:26:39.893000+00:00,NaN,2740614.0,NaN,2740614.0,NaN,1,0,javascriptjsond3.js,187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971699,971699,2221052,Import query results into tool through VB.NET,<p>I am writing a tool to import a database qu...,NaN,2,1,NaN,2010-02-08 10:57:43.953000+00:00,NaN,...,2010-07-16 23:45:04.727000+00:00,NaN,63550.0,NaN,238147.0,NaN,1,0,vb.netexcel,405
971700,971700,2321728,how to map SampleCount property using NHibernate,"<p>I have two tables - Run and Sample, where S...",2325964.0,2,0,NaN,2010-02-23 21:09:08.703000+00:00,NaN,...,NaN,NaN,NaN,NaN,80002.0,NaN,1,0,nhibernatenhibernate-mapping,104
971701,971701,1426146,How to extract numbers from text file using Wi...,<p>I need to do the following using cmd (Windo...,1426593.0,2,1,NaN,2009-09-15 09:31:58.550000+00:00,NaN,...,2009-10-17 23:15:53.133000+00:00,NaN,100754.0,NaN,154180.0,NaN,1,1,windowscommand-linecmd,4087
971702,971702,1437780,Google maps satellite view,<p>I'm using the <em>google maps API</em> with...,1458000.0,2,2,NaN,2009-09-17 09:49:39.907000+00:00,2.0,...,2009-09-21 11:28:56.190000+00:00,NaN,15255.0,NaN,146864.0,NaN,1,1,google-mapsmapsopenstreetmap,3711
971703,971703,1441748,Best way to stop Firefox pipe-lining from mess...,<p>I've noticed that my pageview counts are be...,1441881.0,2,0,NaN,2009-09-17 23:01:27.990000+00:00,NaN,...,NaN,NaN,NaN,NaN,84387.0,NaN,1,1,phpapachefirefoxpipeline,468
971704,971704,1456266,Clone existing recordset to excel recordset,<p>I have a recordset that contains all of the...,1458534.0,2,0,NaN,2009-09-21 19:09:21.113000+00:00,NaN,...,2009-09-22 06:56:00.723000+00:00,NaN,17516.0,NaN,141594.0,NaN,1,1,excelasp-classicvbscriptadodbrecordset,1811
971705,971705,1476978,creating charts in jquery,<p>I'd like to create a chart that breaks down...,NaN,2,0,NaN,2009-09-25 12:15:23.557000+00:00,2.0,...,NaN,NaN,NaN,rashcroft1,NaN,NaN,1,1,javascriptjquerycharts,2991
971706,971706,1533183,Wrapping an image around 3d object for easy 2d...,<p>Looking for method for wrapping a 2d image ...,NaN,2,2,NaN,2009-10-07 17:52:06.950000+00:00,NaN,...,NaN,NaN,NaN,NaN,121461.0,NaN,1,1,algorithmimagegraphics3ddistortion,1872
971707,971707,1551276,Need JET 4.0 Drivers,<p>I am using an ExcelProvider with Microsoft....,1551939.0,2,0,NaN,2009-10-11 17:51:29.203000+00:00,NaN,...,2013-07-24 17:09:32.920000+00:00,NaN,1065525.0,NaN,24333.0,NaN,1,1,excelms-officeoledbjet,362
971708,971708,1552438,Working with Data.frames in R (Using SAS code ...,"<p>I've been mostly working in SAS of late, bu...",NaN,2,0,NaN,2009-10-12 02:37:07.560000+00:00,NaN,...,2011-10-24 09:09:10.280000+00:00,NaN,709619.0,user188181,NaN,NaN,1,1,rsasdataframe,818
971709,971709,1576714,Redirect all HTTP-Requests with *.asp to one s...,<p>Is it possible on an IIS to redirect all fi...,1581717.0,2,2,NaN,2009-10-16 07:57:07.027000+00:00,NaN,...,2011-12-01 19:23:10.033000+00:00,NaN,3043.0,NaN,191075.0,NaN,1,1,iisasp-classiccoldfusionhttp-redirect,739
971710,971710,1582968,How would I position a marker at the bottom of...,"<p>I have a webpage that <a href=""http://www.b...",1583100.0,2,1,NaN,2009-10-17 19:07:30.190000+00:00,2.0,...,2010-02-23 11:03:00.040000+00:00,NaN,184842.0,NaN,147731.0,NaN,1,1,javascriptgoogle-mapsgoogle-maps-markersgoogle...,2539
971711,971711,1608399,ASP.Net MVC Wildcard Mappings IIS 6.0 - Page C...,<p>I added wildcard mappings to my website in ...,1609434.0,2,0,NaN,2009-10-22 16:23:54.827000+00:00,0.0,...,NaN,NaN,NaN,NaN,46780.0,NaN,1,1,asp.net-mvciiswildcard-mapping,1139
971712,971712,1629054,Excel formula for time comparision,<p>while writing an formula for data in a exce...,1629087.0,2,2,NaN,2009-10-27 06:32:48.907000+00:00,NaN,...,2009-10-27 06:51:34.353000+00:00,NaN,166686.0,NaN,193133.0,NaN,1,1,exceldatetime,400
971713,971713,1630012,Automapper Mapping,<p>I'm trying to map an object with property n...,NaN,2,1,NaN,2009-10-27 10:49:35.520000+00:00,1.0,...,2009-10-27 11:40:05.330000+00:00,NaN,5853.0,NaN,5853.0,NaN,1,1,.netautomapper,2369
971714,971714,1633810,Image series (animation) over Google Maps,<p>I'm new to Google map api. My goal is to ov...,1635707.0,2,0,NaN,2009-10-27 21:33:23.560000+00:00,2.0,...,2009-10-28 07:48:02.407000+00:00,NaN,41983.0,NaN,182843.0,NaN,1,1,asp.netgoogle-maps,1594
971715,971715,1697356,How to transition between two images using a g...,"<p>Imagine you have two images A and B, and a ...",1697564.0,2,0,NaN,2009-11-08 17:58:11.270000+00:00,2.0,...,2009-11-09 17:02:14.970000+00:00,NaN,39926.0,NaN,39926.0,NaN,1,1,language-agnosticgraphicstransitions,641
971716,971716,1704369,PHP Excel Reader : get strikeout / strikethrou...,<p>I am looking for way to parse the strikeout...,1704660.0,2,1,NaN,2009-11-09 22:28:22.193000+00:00,1.0,...,2009-11-10 02:09:32.080000+00:00,NaN,2766176.0,NaN,401323.0,NaN,1,1,phpexcelparsing,2475
971717,971717,1720169,What does this Python code do: shell=(sys.plat...,"<p>I don't understand what this code is doing,...",1720192.0,2,0,NaN,2009-11-12 05:51:49.013000+00:00,NaN,...,2009-11-12 05:59:44.660000+00:00,NaN,207258.0,NaN,207258.0,NaN,1,1,pythonmacoscommand-line,450
971718,971718,1723943,Easiest way to get the image of a map from goo...,<p>I have a hundred of UK postcodes and need t...,NaN,2,0,NaN,2009-11-12 17:25:29.120000+00:00,NaN,...,NaN,NaN,NaN,ORA600,NaN,NaN,1,1,google-maps,72
971719,971719,1728852,Mysql Importing new codes from excel,<p>I have a CSV file with mappings from projec...,1728924.0,2,0,NaN,2009-11-13 12:11:05.777000+00:00,NaN,...,2009-11-13 12:30:11.423000+00:00,NaN,112517.0,NaN,111052.0,NaN,1,1,mysqlexcelimport,142
971720,971720,1744406,what is the name of the convention used in thi...,<p>I found this diagram in the JSON specificat...,1744430.0,2,0,NaN,2009-11-16 19:44:07.833000+00:00,NaN,...,2019-05-09 07:04:40.167000+00:00,NaN,4751173.0,NaN,42223.0,NaN,1,1,jsondiagramspecificationsbnf,129
971721,971721,1748902,Linux inter-process reentrant semaphore,<p>I'm porting a Windows application to Linux ...,1749086.0,2,1,NaN,2009-11-17 13:34:04.997000+00:00,1.0,...,NaN,NaN,NaN,NaN,212865.0,NaN,1,1,c++clinuxsemaphoreinterprocess,2635
971722,971722,1775697,C# DataTable: Add new row throws error using A...,<p>I have a collection </p>\r\n\r\n<pre><code...,1776616.0,2,0,NaN,2009-11-21 15:00:09.100000+00:00,1.0,...,NaN,NaN,NaN,NaN,198544.0,NaN,1,1,c#collectionsdatatableauto-incrementdatarow,6763
971723,971723,1778868,Access and classic ASP error 80004005 System r...,<p>An old site on shared hosting has developed...,1778951.0,2,2,NaN,2009-11-22 14:37:06.903000+00:00,NaN,...,2011-11-19 05:08:22.227000+00:00,NaN,50776.0,NaN,7315.0,NaN,1,1,ms-accessasp-classic,3877
971724,971724,1806077,painting ticks on a zoomable timeline,<p>I am creating a timeline where I want to pa...,NaN,2,2,NaN,2009-11-26 23:13:20.640000+00:00,1.0,...,2014-06-18 15:51:56.300000+00:00,NaN,2246344.0,NaN,97688.0,NaN,1,1,painttimelinetimelinemarkers,525
971725,971725,1839830,Subgraph algorithm,<p>I would like to know if there is an efficie...,1839857.0,2,3,NaN,2009-12-03 13:21:27.060000+00:00,NaN,...,2009-12-04 09:50:28.653000+00:00,NaN,208171.0,NaN,208171.0,NaN,1,1,algorithmdata-structuresgraph,2018
971726,971726,1895811,Creating an Excel workbook in isolated storage,<p>Can I create an Excel workbook in the isola...,NaN,2,0,NaN,2009-12-13 07:07:26.630000+00:00,NaN,...,2012-06-12 01:08:36.673000+00:00,NaN,651104.0,NaN,228533.0,NaN,1,1,silverlightexcelstorage,502
971727,971727,1898313,Rails foreign key is nil in nested form,<p>I have a couple models (Site and Server) th...,1898828.0,2,1,NaN,2009-12-14 00:12:34.577000+00:00,0.0,...,2009-12-14 03:37:49.330000+00:00,NaN,65311.0,NaN,65311.0,NaN,1,1,ruby-on-railsassociations,2469
971728,971728,1950250,"Is there a better, less cumbersome way to extr...",<p>Let's say I am working in a .aspx page (or ...,NaN,2,0,NaN,2009-12-23 01:45:01.577000+00:00,0.0,...,2013-02-25 20:42:38.050000+00:00,NaN,889949.0,NaN,7173.0,NaN,1,1,c#asp.netasp.net-mvcinline-code,199

In [28]:
# retrieving the answers that belong to the questions retrieved above

sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.posts_answers` WHERE parent_id IN 
    (SELECT id FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%d3%' 
    OR tags LIKE '%tableau%'
    OR tags LIKE '%ggplot%'
    OR tags LIKE '%plotly%'
    OR tags LIKE '%matplotlib%'
    OR tags LIKE '%excel%'
    OR tags LIKE '%sheets%'
    OR tags LIKE '%seaborn%'
    OR tags LIKE '%altair%'
    OR tags LIKE '%powerbi%'
    OR tags LIKE '%qlik%'
    OR tags LIKE '%chart%'
    OR tags LIKE '%graph%'
    OR tags LIKE '%sas%'
    OR tags LIKE '%spss%'
    OR tags LIKE '%plot%'
    OR tags LIKE '%stata%'
    OR tags LIKE '%line%'
    OR tags LIKE '%visual%'
    OR tags LIKE '%viz%'
    OR tags LIKE '%linechart%'
    OR tags LIKE '%diagram%'
    OR tags LIKE '%map%')
    AND
    tags NOT LIKE '%visual-studio%'
    AND
    tags NOT LIKE '%visual-c++%')
"""
dfPostAnswersFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [29]:
np.shape(dfPostAnswersFiltered)

(1266934, 20)

In [30]:
dfPostAnswersFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,31323756,None,"<p>Not really that difficult, there are only t...",None,None,4,NaT,2015-07-09 16:53:18.617000+00:00,None,2015-07-11 02:24:03.557000+00:00,2015-07-11 02:24:03.557000+00:00,None,2344142.0,None,2344142.0,31323555,2,2,None,None
1,31411442,None,<p>I am not sure i understand your question bu...,None,None,4,NaT,2015-07-14 15:49:43.543000+00:00,None,2015-07-14 15:49:43.543000+00:00,NaT,None,NaN,None,3496382.0,31411322,2,2,None,None
2,31447207,None,<p>By searching on the Internet you could have...,None,None,4,NaT,2015-07-16 06:52:37.280000+00:00,None,2015-07-16 07:01:51.303000+00:00,2015-07-16 07:01:51.303000+00:00,None,5118384.0,None,5118384.0,31447168,2,2,None,None
3,31627010,None,"<p>Your path has blanks, so you need surroundi...",None,None,4,NaT,2015-07-25 13:35:20.470000+00:00,None,2015-07-25 14:07:44.393000+00:00,2015-07-25 14:07:44.393000+00:00,None,2077064.0,None,2077064.0,31626827,2,2,None,None
4,31697233,None,"<p>You will have to use <a href=""http://matplo...",None,None,4,NaT,2015-07-29 10:02:04.520000+00:00,None,2015-07-29 10:23:21.417000+00:00,2015-07-29 10:23:21.417000+00:00,None,1469380.0,None,1469380.0,31696988,2,2,None,None
5,31729880,None,<p>It looks like the problem is with the value...,None,None,4,NaT,2015-07-30 17:02:21.990000+00:00,None,2015-07-30 17:02:21.990000+00:00,NaT,None,NaN,None,5045195.0,31729501,2,2,None,None
6,31366441,None,<p>You could try this expression:</p>\n\n<pre>...,None,None,4,NaT,2015-07-12 09:45:59.523000+00:00,None,2015-07-12 09:45:59.523000+00:00,NaT,None,NaN,None,3527297.0,31365188,2,3,None,None
7,31419980,None,"<p>Direct2D, more clear <strong>ID2D1GeometryS...",None,None,4,NaT,2015-07-15 01:24:39.170000+00:00,None,2015-07-15 01:45:45.457000+00:00,2015-07-15 01:45:45.457000+00:00,None,2546626.0,None,2546626.0,31269690,2,3,None,None
8,31515223,None,<p>Your very first script is actually just the...,None,None,4,NaT,2015-07-20 11:23:00.983000+00:00,None,2015-07-20 12:55:32.787000+00:00,2015-07-20 12:55:32.787000+00:00,None,1179880.0,None,1179880.0,31514205,2,3,None,None
9,31522942,None,<p><code>scanf</code> is <strong>not</strong> ...,None,None,4,NaT,2015-07-20 17:40:03.590000+00:00,None,2015-07-20 18:09:51.473000+00:00,2015-07-20 18:09:51.473000+00:00,None,3545273.0,None,3545273.0,31522555,2,3,None,None
10,31550820,None,<p>The HERE-API doesn't implement a callback l...,None,None,4,NaT,2015-07-21 22:35:31.883000+00:00,None,2015-07-21 22:35:31.883000+00:00,NaT,None,NaN,None,459897.0,31544767,2,3,None,None
11,31574931,None,<p>This is by far not the best solution in ter...,None,None,4,NaT,2015-07-22 22:12:17.250000+00:00,None,2015-07-22 22:18:38.993000+00:00,2015-07-22 22:18:38.993000+00:00,None,5123306.0,None,5123306.0,31574403,2,3,None,None
12,31662878,None,<p>I can do the example for <code>sev_alpha</c...,None,None,4,NaT,2015-07-27 20:41:00.620000+00:00,None,2015-07-27 20:52:33.673000+00:00,2015-07-27 20:52:33.673000+00:00,None,717481.0,None,717481.0,31662080,2,3,None,None
13,31694603,None,<pre><code>Option Explicit\nSub SaveAsPDF()\n ...,None,None,4,NaT,2015-07-29 08:01:36.010000+00:00,None,2017-07-25 20:17:40.093000+00:00,2017-07-25 20:17:40.093000+00:00,None,4539709.0,None,4539709.0,31694081,2,3,None,None
14,31743614,None,<p>I think the problem lies in the fact that y...,None,None,4,NaT,2015-07-31 10:08:40.870000+00:00,None,2015-07-31 10:08:40.870000+00:00,NaT,None,NaN,None,4751173.0,31743240,2,3,None,None
15,31298140,None,<p><code>Vc</code> should be a <code>factor</c...,None,None,4,NaT,2015-07-08 16:13:42.563000+00:00,None,2015-07-08 16:13:42.563000+00:00,NaT,None,NaN,None,2415684.0,31297196,2,4,None,None
16,31303956,None,<p>You have to perform a GraphRequest like the...,None,None,4,NaT,2015-07-08 21:18:28.410000+00:00,None,2015-07-08 21:26:01.803000+00:00,2015-07-08 21:26:01.803000+00:00,None,1900721.0,None,1900721.0,31303782,2,4,None,None
17,31427154,None,<p>Try this way in CDVPlugin.m</p>\n\n<pre><co...,None,None,4,NaT,2015-07-15 09:55:30.443000+00:00,None,2015-07-15 09:55:30.443000+00:00,NaT,None,NaN,None,4169569.0,31426401,2,4,None,None
18,31658165,None,<p>While it is possible <em>to specify</em> ta...,None,None,4,NaT,2015-07-27 16:14:19.233000+00:00,None,2015-07-27 21:07:32.683000+00:00,2015-07-27 21:07:32.683000+00:00,None,5161413.0,None,5161413.0,17626159,2,4,None,None
19,31669433,None,<p>The tooltips are dynamically appended to th...,None,None,4,NaT,2015-07-28 07:01:53.930000+00:00,None,2015-07-28 07:01:53.930000+00:00,NaT,None,NaN,None,519413.0,31669246,2,4,None,None
20,31685347,None,<p>Use this:</p>\n\n<pre><code>.ComboBox1.Text...,None,None,4,NaT,2015-07-28 19:23:25.137000+00:00,None,2015-07-28 19:54:08.467000+00:00,2015-07-28 19:54:08.467000+00:00,None,4916894.0,None,4916894.0,31685120,2,4,None,None
21,31680887,None,<ol>\n<li>Right-click on <code>SourceRow</code...,None,None,4,NaT,2015-07-28 15:31:08.280000+00:00,None,2015-07-28 15:31:08.280000+00:00,NaT,None,NaN,None,2237785.0,31680465,2,5,None,None
22,31581501,None,<p>I would plot it like this. Note that size n...,None,None,4,NaT,2015-07-23 08:04:06.527000+00:00,None,2015-07-23 08:11:04.930000+00:00,2015-07-23 08:11:04.930000+00:00,None,322912.0,None,322912.0,31581213,2,6,None,None
23,31601382,None,<p>Here's my implementation of moving the my l...,None,None,4,NaT,2015-07-24 02:47:20.033000+00:00,None,2015-07-24 02:47:20.033000+00:00,NaT,None,NaN,None,5096562.0,31591524,2,6,None,None
24,31691276,None,<p>You can also do some magic with the base <c...,None,None,4,NaT,2015-07-29 04:33:28.187000+00:00,None,2015-08-03 09:50:53.167000+00:00,2015-08-03 09:50:53.167000+00:00,None,496803.0,None,496803.0,31690789,2,6,None,None
25,31402414,None,"<p>You can use <a href=""http://en.cppreference...",None,None,4,NaT,2015-07-14 09:11:28.673000+00:00,None,2015-07-14 09:11:28.673000+00:00,NaT,None,NaN,None,1295063.0,31402314,2,7,None,None
26,31647520,None,<pre><code>protected void userLocationMap() {\...,None,None,4,NaT,2015-07-27 07:43:44.827000+00:00,None,2015-07-27 13:48:33.740000+00:00,2015-07-27 13:48:33.740000+00:00,None,4682365.0,None,4682365.0,31647159,2,8,None,None
27,31639169,None,<p>ifaour has the right idea of how to use pag...,None,None,4,NaT,2015-07-26 16:15:36.247000+00:00,None,2015-09-06 12:21:20.650000+00:00,2015-09-06 12:21:20.650000+00:00,None,4112664.0,None,4105699.0,31398145,2,10,None,None
28,31789658,None,<p>I use a keyboard shortcut to past the value...,None,None,4,NaT,2015-08-03 14:16:56.797000+00:00,None,2018-05-09 18:35:35.110000+00:00,2018-05-09 18:35:35.110000+00:00,None,836169.0,None,3447515.0,31789185,2,11,None,None
29,31293174,None,<p>When performing <strong>UI Updates in closu...,None,None,4,NaT,2015-07-08 12:46:51.883000+00:00,None,2017-02-13 12:40:23.227000+00:00,2017-02-13 12:40:23.227000+00:00,None,3970292.0,None,3970292.0,31287149,2,19,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266904,39630189,None,<p>i dont know for other assemblers but in tas...,None,None,3,NaT,2016-09-22 04:18:35.087000+00:00,None,2016-09-23 02:35:03.017000+00:00,2016-09-23 02:35:03.017000+00:00,None,224132.0,None,6125442.0,39628953,2,2,None,None
1266905,39649520,None,<p>If you don't need to keep arr1 in its origi...,None,None,3,NaT,2016-09-22 21:59:02.273000+00:00,None,2016-09-22 22:10:36.957000+00:00,2016-09-22 22:10:36.957000+00:00,None,478884.0,None,478884.0,39649467,2,2,None,None
1266906,39652466,None,<p>You can receive the 1-based index position ...,None,None,3,NaT,2016-09-23 04:08:27.260000+00:00,None,2016-09-23 04:08:27.260000+00:00,NaT,None,NaN,user4039065,NaN,39652293,2,2,None,None
1266907,39084442,None,<p>There is one array formula solution provide...,None,None,3,NaT,2016-08-22 16:26:56.107000+00:00,None,2016-08-22 16:26:56.107000+00:00,NaT,None,NaN,user4039065,NaN,39083611,2,3,None,None
1266908,39163708,None,<p>Use <code>svnmucc put SRC-FILE URL</code>.<...,None,None,3,NaT,2016-08-26 10:06:32.340000+00:00,None,2016-08-26 10:08:02.890000+00:00,2016-08-26 10:08:02.890000+00:00,None,761095.0,None,761095.0,39162715,2,3,None,None
1266909,39189046,None,<p><code>viewBox</code> has an uppercase B:</p...,None,None,3,NaT,2016-08-28 07:41:44.993000+00:00,None,2016-08-28 07:54:37.513000+00:00,2016-08-28 07:54:37.513000+00:00,None,5768908.0,None,5768908.0,39188877,2,3,None,None
1266910,39242948,None,<p>Your idea to use <code>lapply</code> is one...,None,None,3,NaT,2016-08-31 07:09:36.920000+00:00,None,2016-08-31 07:15:16.607000+00:00,2016-08-31 07:15:16.607000+00:00,None,1862762.0,None,1862762.0,39242727,2,3,None,None
1266911,39453905,None,<p>you probably have a <code>setlocal</code> i...,None,None,3,NaT,2016-09-12 15:30:23.077000+00:00,None,2016-09-12 15:30:23.077000+00:00,NaT,None,NaN,None,2152082.0,39453774,2,3,None,None
1266912,39495269,None,"<p>Full disclosure, I'm a member of the ZingCh...",None,None,3,NaT,2016-09-14 16:17:51.800000+00:00,None,2016-09-14 16:17:51.800000+00:00,NaT,None,NaN,None,5712661.0,39494847,2,3,None,None
1266913,39519093,None,<p>As soon as your last <code>write</code> is ...,None,None,3,NaT,2016-09-15 19:40:03.690000+00:00,None,2016-09-15 19:40:03.690000+00:00,NaT,None,NaN,None,5754797.0,39501950,2,3,None,None
1266914,39156893,None,<p>The API key may not be passed in the URL. ...,None,None,3,NaT,2016-08-26 00:59:56.897000+00:00,None,2016-08-26 00:59:56.897000+00:00,NaT,None,NaN,None,5632740.0,39154723,2,4,None,None
1266915,39248134,None,<p>Probably you should do something a little m...,None,None,3,NaT,2016-08-31 11:15:29.840000+00:00,None,2016-08-31 11:33:20.787000+00:00,2017-05-23 12:32:08.853000+00:00,None,-1.0,None,5448626.0,39201757,2,4,None,None
1266916,39297924,None,<p>you can use a blank string (<code>''</code>...,None,None,3,NaT,2016-09-02 17:31:18.120000+00:00,None,2016-09-06 12:34:00.327000+00:00,2016-09-06 12:34:00.327000+00:00,None,5090771.0,None,5090771.0,39285078,2,4,None,None
1266917,39653318,None,<p>It is as simple as</p>\n\n<pre><code>wb.VBP...,None,None,3,NaT,2016-09-23 05:38:21.870000+00:00,None,2016-09-23 05:38:21.870000+00:00,NaT,None,NaN,None,1140579.0,39653129,2,4,None,None
1266918,39210996,None,<p>A For ... Next loop using the ASCII charact...,None,None,3,NaT,2016-08-29 16:33:18.980000+00:00,None,2016-08-29 16:40:16.277000+00:00,2016-08-29 16:40:16.277000+00:00,user4039065,NaN,user4039065,NaN,39210888,2,5,None,None
1266919,39375477,None,<p>They're stored internally in the database. ...,None,None,3,NaT,2016-09-07 16:52:17.623000+00:00,None,2016-09-07 16:52:17.623000+00:00,NaT,None,NaN,None,736079.0,39374159,2,5,None,None
1266920,39402126,None,<p>It is a circle -- The problem is that the a...,None,None,3,NaT,2016-09-09 00:36:49.637000+00:00,None,2016-09-09 00:36:49.637000+00:00,NaT,None,NaN,None,748858.0,39402109,2,6,None,None
1266921,39371604,None,"<p>I usually use a pattern like this, which is...",None,None,3,NaT,2016-09-07 13:44:28.780000+00:00,None,2016-09-13 12:14:52.903000+00:00,2016-09-13 12:14:52.903000+00:00,None,169781.0,None,169781.0,39365970,2,7,None,None
1266922,39406305,None,<p>The other answer is correct. You could also...,None,None,3,NaT,2016-09-09 07:39:55.320000+00:00,None,2017-03-11 17:46:14.120000+00:00,2017-03-11 17:46:14.120000+00:00,None,54467.0,None,54467.0,39391437,2,7,None,None
1266923,39551998,None,<blockquote>\n <p>Is the because it's too slo...,None,None,3,NaT,2016-09-17 21:39:28.033000+00:00,None,2016-09-17 21:39:28.033000+00:00,NaT,None,NaN,None,115145.0,39551774,2,8,None,None
1266924,39178633,None,<p>I solved this problem in my map fragment by...,None,None,3,NaT,2016-08-27 07:31:17.907000+00:00,None,2016-08-27 07:31:17.907000+00:00,NaT,None,NaN,None,6751239.0,14489880,2,11,None,None
1266925,39531911,None,"<p>@DanDan's answer, using C++11 is:</p>\n\n<p...",None,None,3,NaT,2016-09-16 12:47:48.270000+00:00,None,2016-09-16 12:47:48.270000+00:00,NaT,None,NaN,None,1349673.0,110157,2,11,None,None
1266926,39426143,None,<p>You need to use the same encoding in your G...,None,None,3,NaT,2016-09-10 12:35:50.470000+00:00,None,2016-09-10 12:35:50.470000+00:00,NaT,None,NaN,None,142162.0,39426096,2,12,None,None
1266927,39256428,None,"<p>This is a common <a href=""https://en.wikipe...",None,None,3,NaT,2016-08-31 18:16:43.543000+00:00,None,2017-09-22 05:02:12.783000+00:00,2017-09-22 05:02:12.783000+00:00,None,641914.0,None,2173016.0,39256309,2,17,None,None
1266928,39425829,None,<p>The following code worked for me without sy...,None,None,3,NaT,2016-09-10 11:57:14.217000+00:00,None,2016-09-10 11:57:14.217000+00:00,NaT,None,NaN,None,1264304.0,3339801,2,-3,None,None
1266929,39286561,None,<p>In:</p>\n\n<pre><code>//async operation:\nT...,None,None,3,NaT,2016-09-02 07:23:13.950000+00:00,None,2016-09-06 15:25:21.513000+00:00,2016-09-06 15:25:21.513000+00:00,None,1463733.0,None,1463733.0,39286043,2,-1,None,None
1266930,39416177,None,<p>You have an error in your code. You have n...,None,None,3,NaT,2016-09-09 16:40:39.990000+00:00,None,2016-09-09 16:46:01.873000+00:00,2016-09-09 16:46:01.873000+00:00,None,4904165.0,None,4904165.0,39415527,2,-1,None,None
1266931,39086563,None,<p>You do it in exactly the same way as when y...,None,None,4,NaT,2016-08-22 18:40:35.723000+00:00,None,2016-08-22 18:40:35.723000+00:00,NaT,None,NaN,None,324584.0,39084970,2,0,None,None
1266932,39125305,None,<p>First I made a very simple userform with 5 ...,None,None,4,NaT,2016-08-24 13:55:18.397000+00:00,None,2016-08-24 13:55:18.397000+00:00,NaT,None,NaN,None,6704227.0,38845555,2,0,None,None
1266933,39126927,None,<p>I modified your SQL statement. Replace the...,None,None,4,NaT,2016-08-24 15:02:50.527000+00:00,None,2016-08-24 15:02:50.527000+00:00,NaT,None,NaN,None,6202343.0,39126025,2,0,None,None

In [31]:
# write the dataframe to a tsv
dfPostAnswersFiltered.to_csv("data/stackoverflow/PostAnswersFiltered.tsv", sep='\t')

In [32]:
del dfPostAnswersFiltered

In [33]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST ANSWERS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfPostAnswersFiltered = pd.read_csv("data/stackoverflow/PostAnswersFiltered.tsv", sep='\t')

In [34]:
dfPostAnswersFiltered

,Unnamed: 0,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,...,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,0,31323756,NaN,"<p>Not really that difficult, there are only t...",NaN,NaN,4,NaN,2015-07-09 16:53:18.617000+00:00,NaN,...,2015-07-11 02:24:03.557000+00:00,NaN,2344142.0,NaN,2344142.0,31323555,2,2,NaN,NaN
1,1,31411442,NaN,<p>I am not sure i understand your question bu...,NaN,NaN,4,NaN,2015-07-14 15:49:43.543000+00:00,NaN,...,NaN,NaN,NaN,NaN,3496382.0,31411322,2,2,NaN,NaN
2,2,31447207,NaN,<p>By searching on the Internet you could have...,NaN,NaN,4,NaN,2015-07-16 06:52:37.280000+00:00,NaN,...,2015-07-16 07:01:51.303000+00:00,NaN,5118384.0,NaN,5118384.0,31447168,2,2,NaN,NaN
3,3,31627010,NaN,"<p>Your path has blanks, so you need surroundi...",NaN,NaN,4,NaN,2015-07-25 13:35:20.470000+00:00,NaN,...,2015-07-25 14:07:44.393000+00:00,NaN,2077064.0,NaN,2077064.0,31626827,2,2,NaN,NaN
4,4,31697233,NaN,"<p>You will have to use <a href=""http://matplo...",NaN,NaN,4,NaN,2015-07-29 10:02:04.520000+00:00,NaN,...,2015-07-29 10:23:21.417000+00:00,NaN,1469380.0,NaN,1469380.0,31696988,2,2,NaN,NaN
5,5,31729880,NaN,<p>It looks like the problem is with the value...,NaN,NaN,4,NaN,2015-07-30 17:02:21.990000+00:00,NaN,...,NaN,NaN,NaN,NaN,5045195.0,31729501,2,2,NaN,NaN
6,6,31366441,NaN,<p>You could try this expression:</p>\r\n\r\n<...,NaN,NaN,4,NaN,2015-07-12 09:45:59.523000+00:00,NaN,...,NaN,NaN,NaN,NaN,3527297.0,31365188,2,3,NaN,NaN
7,7,31419980,NaN,"<p>Direct2D, more clear <strong>ID2D1GeometryS...",NaN,NaN,4,NaN,2015-07-15 01:24:39.170000+00:00,NaN,...,2015-07-15 01:45:45.457000+00:00,NaN,2546626.0,NaN,2546626.0,31269690,2,3,NaN,NaN
8,8,31515223,NaN,<p>Your very first script is actually just the...,NaN,NaN,4,NaN,2015-07-20 11:23:00.983000+00:00,NaN,...,2015-07-20 12:55:32.787000+00:00,NaN,1179880.0,NaN,1179880.0,31514205,2,3,NaN,NaN
9,9,31522942,NaN,<p><code>scanf</code> is <strong>not</strong> ...,NaN,NaN,4,NaN,2015-07-20 17:40:03.590000+00:00,NaN,...,2015-07-20 18:09:51.473000+00:00,NaN,3545273.0,NaN,3545273.0,31522555,2,3,NaN,NaN
10,10,31550820,NaN,<p>The HERE-API doesn't implement a callback l...,NaN,NaN,4,NaN,2015-07-21 22:35:31.883000+00:00,NaN,...,NaN,NaN,NaN,NaN,459897.0,31544767,2,3,NaN,NaN
11,11,31574931,NaN,<p>This is by far not the best solution in ter...,NaN,NaN,4,NaN,2015-07-22 22:12:17.250000+00:00,NaN,...,2015-07-22 22:18:38.993000+00:00,NaN,5123306.0,NaN,5123306.0,31574403,2,3,NaN,NaN
12,12,31662878,NaN,<p>I can do the example for <code>sev_alpha</c...,NaN,NaN,4,NaN,2015-07-27 20:41:00.620000+00:00,NaN,...,2015-07-27 20:52:33.673000+00:00,NaN,717481.0,NaN,717481.0,31662080,2,3,NaN,NaN
13,13,31694603,NaN,<pre><code>Option Explicit\r\nSub SaveAsPDF()\...,NaN,NaN,4,NaN,2015-07-29 08:01:36.010000+00:00,NaN,...,2017-07-25 20:17:40.093000+00:00,NaN,4539709.0,NaN,4539709.0,31694081,2,3,NaN,NaN
14,14,31743614,NaN,<p>I think the problem lies in the fact that y...,NaN,NaN,4,NaN,2015-07-31 10:08:40.870000+00:00,NaN,...,NaN,NaN,NaN,NaN,4751173.0,31743240,2,3,NaN,NaN
15,15,31298140,NaN,<p><code>Vc</code> should be a <code>factor</c...,NaN,NaN,4,NaN,2015-07-08 16:13:42.563000+00:00,NaN,...,NaN,NaN,NaN,NaN,2415684.0,31297196,2,4,NaN,NaN
16,16,31303956,NaN,<p>You have to perform a GraphRequest like the...,NaN,NaN,4,NaN,2015-07-08 21:18:28.410000+00:00,NaN,...,2015-07-08 21:26:01.803000+00:00,NaN,1900721.0,NaN,1900721.0,31303782,2,4,NaN,NaN
17,17,31427154,NaN,<p>Try this way in CDVPlugin.m</p>\r\n\r\n<pre...,NaN,NaN,4,NaN,2015-07-15 09:55:30.443000+00:00,NaN,...,NaN,NaN,NaN,NaN,4169569.0,31426401,2,4,NaN,NaN
18,18,31658165,NaN,<p>While it is possible <em>to specify</em> ta...,NaN,NaN,4,NaN,2015-07-27 16:14:19.233000+00:00,NaN,...,2015-07-27 21:07:32.683000+00:00,NaN,5161413.0,NaN,5161413.0,17626159,2,4,NaN,NaN
19,19,31669433,NaN,<p>The tooltips are dynamically appended to th...,NaN,NaN,4,NaN,2015-07-28 07:01:53.930000+00:00,NaN,...,NaN,NaN,NaN,NaN,519413.0,31669246,2,4,NaN,NaN
20,20,31685347,NaN,<p>Use this:</p>\r\n\r\n<pre><code>.ComboBox1....,NaN,NaN,4,NaN,2015-07-28 19:23:25.137000+00:00,NaN,...,2015-07-28 19:54:08.467000+00:00,NaN,4916894.0,NaN,4916894.0,31685120,2,4,NaN,NaN
21,21,31680887,NaN,<ol>\r\n<li>Right-click on <code>SourceRow</co...,NaN,NaN,4,NaN,2015-07-28 15:31:08.280000+00:00,NaN,...,NaN,NaN,NaN,NaN,2237785.0,31680465,2,5,NaN,NaN
22,22,31581501,NaN,<p>I would plot it like this. Note that size n...,NaN,NaN,4,NaN,2015-07-23 08:04:06.527000+00:00,NaN,...,2015-07-23 08:11:04.930000+00:00,NaN,322912.0,NaN,322912.0,31581213,2,6,NaN,NaN
23,23,31601382,NaN,<p>Here's my implementation of moving the my l...,NaN,NaN,4,NaN,2015-07-24 02:47:20.033000+00:00,NaN,...,NaN,NaN,NaN,NaN,5096562.0,31591524,2,6,NaN,NaN
24,24,31691276,NaN,<p>You can also do some magic with the base <c...,NaN,NaN,4,NaN,2015-07-29 04:33:28.187000+00:00,NaN,...,2015-08-03 09:50:53.167000+00:00,NaN,496803.0,NaN,496803.0,31690789,2,6,NaN,NaN
25,25,31402414,NaN,"<p>You can use <a href=""http://en.cppreference...",NaN,NaN,4,NaN,2015-07-14 09:11:28.673000+00:00,NaN,...,NaN,NaN,NaN,NaN,1295063.0,31402314,2,7,NaN,NaN
26,26,31647520,NaN,<pre><code>protected void userLocationMap() {\...,NaN,NaN,4,NaN,2015-07-27 07:43:44.827000+00:00,NaN,...,2015-07-27 13:48:33.740000+00:00,NaN,4682365.0,NaN,4682365.0,31647159,2,8,NaN,NaN
27,27,31639169,NaN,<p>ifaour has the right idea of how to use pag...,NaN,NaN,4,NaN,2015-07-26 16:15:36.247000+00:00,NaN,...,2015-09-06 12:21:20.650000+00:00,NaN,4112664.0,NaN,4105699.0,31398145,2,10,NaN,NaN
28,28,31789658,NaN,<p>I use a keyboard shortcut to past the value...,NaN,NaN,4,NaN,2015-08-03 14:16:56.797000+00:00,NaN,...,2018-05-09 18:35:35.110000+00:00,NaN,836169.0,NaN,3447515.0,31789185,2,11,NaN,NaN
29,29,31293174,NaN,<p>When performing <strong>UI Updates in closu...,NaN,NaN,4,NaN,2015-07-08 12:46:51.883000+00:00,NaN,...,2017-02-13 12:40:23.227000+00:00,NaN,3970292.0,NaN,3970292.0,31287149,2,19,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266904,1266904,39630189,NaN,<p>i dont know for other assemblers but in tas...,NaN,NaN,3,NaN,2016-09-22 04:18:35.087000+00:00,NaN,...,2016-09-23 02:35:03.017000+00:00,NaN,224132.0,NaN,6125442.0,39628953,2,2,NaN,NaN
1266905,1266905,39649520,NaN,<p>If you don't need to keep arr1 in its origi...,NaN,NaN,3,NaN,2016-09-22 21:59:02.273000+00:00,NaN,...,2016-09-22 22:10:36.957000+00:00,NaN,478884.0,NaN,478884.0,39649467,2,2,NaN,NaN
1266906,1266906,39652466,NaN,<p>You can receive the 1-based index position ...,NaN,NaN,3,NaN,2016-09-23 04:08:27.260000+00:00,NaN,...,NaN,NaN,NaN,user4039065,NaN,39652293,2,2,NaN,NaN
1266907,1266907,39084442,NaN,<p>There is one array formula solution provide...,NaN,NaN,3,NaN,2016-08-22 16:26:56.107000+00:00,NaN,...,NaN,NaN,NaN,user4039065,NaN,39083611,2,3,NaN,NaN
1266908,1266908,39163708,NaN,<p>Use <code>svnmucc put SRC-FILE URL</code>.<...,NaN,NaN,3,NaN,2016-08-26 10:06:32.340000+00:00,NaN,...,2016-08-26 10:08:02.890000+00:00,NaN,761095.0,NaN,761095.0,39162715,2,3,NaN,NaN
1266909,1266909,39189046,NaN,<p><code>viewBox</code> has an uppercase B:</p...,NaN,NaN,3,NaN,2016-08-28 07:41:44.993000+00:00,NaN,...,2016-08-28 07:54:37.513000+00:00,NaN,5768908.0,NaN,5768908.0,39188877,2,3,NaN,NaN
1266910,1266910,39242948,NaN,<p>Your idea to use <code>lapply</code> is one...,NaN,NaN,3,NaN,2016-08-31 07:09:36.920000+00:00,NaN,...,2016-08-31 07:15:16.607000+00:00,NaN,1862762.0,NaN,1862762.0,39242727,2,3,NaN,NaN
1266911,1266911,39453905,NaN,<p>you probably have a <code>setlocal</code> i...,NaN,NaN,3,NaN,2016-09-12 15:30:23.077000+00:00,NaN,...,NaN,NaN,NaN,NaN,2152082.0,39453774,2,3,NaN,NaN
1266912,1266912,39495269,NaN,"<p>Full disclosure, I'm a member of the ZingCh...",NaN,NaN,3,NaN,2016-09-14 16:17:51.800000+00:00,NaN,...,NaN,NaN,NaN,NaN,5712661.0,39494847,2,3,NaN,NaN
1266913,1266913,39519093,NaN,<p>As soon as your last <code>write</code> is ...,NaN,NaN,3,NaN,2016-09-15 19:40:03.690000+00:00,NaN,...,NaN,NaN,NaN,NaN,5754797.0,39501950,2,3,NaN,NaN
1266914,1266914,39156893,NaN,<p>The API key may not be passed in the URL. ...,NaN,NaN,3,NaN,2016-08-26 00:59:56.897000+00:00,NaN,...,NaN,NaN,NaN,NaN,5632740.0,39154723,2,4,NaN,NaN
1266915,1266915,39248134,NaN,<p>Probably you should do something a little m...,NaN,NaN,3,NaN,2016-08-31 11:15:29.840000+00:00,NaN,...,2017-05-23 12:32:08.853000+00:00,NaN,-1.0,NaN,5448626.0,39201757,2,4,NaN,NaN
1266916,1266916,39297924,NaN,<p>you can use a blank string (<code>''</code>...,NaN,NaN,3,NaN,2016-09-02 17:31:18.120000+00:00,NaN,...,2016-09-06 12:34:00.327000+00:00,NaN,5090771.0,NaN,5090771.0,39285078,2,4,NaN,NaN
1266917,1266917,39653318,NaN,<p>It is as simple as</p>\r\n\r\n<pre><code>wb...,NaN,NaN,3,NaN,2016-09-23 05:38:21.870000+00:00,NaN,...,NaN,NaN,NaN,NaN,1140579.0,39653129,2,4,NaN,NaN
1266918,1266918,39210996,NaN,<p>A For ... Next loop using the ASCII charact...,NaN,NaN,3,NaN,2016-08-29 16:33:18.980000+00:00,NaN,...,2016-08-29 16:40:16.277000+00:00,user4039065,NaN,user4039065,NaN,39210888,2,5,NaN,NaN
1266919,1266919,39375477,NaN,<p>They're stored internally in the database. ...,NaN,NaN,3,NaN,2016-09-07 16:52:17.623000+00:00,NaN,...,NaN,NaN,NaN,NaN,736079.0,39374159,2,5,NaN,NaN
1266920,1266920,39402126,NaN,<p>It is a circle -- The problem is that the a...,NaN,NaN,3,NaN,2016-09-09 00:36:49.637000+00:00,NaN,...,NaN,NaN,NaN,NaN,748858.0,39402109,2,6,NaN,NaN
1266921,1266921,39371604,NaN,"<p>I usually use a pattern like this, which is...",NaN,NaN,3,NaN,2016-09-07 13:44:28.780000+00:00,NaN,...,2016-09-13 12:14:52.903000+00:00,NaN,169781.0,NaN,169781.0,39365970,2,7,NaN,NaN
1266922,1266922,39406305,NaN,<p>The other answer is correct. You could also...,NaN,NaN,3,NaN,2016-09-09 07:39:55.320000+00:00,NaN,...,2017-03-11 17:46:14.120000+00:00,NaN,54467.0,NaN,54467.0,39391437,2,7,NaN,NaN
1266923,1266923,39551998,NaN,<blockquote>\r\n <p>Is the because it's too s...,NaN,NaN,3,NaN,2016-09-17 21:39:28.033000+00:00,NaN,...,NaN,NaN,NaN,NaN,115145.0,39551774,2,8,NaN,NaN
1266924,1266924,39178633,NaN,<p>I solved this problem in my map fragment by...,NaN,NaN,3,NaN,2016-08-27 07:31:17.907000+00:00,NaN,...,NaN,NaN,NaN,NaN,6751239.0,14489880,2,11,NaN,NaN
1266925,1266925,39531911,NaN,"<p>@DanDan's answer, using C++11 is:</p>\r\n\r...",NaN,NaN,3,NaN,2016-09-16 12:47:48.270000+00:00,NaN,...,NaN,NaN,NaN,NaN,1349673.0,110157,2,11,NaN,NaN
1266926,1266926,39426143,NaN,<p>You need to use the same encoding in your G...,NaN,NaN,3,NaN,2016-09-10 12:35:50.470000+00:00,NaN,...,NaN,NaN,NaN,NaN,142162.0,39426096,2,12,NaN,NaN
1266927,1266927,39256428,NaN,"<p>This is a common <a href=""https://en.wikipe...",NaN,NaN,3,NaN,2016-08-31 18:16:43.543000+00:00,NaN,...,2017-09-22 05:02:12.783000+00:00,NaN,641914.0,NaN,2173016.0,39256309,2,17,NaN,NaN
1266928,1266928,39425829,NaN,<p>The following code worked for me without sy...,NaN,NaN,3,NaN,2016-09-10 11:57:14.217000+00:00,NaN,...,NaN,NaN,NaN,NaN,1264304.0,3339801,2,-3,NaN,NaN
1266929,1266929,39286561,NaN,<p>In:</p>\r\n\r\n<pre><code>//async operation...,NaN,NaN,3,NaN,2016-09-02 07:23:13.950000+00:00,NaN,...,2016-09-06 15:25:21.513000+00:00,NaN,1463733.0,NaN,1463733.0,39286043,2,-1,NaN,NaN
1266930,1266930,39416177,NaN,<p>You have an error in your code. You have n...,NaN,NaN,3,NaN,2016-09-09 16:40:39.990000+00:00,NaN,...,2016-09-09 16:46:01.873000+00:00,NaN,4904165.0,NaN,4904165.0,39415527,2,-1,NaN,NaN
1266931,1266931,39086563,NaN,<p>You do it in exactly the same way as when y...,NaN,NaN,4,NaN,2016-08-22 18:40:35.723000+00:00,NaN,...,NaN,NaN,NaN,NaN,324584.0,39084970,2,0,NaN,NaN
1266932,1266932,39125305,NaN,<p>First I made a very simple userform with 5 ...,NaN,NaN,4,NaN,2016-08-24 13:55:18.397000+00:00,NaN,...,NaN,NaN,NaN,NaN,6704227.0,38845555,2,0,NaN,NaN
1266933,1266933,39126927,NaN,<p>I modified your SQL statement. Replace the...,NaN,NaN,4,NaN,2016-08-24 15:02:50.527000+00:00,NaN,...,NaN,NaN,NaN,NaN,6202343.0,39126025,2,0,NaN,NaN

In [35]:
# retrieving the comments that belong to the questions retrieved above

sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.comments` WHERE post_id IN 
    (SELECT id FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%d3%' 
    OR tags LIKE '%tableau%'
    OR tags LIKE '%ggplot%'
    OR tags LIKE '%plotly%'
    OR tags LIKE '%matplotlib%'
    OR tags LIKE '%excel%'
    OR tags LIKE '%sheets%'
    OR tags LIKE '%seaborn%'
    OR tags LIKE '%altair%'
    OR tags LIKE '%powerbi%'
    OR tags LIKE '%qlik%'
    OR tags LIKE '%chart%'
    OR tags LIKE '%graph%'
    OR tags LIKE '%sas%'
    OR tags LIKE '%spss%'
    OR tags LIKE '%plot%'
    OR tags LIKE '%stata%'
    OR tags LIKE '%line%'
    OR tags LIKE '%visual%'
    OR tags LIKE '%viz%'
    OR tags LIKE '%linechart%'
    OR tags LIKE '%diagram%'
    OR tags LIKE '%map%')
    AND
    tags NOT LIKE '%visual-studio%'
    AND
    tags NOT LIKE '%visual-c++%')
"""
dfCommentsFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [36]:
np.shape(dfCommentsFiltered)

(1781412, 7)

In [37]:
dfCommentsFiltered

,id,text,creation_date,post_id,user_id,user_display_name,score
0,13959910,Don't worry about extra objects unless there i...,2012-05-24 19:03:24.103000+00:00,10743622,NaN,user166390,6
1,14116297,"If you're going to use NodeJS, you might as we...",2012-05-31 20:28:18.247000+00:00,10840689,NaN,user1106925,5
2,14834466,"WTF, you want to write your own virtual filesy...",2012-07-01 04:15:00.443000+00:00,11279477,NaN,user405725,6
3,13253544,"Sorry about the semicolons, I did put them in ...",2012-04-24 13:46:43.277000+00:00,10298983,NaN,user818700,0
4,13254271,"@Pointy - I'm so sorry, it's obviously too lat...",2012-04-24 14:11:36.220000+00:00,10298983,NaN,user818700,0
5,13255022,Ahhhh.. Now I see. Thank you very much. I real...,2012-04-24 14:37:07.523000+00:00,10298983,NaN,user818700,0
6,13256213,Here's a complete example: http://codepad.org/...,2012-04-24 15:18:30.447000+00:00,10290177,NaN,user393964,0
7,13279186,"I'm certainly surprised by this, and it does't...",2012-04-25 12:52:39.417000+00:00,10315746,NaN,user24359,0
8,13279391,"Er, I mean `Payments`",2012-04-25 12:59:19.757000+00:00,10315746,NaN,user24359,0
9,13283132,@dasblinkenlight great thanks. I guess this is...,2012-04-25 15:09:25.203000+00:00,10318302,NaN,user517491,0
10,13294136,getLatLong evaluates to undefined there. What'...,2012-04-25 23:20:36.513000+00:00,10325141,NaN,user166390,0
11,13299256,"Thinking about it a bit more, approximation wo...",2012-04-26 06:42:10.947000+00:00,10328302,NaN,user1254163,0
12,13299587,"Thanks, could you clarify just a bit more?",2012-04-26 07:01:08.473000+00:00,10328302,NaN,user1254163,0
13,13349030,"@RobTaylor, thanks, that was the answer!",2012-04-28 01:15:46.203000+00:00,10356249,NaN,user349026,0
14,13353005,"I fix this, no result",2012-04-28 10:09:40.510000+00:00,10362497,NaN,user1085536,0
15,13356459,When you need to crunch lots of data. Ask a v...,2012-04-28 15:17:45.123000+00:00,10364690,NaN,user554546,0
16,13360761,"Did you try substracting two? If it works, it ...",2012-04-28 20:40:26.977000+00:00,10367336,NaN,user529758,0
17,13392990,If you need pseudo-code in java. Please check ...,2012-04-30 16:41:35.510000+00:00,2445380,NaN,user1245222,0
18,13397179,i need that plotLine on the xAxis to affect ju...,2012-04-30 20:15:18.847000+00:00,10389794,NaN,user1170618,0
19,13399991,"As far as I remember it worked fine, it was ju...",2012-04-30 22:53:54.873000+00:00,5292700,NaN,user206705,0
20,13412484,"PeterP, I think the root cause of most of your...",2012-05-01 14:47:12.087000+00:00,10382727,NaN,user694833,0
21,13415888,You mean the part they could travel together?,2012-05-01 17:08:42.250000+00:00,10401339,NaN,user180326,0
22,13436789,How is mapView declared and created? Show how...,2012-05-02 13:27:31.307000+00:00,10410431,NaN,user467105,0
23,13446583,Please check what tags relate to before you us...,2012-05-02 19:59:18.940000+00:00,10420327,NaN,user577537,0
24,13446620,"In fact, is this a programming question, or do...",2012-05-02 20:00:26.583000+00:00,10420327,NaN,user577537,0
25,13454793,"Hi, I wish to store just the data. and later ...",2012-05-03 06:14:14.093000+00:00,10425984,NaN,user1357933,0
26,13455047,That means the client must have the Excel inst...,2012-05-03 06:29:25.630000+00:00,10425984,NaN,user1357933,0
27,13455153,"Yep, I thought he should have a Excel installe...",2012-05-03 06:36:15.940000+00:00,10425984,NaN,user1357933,0
28,13455434,"If it's CLI, treat it like ... CLI. Just launc...",2012-05-03 06:52:54.417000+00:00,10426332,NaN,user166390,0
29,13457347,"Stack Overflow is for programming questions, i...",2012-05-03 08:32:37.013000+00:00,10420327,NaN,user577537,0
...,...,...,...,...,...,...,...
1781382,92195296,Max of what? You're getting a single row number.,2018-10-03 15:48:05.933000+00:00,52630943,NaN,user4039065,2
1781383,92222177,If you're struggling then you've written somet...,2018-10-04 11:01:47.900000+00:00,52645043,NaN,user4039065,2
1781384,92244715,Type `=textjoin()` into a cell. Do you get a `...,2018-10-05 00:49:12.140000+00:00,52656870,NaN,user4039065,2
1781385,92280566,Have you accepted the vb overhead and tried `p...,2018-10-06 04:07:02.387000+00:00,52675562,NaN,user4039065,2
1781386,92345084,Homework questions are welcome here so long as...,2018-10-08 20:13:28.433000+00:00,52709423,NaN,user4039065,2
1781387,92372894,countif not good enough?,2018-10-09 14:46:33.007000+00:00,52723771,NaN,user4039065,2
1781388,92680303,possible duplicate of [TEXTJOIN for xl2010/xl2...,2018-10-18 22:31:40.197000+00:00,52883256,NaN,user4039065,2
1781389,92695899,you can do this with the HYPERLINK function.,2018-10-19 11:42:28.943000+00:00,52891640,NaN,user4039065,2
1781390,92700913,... and [Is the . in .Range necessary when def...,2018-10-19 14:11:51.083000+00:00,52893738,NaN,user4039065,2
1781391,92703506,Lots of hits for this message on the internet....,2018-10-19 15:26:13.893000+00:00,52895386,NaN,user1531971,2
1781392,92789638,How is this not the simplest COUNTIF question?,2018-10-23 02:45:42.043000+00:00,52940245,NaN,user4039065,2
1781393,92796187,Doesn't `=sumproduct(--((COUNTIF*COUNTIF)>0))`...,2018-10-23 08:06:00.657000+00:00,52944014,NaN,user4039065,2
1781394,92800753,"Use a series with a step, not an autofill.",2018-10-23 10:05:37.653000+00:00,52946233,NaN,user4039065,2
1781395,92866495,Ping me if you [edit] your question to show yo...,2018-10-25 01:31:09.460000+00:00,52979742,NaN,user4039065,2
1781396,92923984,Seen this?\nhttps://stackoverflow.com/question...,2018-10-26 13:53:32.163000+00:00,53007623,NaN,user2261597,2
1781397,92939774,If that was a POSIX datetime the result would ...,2018-10-27 03:18:43.720000+00:00,53018396,NaN,user4039065,2
1781398,92940232,Get rid of `On Error Resume Next` and try it a...,2018-10-27 04:33:35.060000+00:00,53018619,NaN,user4039065,2
1781399,92945684,DateValue takes a string and returns a true date.,2018-10-27 12:03:13.977000+00:00,53021679,NaN,user4039065,2
1781400,91178470,The behavior you're trying to achieve is handl...,2018-08-31 11:02:26.433000+00:00,52114044,NaN,user4039065,3
1781401,91682982,It looks like you're copying the whole row for...,2018-09-17 13:51:24.587000+00:00,52369143,NaN,user4039065,3
1781402,91760754,My guess is that fx reads the string masquerad...,2018-09-19 14:45:55.423000+00:00,52408304,NaN,user4039065,3
1781403,91787056,You would likely be interested in [this](https...,2018-09-20 09:39:06.633000+00:00,52421920,NaN,user4039065,3
1781404,92190527,"The $ variety (e.g. Left$, Mid$, etc) are meas...",2018-10-03 13:47:13.183000+00:00,52628282,NaN,user4039065,3
1781405,92322228,What's wrong with sumif/sumifs?,2018-10-08 08:07:51.933000+00:00,52697828,NaN,user4039065,3
1781406,92367004,Does that actually work? Those text-that-look-...,2018-10-09 12:22:47.200000+00:00,52720731,NaN,user4039065,3
1781407,92596122,*Is my code running badly because I use DoEven...,2018-10-16 16:32:17.607000+00:00,52839776,NaN,user2261597,3
1781408,92685037,"What is `Range(Range(""G2:G14614""), Range(""G"" &...",2018-10-19 04:50:57.337000+00:00,52886028,NaN,user4039065,3
1781409,92702053,Looks like twenty-five minutes and forty-seven...,2018-10-19 14:44:27.907000+00:00,52894675,NaN,user4039065,3
1781410,92888112,If you are talking about fields/properties/met...,2018-10-25 14:14:20.467000+00:00,52991408,NaN,user2819245,3
1781411,92943075,This would be a good time to learn that you sh...,2018-10-27 09:11:38.137000+00:00,53019966,NaN,user4039065,3

In [39]:
# write the dataframe to a tsv
dfCommentsFiltered.to_csv("data/stackoverflow/CommentsFiltered.tsv", sep='\t')

In [40]:
del dfCommentsFiltered

In [41]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST COMMENTS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfCommentsFiltered = pd.read_csv("data/stackoverflow/CommentsFiltered.tsv", sep='\t')

In [42]:
dfCommentsFiltered

,Unnamed: 0,id,text,creation_date,post_id,user_id,user_display_name,score
0,0,13959910,Don't worry about extra objects unless there i...,2012-05-24 19:03:24.103000+00:00,10743622,NaN,user166390,6
1,1,14116297,"If you're going to use NodeJS, you might as we...",2012-05-31 20:28:18.247000+00:00,10840689,NaN,user1106925,5
2,2,14834466,"WTF, you want to write your own virtual filesy...",2012-07-01 04:15:00.443000+00:00,11279477,NaN,user405725,6
3,3,13253544,"Sorry about the semicolons, I did put them in ...",2012-04-24 13:46:43.277000+00:00,10298983,NaN,user818700,0
4,4,13254271,"@Pointy - I'm so sorry, it's obviously too lat...",2012-04-24 14:11:36.220000+00:00,10298983,NaN,user818700,0
5,5,13255022,Ahhhh.. Now I see. Thank you very much. I real...,2012-04-24 14:37:07.523000+00:00,10298983,NaN,user818700,0
6,6,13256213,Here's a complete example: http://codepad.org/...,2012-04-24 15:18:30.447000+00:00,10290177,NaN,user393964,0
7,7,13279186,"I'm certainly surprised by this, and it does't...",2012-04-25 12:52:39.417000+00:00,10315746,NaN,user24359,0
8,8,13279391,"Er, I mean `Payments`",2012-04-25 12:59:19.757000+00:00,10315746,NaN,user24359,0
9,9,13283132,@dasblinkenlight great thanks. I guess this is...,2012-04-25 15:09:25.203000+00:00,10318302,NaN,user517491,0
10,10,13294136,getLatLong evaluates to undefined there. What'...,2012-04-25 23:20:36.513000+00:00,10325141,NaN,user166390,0
11,11,13299256,"Thinking about it a bit more, approximation wo...",2012-04-26 06:42:10.947000+00:00,10328302,NaN,user1254163,0
12,12,13299587,"Thanks, could you clarify just a bit more?",2012-04-26 07:01:08.473000+00:00,10328302,NaN,user1254163,0
13,13,13349030,"@RobTaylor, thanks, that was the answer!",2012-04-28 01:15:46.203000+00:00,10356249,NaN,user349026,0
14,14,13353005,"I fix this, no result",2012-04-28 10:09:40.510000+00:00,10362497,NaN,user1085536,0
15,15,13356459,When you need to crunch lots of data. Ask a v...,2012-04-28 15:17:45.123000+00:00,10364690,NaN,user554546,0
16,16,13360761,"Did you try substracting two? If it works, it ...",2012-04-28 20:40:26.977000+00:00,10367336,NaN,user529758,0
17,17,13392990,If you need pseudo-code in java. Please check ...,2012-04-30 16:41:35.510000+00:00,2445380,NaN,user1245222,0
18,18,13397179,i need that plotLine on the xAxis to affect ju...,2012-04-30 20:15:18.847000+00:00,10389794,NaN,user1170618,0
19,19,13399991,"As far as I remember it worked fine, it was ju...",2012-04-30 22:53:54.873000+00:00,5292700,NaN,user206705,0
20,20,13412484,"PeterP, I think the root cause of most of your...",2012-05-01 14:47:12.087000+00:00,10382727,NaN,user694833,0
21,21,13415888,You mean the part they could travel together?,2012-05-01 17:08:42.250000+00:00,10401339,NaN,user180326,0
22,22,13436789,How is mapView declared and created? Show how...,2012-05-02 13:27:31.307000+00:00,10410431,NaN,user467105,0
23,23,13446583,Please check what tags relate to before you us...,2012-05-02 19:59:18.940000+00:00,10420327,NaN,user577537,0
24,24,13446620,"In fact, is this a programming question, or do...",2012-05-02 20:00:26.583000+00:00,10420327,NaN,user577537,0
25,25,13454793,"Hi, I wish to store just the data. and later ...",2012-05-03 06:14:14.093000+00:00,10425984,NaN,user1357933,0
26,26,13455047,That means the client must have the Excel inst...,2012-05-03 06:29:25.630000+00:00,10425984,NaN,user1357933,0
27,27,13455153,"Yep, I thought he should have a Excel installe...",2012-05-03 06:36:15.940000+00:00,10425984,NaN,user1357933,0
28,28,13455434,"If it's CLI, treat it like ... CLI. Just launc...",2012-05-03 06:52:54.417000+00:00,10426332,NaN,user166390,0
29,29,13457347,"Stack Overflow is for programming questions, i...",2012-05-03 08:32:37.013000+00:00,10420327,NaN,user577537,0
...,...,...,...,...,...,...,...,...
1781382,1781382,92195296,Max of what? You're getting a single row number.,2018-10-03 15:48:05.933000+00:00,52630943,NaN,user4039065,2
1781383,1781383,92222177,If you're struggling then you've written somet...,2018-10-04 11:01:47.900000+00:00,52645043,NaN,user4039065,2
1781384,1781384,92244715,Type `=textjoin()` into a cell. Do you get a `...,2018-10-05 00:49:12.140000+00:00,52656870,NaN,user4039065,2
1781385,1781385,92280566,Have you accepted the vb overhead and tried `p...,2018-10-06 04:07:02.387000+00:00,52675562,NaN,user4039065,2
1781386,1781386,92345084,Homework questions are welcome here so long as...,2018-10-08 20:13:28.433000+00:00,52709423,NaN,user4039065,2
1781387,1781387,92372894,countif not good enough?,2018-10-09 14:46:33.007000+00:00,52723771,NaN,user4039065,2
1781388,1781388,92680303,possible duplicate of [TEXTJOIN for xl2010/xl2...,2018-10-18 22:31:40.197000+00:00,52883256,NaN,user4039065,2
1781389,1781389,92695899,you can do this with the HYPERLINK function.,2018-10-19 11:42:28.943000+00:00,52891640,NaN,user4039065,2
1781390,1781390,92700913,... and [Is the . in .Range necessary when def...,2018-10-19 14:11:51.083000+00:00,52893738,NaN,user4039065,2
1781391,1781391,92703506,Lots of hits for this message on the internet....,2018-10-19 15:26:13.893000+00:00,52895386,NaN,user1531971,2
1781392,1781392,92789638,How is this not the simplest COUNTIF question?,2018-10-23 02:45:42.043000+00:00,52940245,NaN,user4039065,2
1781393,1781393,92796187,Doesn't `=sumproduct(--((COUNTIF*COUNTIF)>0))`...,2018-10-23 08:06:00.657000+00:00,52944014,NaN,user4039065,2
1781394,1781394,92800753,"Use a series with a step, not an autofill.",2018-10-23 10:05:37.653000+00:00,52946233,NaN,user4039065,2
1781395,1781395,92866495,Ping me if you [edit] your question to show yo...,2018-10-25 01:31:09.460000+00:00,52979742,NaN,user4039065,2
1781396,1781396,92923984,Seen this?\r\nhttps://stackoverflow.com/questi...,2018-10-26 13:53:32.163000+00:00,53007623,NaN,user2261597,2
1781397,1781397,92939774,If that was a POSIX datetime the result would ...,2018-10-27 03:18:43.720000+00:00,53018396,NaN,user4039065,2
1781398,1781398,92940232,Get rid of `On Error Resume Next` and try it a...,2018-10-27 04:33:35.060000+00:00,53018619,NaN,user4039065,2
1781399,1781399,92945684,DateValue takes a string and returns a true date.,2018-10-27 12:03:13.977000+00:00,53021679,NaN,user4039065,2
1781400,1781400,91178470,The behavior you're trying to achieve is handl...,2018-08-31 11:02:26.433000+00:00,52114044,NaN,user4039065,3
1781401,1781401,91682982,It looks like you're copying the whole row for...,2018-09-17 13:51:24.587000+00:00,52369143,NaN,user4039065,3
1781402,1781402,91760754,My guess is that fx reads the string masquerad...,2018-09-19 14:45:55.423000+00:00,52408304,NaN,user4039065,3
1781403,1781403,91787056,You would likely be interested in [this](https...,2018-09-20 09:39:06.633000+00:00,52421920,NaN,user4039065,3
1781404,1781404,92190527,"The $ variety (e.g. Left$, Mid$, etc) are meas...",2018-10-03 13:47:13.183000+00:00,52628282,NaN,user4039065,3
1781405,1781405,92322228,What's wrong with sumif/sumifs?,2018-10-08 08:07:51.933000+00:00,52697828,NaN,user4039065,3
1781406,1781406,92367004,Does that actually work? Those text-that-look-...,2018-10-09 12:22:47.200000+00:00,52720731,NaN,user4039065,3
1781407,1781407,92596122,*Is my code running badly because I use DoEven...,2018-10-16 16:32:17.607000+00:00,52839776,NaN,user2261597,3
1781408,1781408,92685037,"What is `Range(Range(""G2:G14614""), Range(""G"" &...",2018-10-19 04:50:57.337000+00:00,52886028,NaN,user4039065,3
1781409,1781409,92702053,Looks like twenty-five minutes and forty-seven...,2018-10-19 14:44:27.907000+00:00,52894675,NaN,user4039065,3
1781410,1781410,92888112,If you are talking about fields/properties/met...,2018-10-25 14:14:20.467000+00:00,52991408,NaN,user2819245,3
1781411,1781411,92943075,This would be a good time to learn that you sh...,2018-10-27 09:11:38.137000+00:00,53019966,NaN,user4039065,3