In [1]:
import pandas_gbq
import pickle
import pandas as pd
import numpy as np
import re
import time
import os
import math
import random
import warnings

from bs4 import BeautifulSoup

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import nltk
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import gensim
from nltk.tokenize import word_tokenize
import dateutil.parser

%matplotlib inline

# TODO: Set project_id to your Google Cloud Platform project ID.
# project_id = "xxxxxx-yyyyyy-######"
project_id = "diesel-client-247517"

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jeffb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

### Pipeline for Stack Overflow Question and Answers Posts Starts Here

In [2]:
# use this to get the table definition of individual tables in Big Query's tables

# substitute the table name you want the schema for in the "table_name = " line below


sql = """

SELECT column_name, data_type
FROM `bigquery-public-data`.stackoverflow.INFORMATION_SCHEMA.COLUMNS  
WHERE table_name = 'posts_questions' 

"""
df=pandas_gbq.read_gbq(sql, project_id=project_id)

In [3]:
df

                 column_name  data_type
0                         id      INT64
1                      title     STRING
2                       body     STRING
3         accepted_answer_id      INT64
4               answer_count      INT64
5              comment_count      INT64
6       community_owned_date  TIMESTAMP
7              creation_date  TIMESTAMP
8             favorite_count      INT64
9         last_activity_date  TIMESTAMP
10            last_edit_date  TIMESTAMP
11  last_editor_display_name     STRING
12       last_editor_user_id      INT64
13        owner_display_name     STRING
14             owner_user_id      INT64
15                 parent_id     STRING
16              post_type_id      INT64
17                     score      INT64
18                      tags     STRING
19                view_count      INT64

In [15]:
# how many total question and answer records are in Stack Overflow?
sql = """
SELECT COUNT(*) FROM `bigquery-public-data.stackoverflow.posts_questions` 
"""

numquestions = pandas_gbq.read_gbq(sql, project_id=project_id)
print("total number of questions in Stack Overflow:", numquestions)

sql = """
SELECT COUNT(*) FROM `bigquery-public-data.stackoverflow.posts_answers`
"""

numanswers = pandas_gbq.read_gbq(sql, project_id=project_id)
print("total number of answers in Stack Overflow:", numanswers)

total number of questions in Stack Overflow:         f0_
0  18154493
total number of answers in Stack Overflow:         f0_
0  27665009

In [4]:
# Here is the code to extract the records from one table and load it into a pandas data frame

# note that this can run a long time, depending on the number of records you are trying to load


sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%plot%' 
OR tags LIKE '%graph%'
OR tags LIKE '%chart%'
OR tags LIKE '%visualiz%'
OR tags LIKE '%choropleth%'
OR tags LIKE '%drawing%'
OR tags LIKE '%line%'
OR tags LIKE '%geospatial%'
OR tags LIKE '%diagram%')
"""



dfPostQuestionsFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [7]:
# write the raw questions dataframe to a tsv
dfPostQuestionsFiltered.to_csv("data/stackoverflow/PostQuestionsFiltered_raw_12_06_19.tsv", sep='\t', index=False)

In [8]:
# in case you want to delete the dfPostQuestionsFiltered dataframe

# ** NOTE** For the rest of the process to work correctly, you must save the raw file after executing the Big Query SQL select above
# (use the cell immediately above to save it), then run this cell to delete the dataframe,
# then re-load it using he cell below with the "keep_default_na" paramter in order to remove the NaN -type values in the dataset

del dfPostQuestionsFiltered

In [10]:
# Use this code to re-load raw Stack Overflow questions to the Pandas df -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to

dfPostQuestionsFiltered = pd.read_csv("data/stackoverflow/PostQuestionsFiltered_raw_12_06_19.tsv", sep='\t', keep_default_na=False)

In [11]:
np.shape(dfPostQuestionsFiltered)

(429665, 20)

In [12]:
dfPostQuestionsFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,56195999,Apollo client doesn't display an error message,<p>I have configured and set up a fully functi...,56196332.0,1,0,,2019-05-18 04:35:44.290000+00:00,,2019-05-18 05:45:46.330000+00:00,2019-05-18 05:17:59.233000+00:00,,7916354.0,,7916354.0,,1,2,reactjserror-handlinggraphqlapollographql-js,256
1,55971037,Azure Pipeline Gradle build fails for Spring,<p>Im trying to build and deploy a Spring API ...,56004367.0,1,0,,2019-05-03 13:40:43.907000+00:00,,2019-05-06 11:31:53.900000+00:00,,,,,5800859.0,,1,1,javaspringazurespring-bootazure-pipelines,258
2,56028672,Why do I get NA values after filtering a datas...,<p>I am using the gpa1 dataset in R and am try...,,1,0,,2019-05-07 18:38:55.503000+00:00,,2019-05-07 19:19:27.447000+00:00,,,,,11452536.0,,1,0,filteringlinear-regressionresultset,5
3,56224298,Matplotlib could not track button release event,<p>I try to create a dragable line object. The...,,0,0,,2019-05-20 15:46:52.757000+00:00,,2019-05-20 15:53:14.423000+00:00,2019-05-20 15:53:14.423000+00:00,,4089747.0,,4089747.0,,1,0,matplotlib,5
4,56252247,counter of a Dataframe column as a size for sc...,<p>I have used 'Counter' to count the instance...,,0,0,,2019-05-22 08:17:40.557000+00:00,,2019-05-22 08:17:40.557000+00:00,,,,,11232091.0,,1,0,counterscatter-plot,5
5,56281142,Some resources don't enter timesheets in Proje...,<p>I have been asked to enable timesheets in P...,,0,0,,2019-05-23 18:36:05.040000+00:00,,2019-05-23 18:36:05.040000+00:00,,,,,11501306.0,,1,0,projectproject-online,5
6,56212612,Calling a hook (useMutation) inside an event h...,<p>I want to use a mutation in an event handle...,56212940.0,1,0,,2019-05-19 22:47:04.330000+00:00,,2019-05-19 23:57:38.440000+00:00,,,,,10688712.0,,1,0,reactjsgraphqlreact-hooksmutation,261
7,56233232,Graph with O365 Calendar is legacy? What is th...,<p>I want to use an O365 API for synchronisati...,,0,0,,2019-05-21 07:27:44.607000+00:00,,2019-05-21 07:27:44.607000+00:00,,,,,11532180.0,,1,0,graphcalendaroffice365,6
8,56287479,Has somebody working example of TNumericGauge ...,<p>I would like to use TNumericGauge in TDBCha...,,0,0,,2019-05-24 07:08:13.093000+00:00,,2019-05-24 07:08:13.093000+00:00,,,,,11548698.0,,1,0,teechart,6
9,56288322,Process finished with exit code 0 but expectin...,<p>I tried to compute historical value at risk...,,0,0,,2019-05-24 08:05:15.990000+00:00,,2019-05-24 08:05:15.990000+00:00,,,,,11548961.0,,1,0,python-ggplotrisk-analysis,6
10,56204854,How do I chain useQuery and useMutation in Gra...,<p>I have useQuery and useMutation from react-...,56206915.0,2,0,,2019-05-19 04:52:19.730000+00:00,,2019-07-15 12:45:21.457000+00:00,,,,,10116367.0,,1,0,javascriptreactjsgraphqlreact-apolloreact-hooks,262
11,56045499,SharePoint Online looses connection?,<p>I have a JSOM code running on page which ty...,,0,0,,2019-05-08 16:48:23.207000+00:00,,2019-05-08 16:48:23.207000+00:00,,,,,980019.0,,1,0,sharepointconnectiontimeoutsharepoint-onlinere...,7
12,56074434,Filter mails with Auto-Submitted = auto-genera...,<p>I want to filter auto-generated emails in a...,,0,0,,2019-05-10 09:17:02.993000+00:00,,2019-05-14 19:50:26.483000+00:00,2019-05-14 19:50:26.483000+00:00,,105518.0,,11480240.0,,1,0,microsoft-graphmicrosoft-graph-mail,7
13,56158629,After several branches made and ultimately reb...,"<p>After many merges, git checkout -b's and ul...",,0,0,,2019-05-15 22:50:36.273000+00:00,,2019-05-15 22:50:36.273000+00:00,,,,,11055557.0,,1,0,githubcommand-line-interfacerebasebranching-an...,7
14,56170086,How to resolve a list placeholder when providi...,<p>I have something like the following <code>y...,,0,0,,2019-05-16 13:46:14.720000+00:00,,2019-05-16 13:46:14.720000+00:00,,,,,991710.0,,1,0,springcommand-linespring-cloud-config,7
15,56224884,See if exists a connected subgraph that contai...,<p>I need to see if a connected undirected gra...,,0,0,,2019-05-20 16:30:13.607000+00:00,,2019-05-20 16:30:13.607000+00:00,,,,,5644338.0,,1,0,graphundirected-graph,7
16,56251794,Communication between web app and offline appl...,<p>Current situation: </p>\r\n\r\n<ul>\r\n<li>...,,0,0,,2019-05-22 07:48:17.537000+00:00,,2019-05-22 07:48:17.537000+00:00,,,,,1016498.0,,1,0,webcommunicationoffline,7
17,56258049,Using Inquire to get user input but unable to ...,<p>I am trying to get some user input via inqu...,,0,0,,2019-05-22 13:30:18.737000+00:00,,2019-05-22 13:30:18.737000+00:00,,,,,10129053.0,,1,0,node.jscommand-line-interfaceinquirer,7
18,56307203,node.js console window stays hanging when fetc...,<p>I have been following tutorials online on b...,,0,0,,2019-05-25 17:34:10.660000+00:00,,2019-05-25 17:34:10.660000+00:00,,,,,6842897.0,,1,0,node.jscommand-linegoogle-cloud-firestore,7
19,55977501,Trying to represent weighted undirected graph ...,<p>I am looking for a good way to represent 10...,,0,0,,2019-05-03 21:52:14.757000+00:00,,2019-05-03 21:52:14.757000+00:00,,,,,10772836.0,,1,0,graph,8
20,56039472,What is the usage of frequent closed subgraph ...,<p>What is the usage of frequent closed subgra...,,0,0,,2019-05-08 11:14:45.743000+00:00,,2019-05-08 11:14:45.743000+00:00,,,,,5554059.0,,1,0,miningsubgraph,8
21,56056021,Combo Boxes and SharePoint Online,<p>I am trying to develop a file naming tool u...,,0,0,,2019-05-09 09:12:11.557000+00:00,,2019-05-09 09:12:11.557000+00:00,,,,,2564908.0,,1,0,htmlsharepoint-online,8
22,56083026,How to plot several images in one page inside ...,<p>I'm generating 50 different kmean clusters ...,,0,0,,2019-05-10 18:25:13.317000+00:00,,2019-05-10 18:25:13.317000+00:00,,,,,11482678.0,,1,0,loopsplotjpeg,8
23,56136191,Facebook product set not available while creat...,<p>While trying to create a Dynamic ad through...,,0,0,,2019-05-14 18:08:08.983000+00:00,,2019-05-14 18:08:08.983000+00:00,,,,,4378824.0,,1,0,facebook-graph-api,8
24,56155291,Try parsing data types in PipelineDB and strea...,<p>We were using Pipeline DB to receive data i...,,1,0,,2019-05-15 18:08:09.437000+00:00,,2019-05-16 13:59:01.973000+00:00,,,,,3250242.0,,1,0,postgresqlpipelinedb,8
25,56160831,Check Libraries in Wine without GUI,"<p>I have an AWS Server, using EC2 Linux, curr...",,0,0,,2019-05-16 04:26:04.413000+00:00,,2019-05-16 04:26:04.413000+00:00,,,,,4329084.0,,1,0,command-linewine,8
26,56249395,How to Ignore child items when the parent item...,<p>I have a table of items following an outlin...,,0,0,,2019-05-22 04:36:20.187000+00:00,,2019-05-22 04:57:01.747000+00:00,2019-05-22 04:57:01.747000+00:00,,11474744.0,,11537102.0,,1,0,parent-childparentoutline,8
27,56263392,Changing a user via gnome-session,<p>I am trying to emulate the following via co...,,0,0,,2019-05-22 19:04:58.800000+00:00,,2019-05-22 19:04:58.800000+00:00,,,,,10307467.0,,1,0,command-linegnome-terminalcinnameg,8
28,56273810,How to force plotly plots to correct starting ...,<p>I'm plotting the sales numbers (<code>amoun...,,1,0,,2019-05-23 11:01:39.523000+00:00,,2019-05-23 11:05:50.307000+00:00,,,,,8297514.0,,1,0,python-3.xplotly,8
29,56279337,How to get Account’s list of Rules (AdRule) by...,<p>I’ve created manually Rules in My Ad Accoun...,,0,0,,2019-05-23 16:18:39.247000+00:00,,2019-05-23 16:18:39.247000+00:00,,,,,11546043.0,,1,0,python-3.xfacebook-graph-apifacebook-python-bu...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429635,2967176,Where is svn.exe in my machine?,<p>I have <strong>Tortoise svn</strong> instal...,2967196.0,13,0,,2010-06-03 15:03:44.580000+00:00,14.0,2019-08-19 11:47:19.567000+00:00,2011-05-06 12:14:40.977000+00:00,,248827.0,,248827.0,,1,130,svncommand-linetortoisesvn,124165
429636,3206622,Is putting data in cookies secure?,<p>I am using asp.net mvc 2.0 and I am wonderi...,3206715.0,14,1,,2010-07-08 18:07:13.610000+00:00,3.0,2016-05-03 11:08:08.187000+00:00,2016-05-03 11:08:08.187000+00:00,,31532.0,,130015.0,,1,14,c#.netsecurityencryptioncryptography,5013
429637,2807070,Screenshot of the Nexus One from adb?,<p>My goal is to be able to type a one word co...,11798991.0,14,0,,2010-05-10 23:16:20.110000+00:00,34.0,2015-04-23 15:14:36.843000+00:00,2012-07-09 12:15:22.577000+00:00,,750613.0,,9574.0,,1,46,androidgraphicsffmpegscreenshot,33532
429638,3181080,How to detect online/offline event cross-browser?,<p>I'm trying to accurately detect when the br...,4813406.0,14,4,,2010-07-05 16:53:08.143000+00:00,29.0,2019-03-10 09:35:38.933000+00:00,2017-10-03 13:18:48.667000+00:00,,8338128.0,,345847.0,,1,104,javascriptjqueryjavascript-eventsofflinenetwor...,107731
429639,3058866,How to force a line break in a loooooong word ...,"<p>Okay, this is really confusing me. I have s...",3059128.0,14,1,,2010-06-17 04:26:59.070000+00:00,54.0,2019-02-26 08:52:27.423000+00:00,2012-07-05 21:43:49.883000+00:00,,785326.0,,193619.0,,1,387,htmlcssline-breaks,361620
429640,2658772,Vertical line using XML drawable,<p>I'm trying to figure out how to define a ve...,2659038.0,14,0,,2010-04-17 14:57:01.760000+00:00,51.0,2019-06-17 04:05:12.610000+00:00,2013-12-30 13:51:24.660000+00:00,,56285.0,,55583.0,,1,143,androidandroid-layoutlineandroid-xmlandroid-dr...,215588
429641,3099219,ggplot with 2 y axes on each side and differen...,<p>I need to plot a bar chart showing counts a...,3117319.0,14,3,,2010-06-23 05:52:19.900000+00:00,82.0,2019-05-27 19:58:38.600000+00:00,2019-05-27 19:58:38.600000+00:00,,6461462.0,,373908.0,,1,202,rggplot2r-faq,233516
429642,2674703,"PHP: trying to create a new line with ""\n""",<p>i'm writing this:</p>\r\n\r\n<pre><code>ech...,2674718.0,15,2,,2010-04-20 11:41:06.153000+00:00,7.0,2018-11-15 09:02:22.737000+00:00,2010-04-20 11:42:39.817000+00:00,,12855.0,,248959.0,,1,26,phpnewline,146288
429643,2850203,Count the number of lines in a Java String,<p>Need some compact code for counting the num...,2850259.0,15,2,,2010-05-17 15:08:47.200000+00:00,6.0,2019-01-03 12:18:22.020000+00:00,2018-07-15 07:33:02.457000+00:00,,1746118.0,,321397.0,,1,45,javastringlines,70043
429644,3209362,How to plot empirical cdf in matplotlib in Pyt...,<p>How can I plot the empirical CDF of an arra...,3213923.0,15,0,,2010-07-09 02:14:18.633000+00:00,35.0,2019-03-04 10:37:48.900000+00:00,2012-06-05 07:56:59.890000+00:00,,1301710.0,user248237,,,1,55,pythonnumpystatisticsmatplotlibscipy,64507
429645,2920416,./configure : /bin/sh^M : bad interpreter,<p>I've been trying to install lpng142 on my f...,5514351.0,15,6,,2010-05-27 10:49:52.700000+00:00,134.0,2018-03-30 20:18:28.337000+00:00,2010-11-25 21:16:48.020000+00:00,,327563.0,,348862.0,,1,373,linuxbashshellnewline,474552
429646,2706910,Enable the display of line numbers in Visual S...,<p>Why doesn't Visual Studio have any way of s...,,15,3,,2010-04-25 02:24:55.783000+00:00,13.0,2018-07-03 10:31:45.720000+00:00,2016-04-05 13:46:50.160000+00:00,,1497596.0,,113419.0,,1,147,visual-studio-2010visual-studioline-numbers,134090
429647,2507766,Merge / convert multiple PDF files into one PDF,<p>How could I merge / convert multiple PDF fi...,2507825.0,15,2,,2010-03-24 12:56:47.203000+00:00,317.0,2018-12-13 03:36:43.340000+00:00,2017-05-23 11:55:01.607000+00:00,,-1.0,,248104.0,,1,949,linuxpdfmergecommand-line-interface,636803
429648,2564258,Plot two graphs in same plot in R,<p>I would like to plot y1 and y2 in the same ...,2564276.0,16,2,,2010-04-01 23:28:14.070000+00:00,146.0,2019-02-01 08:41:23.547000+00:00,2018-03-16 08:01:41.373000+00:00,,1851712.0,,256439.0,,1,517,rplotggplot2r-faq,1174114
429649,2612483,What's so bad about in-line CSS?,<p>When I see website starter code and example...,2612494.0,16,4,,2010-04-10 06:22:13.100000+00:00,26.0,2018-11-30 14:54:06.183000+00:00,2012-04-30 04:22:33.937000+00:00,,106224.0,,187491.0,,1,157,cssinline-styles,67323
429650,2789703,Remove stubborn underline from link,<p>I am attempting to have a link show up in w...,2789864.0,16,2,,2010-05-07 15:29:21.757000+00:00,65.0,2019-07-10 22:48:37.260000+00:00,2019-04-04 22:43:02.333000+00:00,,5250453.0,,174718.0,,1,478,csshyperlinkunderline,966460
429651,2710748,Run cURL commands from Windows console,<p>Is there a way to install cURL in Windows i...,2710766.0,18,5,,2010-04-26 02:10:23.710000+00:00,69.0,2019-02-25 13:26:21.037000+00:00,2013-07-22 14:21:28.830000+00:00,,1442342.0,,310648.0,,1,370,windowscommand-linecurl,727952
429652,2698817,Linear Layout and weight in Android,<p>I always read about this funny weight value...,2700501.0,18,1,,2010-04-23 13:18:23.607000+00:00,112.0,2019-06-22 08:04:58.940000+00:00,2019-05-14 15:31:36.977000+00:00,,648265.0,,114066.0,,1,248,androidandroid-linearlayoutandroid-layout-weight,365223
429653,2711297,Underline text in UIlabel,<p>How can I underline a text that could be mu...,,19,1,,2010-04-26 05:33:18.863000+00:00,31.0,2019-05-27 23:59:21.707000+00:00,2019-05-27 23:59:21.707000+00:00,,1033581.0,,325350.0,,1,81,iostextuikituilabelunderline,117585
429654,2664885,"Xcode ""Build and Archive"" from command line",<p>Xcode 3.2 provides an awesome new feature u...,4198166.0,19,6,,2010-04-19 02:18:34.360000+00:00,307.0,2019-02-13 04:45:12.953000+00:00,2010-07-21 05:46:19.007000+00:00,,54829.0,,54829.0,,1,377,xcodecommand-linebuild,270397
429655,3018289,"xcopy file, rename, suppress ""Does xxx specify...",<p>This seems pretty simple and maybe I'm just...,3018369.0,19,5,,2010-06-10 20:36:16.703000+00:00,59.0,2018-01-24 00:30:21.227000+00:00,,,,,38743.0,,1,383,command-linecommand-promptxcopy,339133
429656,2741859,How fast can you make linear search?,<p>I'm looking to optimize this linear search:...,,20,35,,2010-04-30 01:50:25.533000+00:00,11.0,2019-08-08 16:10:15.870000+00:00,2019-08-08 08:15:15.273000+00:00,,3345375.0,,80410.0,,1,24,csearchoptimizationsimdlinear-search,10245
429657,2336678,"Login without HTTPS, how to secure?","<p>For a webapplication, when HTTPS is not ava...",,20,21,,2010-02-25 18:43:17.767000+00:00,37.0,2018-12-19 21:00:14.397000+00:00,2015-01-02 20:29:22.407000+00:00,,4044998.0,,232542.0,,1,75,phpajaxsecurityencryptioncryptography,33335
429658,3137094,How to count lines in a document?,"<p>I have lines like these, and I want to know...",3137099.0,20,3,,2010-06-29 00:31:31.247000+00:00,184.0,2019-03-09 00:51:08.040000+00:00,2015-11-08 18:09:53.850000+00:00,,2229828.0,,368453.0,,1,946,linuxbashcommand-linescripting,1188881
429659,2732474,Restore a postgres backup file using the comma...,"<p>I'm new to postgresql, and locally, I use p...",2732521.0,20,0,,2010-04-28 19:18:10.693000+00:00,91.0,2019-08-10 06:40:56.100000+00:00,2013-02-11 10:21:56.883000+00:00,,559026.0,,287813.0,,1,217,postgresqlcommand-linebackuprestore,504631
429660,2668678,Importing CSV with line breaks in Excel 2007,<p>I'm working on a feature to export search r...,3089081.0,21,2,,2010-04-19 15:31:14.943000+00:00,14.0,2019-03-31 14:28:12.680000+00:00,2018-11-09 09:52:51.903000+00:00,,1671066.0,,56954.0,,1,104,excelcsvnewlineexcel-2007,153491
429661,2423777,Is it possible to create a remote repo on GitH...,<p>I created a new local Git repository:</p>\r...,2425632.0,22,0,,2010-03-11 09:25:00.493000+00:00,193.0,2019-02-19 22:56:44.753000+00:00,2017-06-09 13:56:12.433000+00:00,,3118209.0,,98378.0,,1,331,gitgithubsshversion-controlcommand-line-interface,134442
429662,2613800,How to convert DOS/Windows newline (CRLF) to U...,"<p>How can I programmatically (i.e., not using...",,23,3,,2010-04-10 15:03:34.317000+00:00,95.0,2019-06-23 01:29:08.633000+00:00,2018-03-25 15:43:33.153000+00:00,,608639.0,,313518.0,,1,304,linuxwindowsbashunixnewline,409851
429663,2840608,How do I add a newline to a TextView in Android?,<p>When I define a <code>TextView</code> in <c...,2842625.0,27,2,,2010-05-15 15:17:44.183000+00:00,19.0,2019-06-26 19:01:31.400000+00:00,2016-05-08 00:12:42.907000+00:00,,3290339.0,,243782.0,,1,237,androidnewlinetextview,321834
429664,2812770,Add centered text to the middle of a <hr/>-lik...,<p>I'm wondering what options one has in xhtml...,2812830.0,28,4,,2010-05-11 17:00:12.480000+00:00,69.0,2019-05-21 11:30:21.413000+00:00,2016-01-01 04:03:20.713000+00:00,,33822.0,,19212.0,,1,184,htmlcssxhtmllinevertical-alignment,224731

In [39]:
# let's delete questions without answers
dfPostQuestionsFiltered['id'][dfPostQuestionsFiltered['answer_count'] < 1].count()

74243

In [40]:
dfPostQuestionsFiltered = dfPostQuestionsFiltered[dfPostQuestionsFiltered['answer_count'] >= 1]

In [41]:
np.shape(dfPostQuestionsFiltered)

(355422, 22)

In [51]:
# let's also delete questions without accepted answers
dfPostQuestionsFiltered['id'][dfPostQuestionsFiltered['accepted_answer_id'] == ''].count()

104835

In [52]:
dfPostQuestionsFiltered = dfPostQuestionsFiltered[dfPostQuestionsFiltered['accepted_answer_id'] != '']

In [53]:
np.shape(dfPostQuestionsFiltered)

(173698, 21)

In [23]:
# read the model tags file to be used to create the tag features from the tagtext field in the questions file, which
# has all tag values concatenated without any separators

# NOTE: Used shortened version of model tag list below

dfModelTags = pd.read_csv("data/stackoverflow/modeltags_shortened.csv")

In [24]:
dfModelTags

          tagtext
0          python
1           scala
2          matlab
3      matplotlib
4       animation
5              d3
6         ggplot2
7            plot
8           graph
9           chart
10     highcharts
11             3d
12           maps
13        drawing
14         plotly
15      bar-chart
16  visualization
17        seaborn
18     geospatial
19      pie-chart
20       graphviz
21        diagram
22          radar

In [25]:
# add a new column to hold tags from the modeltags table that occur in the queion tags field

dfPostQuestionsFiltered['new_tags']=''

In [28]:
# find occurences of model tag values in tags filed, and append them to tbe new_tags field
def parsetags(qtag):
    tstr=''
    for i in dfModelTags['tagtext']:
        if i in qtag:
            tstr=tstr + i + " "
    return tstr

dfPostQuestionsFiltered['new_tags'] = dfPostQuestionsFiltered['tags'].map(parsetags)

In [29]:
dfPostQuestionsFiltered['new_tags']

0                          graph
1
2
3                matplotlib plot
4                           plot
5
6                          graph
7                          graph
8                          chart
9                    python plot
10                         graph
11
12                         graph
13
14
15                         graph
16
17
18
19                         graph
20                         graph
21
22                          plot
23                         graph
24
25
26
27
28            python plot plotly
29                  python graph
                   ...
429635
429636                     graph
429637                     graph
429638
429639
429640
429641              ggplot2 plot
429642
429643
429644    python matplotlib plot
429645
429646
429647
429648              ggplot2 plot
429649
429650
429651
429652
429653
429654
429655
429656
429657                     graph
429658
429659
429660
429661
429662
429663
429664
Name: new_tags, Length: 429665, dtype: object

In [22]:
dfPostQuestionsFiltered['tags']

0              reactjserror-handlinggraphqlapollographql-js
1                 javaspringazurespring-bootazure-pipelines
2                       filteringlinear-regressionresultset
3                                                matplotlib
4                                       counterscatter-plot
5                                     projectproject-online
6                         reactjsgraphqlreact-hooksmutation
7                                    graphcalendaroffice365
8                                                  teechart
9                                python-ggplotrisk-analysis
10          javascriptreactjsgraphqlreact-apolloreact-hooks
11        sharepointconnectiontimeoutsharepoint-onlinere...
12                      microsoft-graphmicrosoft-graph-mail
13        githubcommand-line-interfacerebasebranching-an...
14                    springcommand-linespring-cloud-config
15                                    graphundirected-graph
16                                  webcommunicationoffline
17                    node.jscommand-line-interfaceinquirer
18                node.jscommand-linegoogle-cloud-firestore
19                                                    graph
20                                           miningsubgraph
21                                    htmlsharepoint-online
22                                            loopsplotjpeg
23                                       facebook-graph-api
24                                     postgresqlpipelinedb
25                                         command-linewine
26                                parent-childparentoutline
27                       command-linegnome-terminalcinnameg
28                                         python-3.xplotly
29        python-3.xfacebook-graph-apifacebook-python-bu...
                                ...
429635                           svncommand-linetortoisesvn
429636                 c#.netsecurityencryptioncryptography
429637                      androidgraphicsffmpegscreenshot
429638    javascriptjqueryjavascript-eventsofflinenetwor...
429639                                   htmlcssline-breaks
429640    androidandroid-layoutlineandroid-xmlandroid-dr...
429641                                        rggplot2r-faq
429642                                           phpnewline
429643                                      javastringlines
429644                 pythonnumpystatisticsmatplotlibscipy
429645                                linuxbashshellnewline
429646          visual-studio-2010visual-studioline-numbers
429647                  linuxpdfmergecommand-line-interface
429648                                    rplotggplot2r-faq
429649                                     cssinline-styles
429650                                csshyperlinkunderline
429651                              windowscommand-linecurl
429652     androidandroid-linearlayoutandroid-layout-weight
429653                         iostextuikituilabelunderline
429654                               xcodecommand-linebuild
429655                      command-linecommand-promptxcopy
429656                 csearchoptimizationsimdlinear-search
429657                phpajaxsecurityencryptioncryptography
429658                       linuxbashcommand-linescripting
429659                  postgresqlcommand-linebackuprestore
429660                            excelcsvnewlineexcel-2007
429661    gitgithubsshversion-controlcommand-line-interface
429662                          linuxwindowsbashunixnewline
429663                               androidnewlinetextview
429664                   htmlcssxhtmllinevertical-alignment
Name: tags, Length: 429665, dtype: object

In [32]:
# Here is a separate process to check for references to the r language in the question body
# and set a separate 'r' column in the questions df to be used to update new_tags
#
# we cannot use the same process used on the tags above, since it will almost always find occurrences of 'r'
# in the tags field that are just parts of other terms (for example, the "r" in "chart")
#
# So, here we look for standalone references to r in the question body instead
#
dfPostQuestionsFiltered['r'] = ''

def testforr(x):
    if (' r ' in x) or (' r,' in x) or (' r.' in x) or (' r:' in x):
        return 'r '
    else:
        return ''

dfPostQuestionsFiltered['r'] = dfPostQuestionsFiltered['body'].map(testforr)

In [33]:
# now, update new_tags, appending the 'r' for questions referencing r in the question body
dfPostQuestionsFiltered['new_tags'] = dfPostQuestionsFiltered['new_tags'] + dfPostQuestionsFiltered['r']

In [36]:
dfPostQuestionsFiltered['new_tags'][dfPostQuestionsFiltered['r']=='r ']

202                     d3 graph r
243       python matplotlib plot r
257                              r
273                              r
308                         plot r
368           python plot plotly r
429                        graph r
434                 ggplot2 plot r
475                              r
593                        chart r
675       python matplotlib plot r
740                 ggplot2 plot r
751                 python graph r
756                        chart r
859       python matplotlib plot r
870                 ggplot2 plot r
894                 python graph r
1014            d3 visualization r
1092      python matplotlib plot r
1233                 plot plotly r
1236                 matlab plot r
1347                ggplot2 plot r
1496                python graph r
1523         ggplot2 plot plotly r
1577                ggplot2 plot r
1613                       graph r
1683                ggplot2 plot r
1738                       graph r
1891            chart highcharts r
1982                 plot plotly r
                    ...
425319                           r
425325                     graph r
425619                           r
425755                     graph r
425988               matlab plot r
426219                  graph 3d r
426310                   drawing r
426681                           r
426719                     graph r
426735                     graph r
426740                     graph r
426901                   drawing r
427162            graph graphviz r
427280                     graph r
427375                     graph r
427492                     graph r
427512                     graph r
427567              python chart r
427631                     graph r
427642                   drawing r
427669                3d drawing r
427819                     graph r
427831              ggplot2 plot r
428025        ggplot2 plot graph r
428161                     graph r
428507                     graph r
428565                     graph r
429107                   drawing r
429414                     graph r
429530                           r
Name: new_tags, Length: 4808, dtype: object

In [42]:
# drop the 'r' column, as it is no longer needed
del dfPostQuestionsFiltered['r']

In [43]:
dfPostQuestionsFiltered.loc[0]

id                                                                   56195999
title                          Apollo client doesn't display an error message
body                        <p>I have configured and set up a fully functi...
accepted_answer_id                                                 56196332.0
answer_count                                                                1
comment_count                                                               0
community_owned_date
creation_date                                2019-05-18 04:35:44.290000+00:00
favorite_count
last_activity_date                           2019-05-18 05:45:46.330000+00:00
last_edit_date                               2019-05-18 05:17:59.233000+00:00
last_editor_display_name
last_editor_user_id                                                 7916354.0
owner_display_name
owner_user_id                                                       7916354.0
parent_id
post_type_id                                                                1
score                                                                       2
tags                             reactjserror-handlinggraphqlapollographql-js
view_count                                                                256
new_tags                                                               graph
Name: 0, dtype: object

In [44]:
# now, let's drop any questions that do not have tags we are interested in

dfPostQuestionsFiltered['id'][dfPostQuestionsFiltered['new_tags'] == ''].count()

76889

In [45]:
dfPostQuestionsFiltered = dfPostQuestionsFiltered[dfPostQuestionsFiltered['new_tags'] != '']

In [46]:
np.shape(dfPostQuestionsFiltered)

(278533, 21)

In [54]:
# let's now create a separate question body column, 'cleaned_question_body', that removes all the code and all HTL tags
# from the question body
# We might use the cleaned_question_body as a feature in one of the similarity models
def clean_ques_body_text(body):
    tmp_body=BeautifulSoup(body,"lxml")
    for code in tmp_body('code'):
        code.replace_with('')
    tstr=''
    for string in tmp_body.stripped_strings:
        tstr = tstr + ' ' + string
    return tstr

dfPostQuestionsFiltered['cleaned_question_body']=''

sttime=time.time()    
dfPostQuestionsFiltered['cleaned_question_body'] = dfPostQuestionsFiltered['body'].map(clean_ques_body_text)
print('question body cleaned in',(time.time()-sttime)/60,'minutes')

C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

question body cleaned in 1.1601197679837545 minutes

In [55]:
dfPostQuestionsFiltered['body'].head()

0     <p>I have configured and set up a fully functi...
6     <p>I want to use a mutation in an event handle...
10    <p>I have useQuery and useMutation from react-...
70    <p>I'm coding in R and I have the following da...
72    <p>I am graphing the internet connection in my...
Name: body, dtype: object

In [56]:
dfPostQuestionsFiltered['cleaned_question_body'].head()

0      I have configured and set up a fully function...
6      I want to use a mutation in an event handler....
10     I have useQuery and useMutation from react-ap...
70     I'm coding in R and I have the following data...
72     I am graphing the internet connection in my a...
Name: cleaned_question_body, dtype: object

In [59]:
print('questions with cleaned_question_body == Nan',len(dfPostQuestionsFiltered['cleaned_question_body'][dfPostQuestionsFiltered['cleaned_question_body'].isna()]))

questions with cleaned_question_body == Nan 0

In [60]:
print('questions with cleaned_question_body == "" ',len(dfPostQuestionsFiltered['cleaned_question_body'][dfPostQuestionsFiltered['cleaned_question_body'] == '']))

questions with cleaned_question_body == ""  21

In [100]:
# write the dataframe to a tsv
dfPostQuestionsFiltered.to_csv("data/stackoverflow/PostQuestionsFiltered_V5_parsed.tsv", sep='\t', index=False)

In [101]:
# write the dataframe to a csv
dfPostQuestionsFiltered.to_csv("data/stackoverflow/PostQuestionsFiltered_V5_parsed.csv",index=False)

In [2]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST QUESTIONS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfPostQuestionsFiltered = pd.read_csv("data/stackoverflow/PostQuestionsFiltered_V5_parsed.tsv", sep='\t', keep_default_na=False)

In [3]:
dfPostQuestionsFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,...,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count,new_tags,cleaned_question_body
0,56195999,Apollo client doesn't display an error message,<p>I have configured and set up a fully functi...,56196332.0,1,0,,2019-05-18 04:35:44.290000+00:00,,2019-05-18 05:45:46.330000+00:00,...,7916354.0,,7916354.0,,1,2,reactjserror-handlinggraphqlapollographql-js,256,graph,I have configured and set up a fully function...
1,56212612,Calling a hook (useMutation) inside an event h...,<p>I want to use a mutation in an event handle...,56212940.0,1,0,,2019-05-19 22:47:04.330000+00:00,,2019-05-19 23:57:38.440000+00:00,...,,,10688712.0,,1,0,reactjsgraphqlreact-hooksmutation,261,graph,I want to use a mutation in an event handler....
2,56204854,How do I chain useQuery and useMutation in Gra...,<p>I have useQuery and useMutation from react-...,56206915.0,2,0,,2019-05-19 04:52:19.730000+00:00,,2019-07-15 12:45:21.457000+00:00,...,,,10116367.0,,1,0,javascriptreactjsgraphqlreact-apolloreact-hooks,262,graph,I have useQuery and useMutation from react-ap...
3,56189061,Customize lines based on specific criteria wit...,<p>I'm coding in R and I have the following da...,56197449.0,1,0,,2019-05-17 15:01:14.930000+00:00,,2019-05-18 08:58:44.763000+00:00,...,,,9537627.0,,1,0,rplotly,11,plot plotly,I'm coding in R and I have the following data...
4,56203260,How do I sum a list with its previous entries ...,<p>I am graphing the internet connection in my...,56203343.0,1,0,,2019-05-18 22:17:19.290000+00:00,,2019-05-18 22:32:10.980000+00:00,...,,,8598201.0,,1,0,pythonlistgraphsumiteration,11,python graph,I am graphing the internet connection in my a...
5,56218250,Modify y data in a line,<p>I have the following script</p>\r\r\n\r\r\n...,56220931.0,1,0,,2019-05-20 09:43:44.660000+00:00,,2019-05-20 12:22:29.497000+00:00,...,,,2749397.0,,1,0,matplotlib,11,matplotlib plot,I have the following script Expected Behavior...
6,56275333,Display Google Geochart in log scale,"<p>I'm using Google's <a href=""https://develop...",56275655.0,1,0,,2019-05-23 12:33:33.063000+00:00,,2019-05-23 12:51:20.197000+00:00,...,,,930151.0,,1,0,chartsgoogle-visualizationgeo,11,chart visualization,I'm using Google's geochart . I'm using the n...
7,55972829,Data displayed upon submission of a form is vi...,<p>I am trying to create create a calculator(f...,55973074.0,1,0,,2019-05-03 15:22:50.823000+00:00,,2019-05-03 15:36:57.783000+00:00,...,,,10067658.0,,1,0,javascriptplotly.js,12,plot plotly,I am trying to create create a calculator(for...
8,56095434,Every row given must be either null or an arra...,<p>I am trying to draw a line from google char...,56095454.0,1,0,,2019-05-12 01:01:47.690000+00:00,,2019-05-12 01:16:52.103000+00:00,...,,,11375519.0,,1,0,phpmysqlgoogle-visualization,12,visualization,I am trying to draw a line from google chart ...
9,56260378,Make Highcharts pick a smart y-axis min,"<p>For a bar or column chart in Highcharts, is...",56260575.0,1,0,,2019-05-22 15:33:03.250000+00:00,,2019-05-22 15:44:21.623000+00:00,...,,,614263.0,,1,0,chartshighchartsstatistics,13,chart highcharts,"For a bar or column chart in Highcharts, is t..."
10,56191057,I would like to create a column chart where ea...,<p>I would like to make a column chart which t...,56191181.0,2,0,,2019-05-17 17:30:36.020000+00:00,,2019-05-17 17:40:26.183000+00:00,...,,,9393218.0,,1,0,rggplot2bar-chart,14,ggplot2 plot chart bar-chart,I would like to make a column chart which tak...
11,56271400,Change the width of the plot,<p>I create a bar plot with python : </p>\r\r\...,56271481.0,1,0,,2019-05-23 08:48:25.737000+00:00,,2019-05-23 08:54:18.917000+00:00,...,,,11482231.0,,1,0,python-3.xbar-chart,14,python chart bar-chart,I create a bar plot with python : My question...
12,56290967,Highcharts custom attribute with datetime line...,<p>I have a line chart with <code>xAxis</code>...,56291205.0,1,0,,2019-05-24 10:37:47.387000+00:00,,2019-05-24 10:53:10.670000+00:00,...,,,1722794.0,,1,0,highcharts,14,chart highcharts,I have a line chart with values as timestamps...
13,56298788,How to write and save each line separately on ...,<p>I'm running two .py files. One creates one ...,56298852.0,1,0,,2019-05-24 19:51:08.473000+00:00,,2019-05-24 19:57:40.767000+00:00,...,,,9948523.0,,1,0,python-3.xmatplotlibdynamicwritefile,14,python matplotlib plot,I'm running two .py files. One creates one ra...
14,56026765,Can't display gauge chart inside a jquery get,<p>I can't get to display a google gauge chart...,56027042.0,1,0,,2019-05-07 16:20:26.053000+00:00,,2019-05-07 16:40:15.513000+00:00,...,5090771.0,,1967683.0,,1,1,jquerychartsgoogle-visualization,15,chart visualization,"I can't get to display a google gauge chart, ..."
15,56172013,How to Change Theme On 3D Pie for JpChart,<p>I can't get the theme or slice colors to ch...,56183832.0,1,0,,2019-05-16 15:30:37.923000+00:00,,2019-05-17 09:47:34.307000+00:00,...,,,2630240.0,,1,0,phpjpgraph,15,graph,I can't get the theme or slice colors to chan...
16,56241219,How to reference/name specific part of a shape?,<p>I want to reference a specific part of a sh...,56245660.0,1,0,,2019-05-21 15:04:03.047000+00:00,,2019-05-21 20:07:11.600000+00:00,...,,,4864040.0,,1,0,graphvizdot,15,graph graphviz,I want to reference a specific part of a shap...
17,56073199,How to get animated charts in a fluid like man...,<p>I am trying to display the charts using Ang...,56074853.0,1,0,,2019-05-10 08:01:42.817000+00:00,,2019-05-10 09:40:21.497000+00:00,...,,,11253744.0,,1,0,angularjszingchart,16,chart,I am trying to display the charts using Angul...
18,56113691,How to select multiple series in the legend - ...,<p>I would like to select multiple series in t...,56133438.0,1,0,,2019-05-13 13:44:16.190000+00:00,,2019-05-14 15:00:56.090000+00:00,...,,,11458934.0,,1,0,javascriptrshinydashboardr-highcharter,16,chart,I would like to select multiple series in the...
19,56169033,How to be sure that my scale axis does not var...,<p>I am plotting maps of interactions between ...,56172534.0,1,0,,2019-05-16 12:51:12.077000+00:00,,2019-05-16 16:02:10.797000+00:00,...,787480.0,,11509868.0,,1,1,gnuplot,16,plot,I am plotting maps of interactions between re...
20,56175964,Geom bar - dodging a population consisting of ...,<p>I want to make a plot that would show distr...,56176120.0,1,0,,2019-05-16 20:13:55.440000+00:00,,2019-05-17 04:25:31.907000+00:00,...,8449629.0,,11396571.0,,1,0,rggplot2geom-bar,16,ggplot2 plot,I want to make a plot that would show distrib...
21,56241666,Highchart Marker image hides if large dataset ...,<p>I have added image as marker in highchart a...,56241940.0,1,0,,2019-05-21 15:29:26.273000+00:00,,2019-05-21 15:45:32.557000+00:00,...,,,3970774.0,,1,0,javascripthighcharts,16,chart highcharts,I have added image as marker in highchart and...
22,56264098,Can I bold invididual elements in y_range of a...,<p>I would like to bold some of the values in ...,56265233.0,1,0,,2019-05-22 19:57:14.390000+00:00,,2019-05-22 22:11:20.800000+00:00,...,,,4495722.0,,1,0,textlabelbar-chartbokehaxis,16,chart bar-chart,I would like to bold some of the values in my...
23,55972445,How can i set the json encode result to the hi...,"<p>I currently new to this chart, I just wante...",55972739.0,1,0,,2019-05-03 15:00:49.223000+00:00,,2019-05-03 15:17:18.907000+00:00,...,,,6314424.0,,1,0,jsonajaxhighcharts,17,chart highcharts,"I currently new to this chart, I just wanted ..."
24,56082261,Changing extent of image and matching plot wit...,<p>I'm creating a figure in matplotlib with tw...,56085359.0,1,0,,2019-05-10 17:25:36.090000+00:00,,2019-05-10 22:04:50.067000+00:00,...,,,11395993.0,,1,0,pythonimagematplotlibscaleaxis,17,python matplotlib plot,I'm creating a figure in matplotlib with two ...
25,56084249,How to change the range of point sizes when po...,<p>I would like to retain the relative size di...,56084939.0,1,0,,2019-05-10 20:12:05.173000+00:00,,2019-05-11 04:00:05.593000+00:00,...,8449629.0,,10719713.0,,1,0,rggplot2scatter-plot,17,ggplot2 plot,I would like to retain the relative size diff...
26,56209617,Annotating line chart,<p>I am having troubles annotating my line cha...,56210341.0,1,0,,2019-05-19 16:06:54.143000+00:00,,2019-05-19 17:29:46.737000+00:00,...,,,7158458.0,,1,0,pythonmatplotlib,17,python matplotlib plot,I am having troubles annotating my line chart...
27,56258396,How to set user name to UITextField from FBSDK...,"<p>I am using Xcode 10, Swift 5 and I am tryin...",56258707.0,1,0,,2019-05-22 13:48:57.233000+00:00,,2019-05-22 15:19:33.493000+00:00,...,,,8540450.0,,1,1,swiftfacebook-graph-api,17,graph,"I am using Xcode 10, Swift 5 and I am trying ..."
28,56278880,set plot background colour when `axes` is not ...,<p>I have the a function to create stacked bar...,56279039.0,1,0,,2019-05-23 15:48:43.310000+00:00,,2019-05-23 19:00:22.390000+00:00,...,4932316.0,,8839068.0,,1,0,pythonmatplotlibbar-chart,17,python matplotlib plot chart bar-chart,I have the a function to create stacked bar p...
29,55984838,how I can make two index inequal in ampl?,<p>I know if I want to make 2 index inequal in...,55986667.0,1,0,,2019-05-04 16:58:58.763000+00:00,,2019-05-04 20:46:36.003000+00:00,...,,,9272398.0,,1,0,linear-programmingamplglpk,18,r,I know if I want to make 2 index inequal in a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173668,2785093,Facebook 'Friends.getAppUsers' using Graph API,<p>I have an application that uses the old RES...,3066091.0,8,0,,2010-05-06 23:02:16.307000+00:00,59.0,2014-04-12 09:41:44.197000+00:00,...,1045444.0,,233202.0,,1,87,facebookfacebook-graph-apifacebook-friends,65839,graph,I have an application that uses the old REST ...
173669,2769539,Simple integer encryption,<p>Is there a simple algorithm to encrypt inte...,2769563.0,9,0,,2010-05-04 23:03:38.447000+00:00,6.0,2018-05-10 07:25:28.697000+00:00,...,297592.0,,297592.0,,1,4,algorithmlanguage-agnosticcryptography,6711,graph,Is there a simple algorithm to encrypt intege...
173670,2862285,How do I order the friends list returned from ...,<p>You can get a list of friends of an authent...,2862420.0,9,0,,2010-05-19 01:26:10.240000+00:00,1.0,2013-11-05 10:34:58.243000+00:00,...,,,53653.0,,1,9,facebookfacebook-graph-api,17401,graph,You can get a list of friends of an authentic...
173671,2742023,Software/Webapp for creating computer science ...,<p>What are some good programs or web-based ap...,2742028.0,9,0,,2010-04-30 02:46:33.690000+00:00,4.0,2017-08-22 21:43:50.787000+00:00,...,,,2045611.0,,1,11,data-structuresdiagrams,2195,diagram,What are some good programs or web-based appl...
173672,3028380,How to convert BigInteger to String in java,<p>I converted a <code>String</code> to <code>...,3028429.0,9,2,,2010-06-12 10:43:43.437000+00:00,9.0,2019-01-24 07:14:51.060000+00:00,...,1033581.0,,270906.0,,1,28,javastringcryptographybiginteger,90018,graph,I converted a to as follows: Now I want my st...
173673,2654480,Writing BMP image in pure c/c++ without other ...,<p>In my algorithm i need create information o...,2654491.0,9,3,,2010-04-16 16:11:39.807000+00:00,21.0,2019-05-28 06:32:50.403000+00:00,...,2300216.0,,272779.0,,1,38,c++cimagegraphicsbmp,114617,graph,In my algorithm i need create information out...
173674,3012905,How can I display the users profile pic using ...,<p>I would like to display the users profile p...,3012980.0,9,0,,2010-06-10 08:48:52.277000+00:00,25.0,2019-07-17 03:09:06.630000+00:00,...,1033581.0,,270311.0,,1,70,phpfacebookfacebook-graph-api,114748,graph,I would like to display the users profile pic...
173675,3002067,How are software license keys generated?,<p>License keys are the defacto-standard as an...,3050217.0,9,9,,2010-06-08 23:24:04.983000+00:00,209.0,2018-08-03 01:38:12.330000+00:00,...,10064859.0,,183528.0,,1,348,securitycryptographylicense-key,118005,graph,License keys are the defacto-standard as an a...
173676,2471884,Histogram using gnuplot?,<p>I know how to create a histogram (just use ...,2538846.0,9,2,,2010-03-18 17:10:28.857000+00:00,78.0,2018-11-20 13:29:28.003000+00:00,...,,,2003845.0,,1,198,gnuplothistogrambinning,198787,plot,"I know how to create a histogram (just use ""w..."
173677,2918362,Writing string to a file on a new line every time,<p>I want to append a newline to my string eve...,2918370.0,9,0,,2010-05-27 03:56:12.210000+00:00,27.0,2019-04-18 07:23:20.533000+00:00,...,3474146.0,,346949.0,,1,201,pythonnewline,537507,python,I want to append a newline to my string every...
173678,2427621,Graphical Programming Language,"<p>In control engineering or instrumentation, ...",2427715.0,10,3,,2010-03-11 18:30:27.743000+00:00,2.0,2015-12-12 01:26:57.410000+00:00,...,-1.0,,260127.0,,1,4,programming-languagesgraphical-language,2915,graph,"In control engineering or instrumentation, I ..."
173679,2600097,UML Diagram Tool - Eclipse plugin?,<p>Can anyone help me? I am currently using Ec...,2600272.0,10,0,,2010-04-08 13:19:53.323000+00:00,5.0,2018-04-27 19:49:37.153000+00:00,...,814702.0,,94279.0,,1,11,javaeclipseeclipse-pluginumlclass-diagram,41550,diagram,Can anyone help me? I am currently using Ecli...
173680,2925169,UML diagrams that are actually pretty?,<p>I'm looking for a diagramming software that...,2927863.0,10,5,,2010-05-27 21:38:38.390000+00:00,10.0,2017-10-13 07:11:30.163000+00:00,...,,,21728.0,,1,20,umldiagramming,7933,diagram,I'm looking for a diagramming software that w...
173681,2768807,Quantum Computing and Encryption Breaking,<p>I read a while back that Quantum Computers ...,2768918.0,10,4,,2010-05-04 20:37:43.960000+00:00,19.0,2018-03-20 03:43:32.077000+00:00,...,58635.0,,69742.0,,1,26,encryptioncryptographyquantum-computing,9894,graph,I read a while back that Quantum Computers ca...
173682,2966015,Facebook: get list of pages that a user is adm...,<p>I'm using the graph api.</p>\r\r\n\r\r\n<p>...,8076688.0,10,0,,2010-06-03 12:46:48.683000+00:00,35.0,2019-02-06 10:22:47.007000+00:00,...,155175.0,,6691.0,,1,71,facebookfacebook-graph-apifacebook-page,84735,graph,I'm using the graph api. I have a logged in u...
173683,2640971,Windows is not passing command line arguments ...,<p>I'm having trouble getting command line arg...,2641185.0,10,6,,2010-04-14 20:56:11.527000+00:00,32.0,2018-12-21 12:31:55.950000+00:00,...,2230844.0,,178521.0,,1,81,pythonwindowsregistrycommand-line-argumentsfil...,29058,python,I'm having trouble getting command line argum...
173684,2834931,What methods are used to visualize a 4-dimensi...,<p>An Array ( a row of elements ):</p>\r\r\n\r...,2835128.0,11,7,,2010-05-14 14:33:44.433000+00:00,6.0,2018-01-13 20:12:09.713000+00:00,...,,,26931.0,,1,14,multidimensional-arrayvisualization,15852,visualization,An Array ( a row of elements ): A 2-D Array (...
173685,2570633,smallest filesize for transparent single pixel...,<p>I'm looking for the smallest (in terms of f...,2570645.0,11,10,,2010-04-03 08:13:57.997000+00:00,23.0,2018-08-18 05:59:26.633000+00:00,...,300204.0,,300204.0,,1,62,imagegraphicstransparencyfilesize,22219,graph,I'm looking for the smallest (in terms of fil...
173686,2512225,Matplotlib plots not showing up in Mac OSX?,<p>I am running Mac OSX 10.5.8. I installed ma...,2512358.0,11,1,,2010-03-24 23:36:24.470000+00:00,23.0,2019-06-07 20:54:46.113000+00:00,...,202229.0,,171546.0,,1,67,pythonmacosmatplotlibplot,57398,python matplotlib plot,I am running Mac OSX 10.5.8. I installed matp...
173687,2860943,How can I hash a password in Java?,<p>I need to hash passwords for storage in a d...,2861125.0,11,6,,2010-05-18 20:35:16.367000+00:00,92.0,2019-03-09 23:29:19.037000+00:00,...,1768232.0,,84131.0,,1,165,javapasswordscryptographic-hash-function,139246,graph,I need to hash passwords for storage in a dat...
173688,2369492,Generate a heatmap in MatPlotLib using a scatt...,"<p>I have a set of X,Y data points (about 10k)...",2461029.0,11,1,,2010-03-03 07:42:17.563000+00:00,112.0,2019-06-11 17:37:16.953000+00:00,...,2692780.0,,121075.0,,1,169,pythonmatplotlibheatmaphistogram2d,187187,python matplotlib plot,"I have a set of X,Y data points (about 10k) t..."
173689,2405292,"How to check if text is ""empty"" (spaces, tabs,...",<p>How can I test if the string is empty in Py...,2405300.0,11,0,,2010-03-08 22:29:25.310000+00:00,24.0,2019-06-10 11:28:32.037000+00:00,...,,,257942.0,,1,183,pythontextnewlinetabsspace,190084,python,How can I test if the string is empty in Pyth...
173690,2713336,Are ASCII diagrams worth my time?,<p>Are ASCII diagrams within source code worth...,2714292.0,12,9,,2010-04-26 12:20:05.923000+00:00,3.0,2019-03-25 18:04:52.437000+00:00,...,1677912.0,,253514.0,,1,18,language-agnosticasciidiagram,3577,diagram,Are ASCII diagrams within source code worth t...
173691,2801882,Generating a PNG with matplotlib when DISPLAY ...,<p>I am trying to use networkx with Python. Wh...,3054314.0,12,3,,2010-05-10 10:22:33.093000+00:00,109.0,2019-01-26 07:54:37.640000+00:00,...,2966723.0,,3836677.0,,1,303,pythonmatplotlibgraph,162518,python matplotlib plot graph,I am trying to use networkx with Python. When...
173692,2486093,Millions of 3D points: How to find the 10 of t...,"<p>A point in 3-d is defined by (x,y,z). Dista...",2486341.0,12,3,,2010-03-21 05:47:06.523000+00:00,62.0,2012-07-24 06:38:06.620000+00:00,...,65977.0,,80433.0,,1,67,algorithmgraphicsgraph,27624,graph,"A point in 3-d is defined by (x,y,z). Distanc..."
173693,3206622,Is putting data in cookies secure?,<p>I am using asp.net mvc 2.0 and I am wonderi...,3206715.0,14,1,,2010-07-08 18:07:13.610000+00:00,3.0,2016-05-03 11:08:08.187000+00:00,...,31532.0,,130015.0,,1,14,c#.netsecurityencryptioncryptography,5013,graph,I am using asp.net mvc 2.0 and I am wondering...
173694,2807070,Screenshot of the Nexus One from adb?,<p>My goal is to be able to type a one word co...,11798991.0,14,0,,2010-05-10 23:16:20.110000+00:00,34.0,2015-04-23 15:14:36.843000+00:00,...,750613.0,,9574.0,,1,46,androidgraphicsffmpegscreenshot,33532,graph,My goal is to be able to type a one word comm...
173695,3099219,ggplot with 2 y axes on each side and differen...,<p>I need to plot a bar chart showing counts a...,3117319.0,14,3,,2010-06-23 05:52:19.900000+00:00,82.0,2019-05-27 19:58:38.600000+00:00,...,6461462.0,,373908.0,,1,202,rggplot2r-faq,233516,ggplot2 plot,I need to plot a bar chart showing counts and...
173696,3209362,How to plot empirical cdf in matplotlib in Pyt...,<p>How can I plot the empirical CDF of an arra...,3213923.0,15,0,,2010-07-09 02:14:18.633000+00:00,35.0,2019-03-04 10:37:48.900000+00:00,...,1301710.0,user248237,,,1,55,pythonnumpystatisticsmatplotlibscipy,64507,python matplotlib plot,How can I plot the empirical CDF of an array ...
173697,2564258,Plot two graphs in same plot in R,<p>I would like to plot y1 and y2 in the same ...,2564276.0,16,2,,2010-04-01 23:28:14.070000+00:00,146.0,2019-02-01 08:41:23.547000+00:00,...,1851712.0,,256439.0,,1,517,rplotggplot2r-faq,1174114,ggplot2 plot,I would like to plot y1 and y2 in the same pl...

In [61]:
# retrieving the answers that belong to the questions retrieved above

sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.posts_answers` WHERE parent_id IN 
    (SELECT id FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%plot%' 
        OR tags LIKE '%graph%'
        OR tags LIKE '%chart%'
        OR tags LIKE '%visualiz%'
        OR tags LIKE '%choropleth%'
        OR tags LIKE '%drawing%'
        OR tags LIKE '%line%'
        OR tags LIKE '%geospatial%'
        OR tags LIKE '%diagram%'))
"""
dfPostAnswersFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [62]:
np.shape(dfPostAnswersFiltered)

(545457, 20)

In [ ]:
# write the dataframe to a tsv
dfPostAnswersFiltered.to_csv("data/stackoverflow/PostAnswersFiltered_raw_12_06_19.tsv", sep='\t', index=False)

In [ ]:
# in case you want to delete the dfPostQuestionsFiltered dataframe

# ** NOTE** For the rest of the process to work correctly, you must save the raw file after executing the Big Query SQL select above
# (use the cell immediately above to save it), then run this cell to delete the dataframe,
# then re-load it using he cell below with the "keep_default_na" paramter in order to remove the NaN -type values in the dataset

del dfPostAnswersFiltered

In [67]:
# Use this code to re-load raw Stack Overflow questions to the Pandas df -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to

dfPostAnswersFiltered = pd.read_csv("data/stackoverflow/PostAnswersFiltered_raw_12_06_19.tsv", sep='\t', keep_default_na=False)

In [69]:
np.shape(dfPostAnswersFiltered)

(545457, 20)

In [71]:
dfPostAnswersFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,44629055,,<p>One possible solution: I do not actually n...,,,0,,2017-06-19 11:12:02.083000+00:00,,2017-06-19 11:12:02.083000+00:00,,,,,8138226.0,44567221,2,0,,
1,44629646,,"<p>I've changed your function in a little, try...",,,0,,2017-06-19 11:43:10.483000+00:00,,2017-06-19 11:43:10.483000+00:00,,,,,6618051.0,41982761,2,0,,
2,44630291,,<p>Currently there is no click event on catego...,,,0,,2017-06-19 12:13:24.530000+00:00,,2017-06-19 12:13:24.530000+00:00,,,,,3437934.0,44297012,2,0,,
3,44631329,,<p>It's better to create separate files for CS...,,,0,,2017-06-19 13:01:51+00:00,,2017-06-19 13:01:51+00:00,,,,,3582474.0,44630985,2,0,,
4,44632276,,<p>The correct syntax is this one:</p>\r\n\r\n...,,,0,,2017-06-19 13:43:45.580000+00:00,,2017-06-19 13:43:45.580000+00:00,,,,,5222773.0,43895941,2,0,,
5,44632434,,<p>You can define the lines from the dataset w...,,,0,,2017-06-19 13:51:27.790000+00:00,,2017-06-19 13:51:27.790000+00:00,,,,,3951036.0,44621561,2,0,,
6,44633649,,<p>The way matplotlib is working is that you h...,,,0,,2017-06-19 14:47:46.830000+00:00,,2017-06-19 14:47:46.830000+00:00,,,,,4124317.0,44633422,2,0,,
7,44633675,,"<p>I have figured out the answer, which is to ...",,,0,,2017-06-19 14:48:42.900000+00:00,,2017-06-19 14:48:42.900000+00:00,,,,,8050923.0,44624707,2,0,,
8,44634042,,<p>I resolved it.</p>\r\n\r\n<pre><code>Get-Co...,,,0,,2017-06-19 15:06:24.867000+00:00,,2017-06-19 15:06:24.867000+00:00,,,,,7065080.0,44633338,2,0,,
9,44635048,,<p>To further a_guest answer - To enable see t...,,,0,,2017-06-19 15:56:06.457000+00:00,,2017-06-19 15:56:06.457000+00:00,,,,,1704227.0,44632018,2,0,,
10,44635254,,<p>You can look for a good combination of colo...,,,0,,2017-06-19 16:08:09.660000+00:00,,2017-06-19 16:08:09.660000+00:00,,,,,8183796.0,44472156,2,0,,
11,44635554,,<p>Pygame should be a dependency of turtle. Tr...,,,0,,2017-06-19 16:23:53.323000+00:00,,2017-06-19 16:23:53.323000+00:00,,,,,7030141.0,44635474,2,0,,
12,44636226,,<p>You've been working inside a Python standar...,,,0,,2017-06-19 17:06:25.743000+00:00,,2017-06-19 17:06:25.743000+00:00,,,,,2357112.0,44635474,2,0,,
13,44636285,,<p>Since you've mentioned that the transformat...,,,0,,2017-06-19 17:10:08.570000+00:00,,2017-06-19 17:10:08.570000+00:00,,,,,8060278.0,18506201,2,0,,
14,44636462,,<p>What range/data is selected at the time the...,,,0,,2017-06-19 17:22:09.553000+00:00,,2017-06-19 17:22:09.553000+00:00,,,,,478884.0,44632742,2,0,,
15,44637074,,<p>Detecting when the canvas size changes can ...,,,0,,2017-06-19 18:00:31.187000+00:00,,2017-06-19 18:00:31.187000+00:00,,,,,6809536.0,44636715,2,0,,
16,44637233,,<blockquote>\r\n <p>other times they generate...,,,0,,2017-06-19 18:10:38.517000+00:00,,2017-06-19 18:17:44.853000+00:00,2017-06-19 18:17:44.853000+00:00,,4926357.0,,4926357.0,44632742,2,0,,
17,44637579,,<p>Well I did this by simply copy the texture ...,,,0,,2017-06-19 18:31:54.673000+00:00,,2017-06-19 21:09:34.603000+00:00,2017-06-19 21:09:34.603000+00:00,,2521214.0,,2521214.0,44619304,2,0,,
18,44637833,,<p>I solved it this way:</p>\r\n\r\n<p>Create ...,,,0,,2017-06-19 18:48:36.953000+00:00,,2017-06-19 18:48:36.953000+00:00,,,,,4958831.0,29515631,2,0,,
19,44638474,,<p>This is what you have been looking for. Not...,,,0,,2017-06-19 19:29:54.890000+00:00,,2017-06-19 19:29:54.890000+00:00,,,,,8113019.0,44275195,2,0,,
20,44638617,,<p>You don't appear to be using <code>mlt.text...,,,0,,2017-06-19 19:39:24.230000+00:00,,2017-06-19 19:39:24.230000+00:00,,,,,5548599.0,44638406,2,0,,
21,44638689,,"<p>Seeing the error code you've posted, it see...",,,0,,2017-06-19 19:43:20.573000+00:00,,2017-06-19 19:43:20.573000+00:00,,,,,8117998.0,44635474,2,0,,
22,44638770,,<p>You can plot without the labels and then ad...,,,0,,2017-06-19 19:48:53.330000+00:00,,2017-06-19 19:48:53.330000+00:00,,,,,6136167.0,44638396,2,0,,
23,44639041,,<p>Python turtle was designed to either be emb...,,,0,,2017-06-19 20:06:46.950000+00:00,,2017-06-19 20:06:46.950000+00:00,,,,,5771269.0,44634947,2,0,,
24,44639185,,<p>As far as I know there are three common pla...,,,0,,2017-06-19 20:15:06.870000+00:00,,2017-06-19 20:15:06.870000+00:00,,,,,7334835.0,44493790,2,0,,
25,44639606,,<p>Try this: <strong><code>sed -r 's/\b[A-Z]+ ...,,,0,,2017-06-19 20:41:55.330000+00:00,,2017-06-21 14:11:54.083000+00:00,2017-06-21 14:11:54.083000+00:00,,3120884.0,,3120884.0,44636721,2,0,,
26,44642203,,"<p>thank you for your attention, i did solve i...",,,0,,2017-06-20 01:07:20.283000+00:00,,2017-06-20 01:07:20.283000+00:00,,,,,3341452.0,44555246,2,0,,
27,44642873,,<p>You need to run the build agent in <a href=...,,,0,,2017-06-20 02:30:41.657000+00:00,,2017-06-20 02:30:41.657000+00:00,,,,,5475003.0,44552023,2,0,,
28,44642981,,<pre><code>labs$countries &lt;- countries\r\ng...,,,0,,2017-06-20 02:44:16.710000+00:00,,2017-06-20 02:44:16.710000+00:00,,,,,6203226.0,44642408,2,0,,
29,44643491,,"<p>Figured it out, thanks for your help></p>\r...",,,0,,2017-06-20 03:46:33.820000+00:00,,2017-06-20 03:46:33.820000+00:00,,,,,5242442.0,44622428,2,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545427,13136482,,<p>There are several perl modules which do thi...,,,12,,2012-10-30 09:55:53.720000+00:00,,2012-10-30 09:55:53.720000+00:00,,,,,784338.0,13136247,2,2,,
545428,12769698,,"<p>Regarding (1): </p>\r\n\r\n<p>First, why ar...",,,12,,2012-10-07 14:31:27.737000+00:00,,2012-10-10 18:50:50.510000+00:00,2012-10-10 18:50:50.510000+00:00,,1219295.0,,1219295.0,12769353,2,3,,
545429,12940339,,<p>Using <code>preg_match_all</code> with more...,,,12,,2012-10-17 17:52:58.163000+00:00,,2012-10-18 01:51:51.523000+00:00,2012-10-18 01:51:51.523000+00:00,,875362.0,,875362.0,12939909,2,3,,
545430,13042922,,<p>It would be to your advantage to have a rea...,,,12,,2012-10-24 04:11:58.110000+00:00,,2012-10-24 04:11:58.110000+00:00,2017-05-23 12:03:27.983000+00:00,,-1.0,,992484.0,13042778,2,3,,
545431,13145956,,<p>Instead of reading the entire thing into me...,,,12,,2012-10-30 19:03:30.380000+00:00,,2012-10-30 19:54:19.417000+00:00,2012-10-30 19:54:19.417000+00:00,,1053.0,,1053.0,13145924,2,5,,
545432,13320284,,"<p>Yes, you can composite the layer of the vie...",,,12,,2012-11-10 07:47:53.163000+00:00,,2012-11-10 07:47:53.163000+00:00,,,,user529758,,13320195,2,5,,
545433,12927886,,<p>You can create something along the lines of...,,,12,,2012-10-17 05:49:19.777000+00:00,,2012-10-29 07:48:44.010000+00:00,2012-10-29 07:48:44.010000+00:00,,1033808.0,,1033808.0,12926779,2,12,,
545434,13143467,,<blockquote>\r\n <p>WebGL is actually a 2D AP...,,,12,,2012-10-30 16:26:31.867000+00:00,,2012-11-01 17:50:04.493000+00:00,2012-11-01 17:50:04.493000+00:00,,734069.0,,734069.0,13135210,2,24,,
545435,13153865,,<hr>\r\n\r\n<p>Edit: 2013.01.15 - If your serv...,,,12,,2012-10-31 08:25:46.587000+00:00,,2013-05-16 17:49:22.863000+00:00,2017-05-23 12:02:59.213000+00:00,,-1.0,,492983.0,4795385,2,33,,
545436,12763851,,"<p>the grid is a 35-bit number, so you can sto...",,,13,,2012-10-06 21:02:57.263000+00:00,,2012-10-06 21:02:57.263000+00:00,,,,,235354.0,12763838,2,1,,
545437,13293635,,<p>When you are creating your Open Graph custo...,,,13,,2012-11-08 16:46:57.157000+00:00,,2012-11-09 11:05:09.323000+00:00,2012-11-09 11:05:09.323000+00:00,,850947.0,,850947.0,13292346,2,1,,
545438,13070034,,<p>Are you setting the width value to 0dp as w...,,,13,,2012-10-25 13:46:31.400000+00:00,,2012-10-25 14:16:09.650000+00:00,2012-10-25 14:16:09.650000+00:00,,371077.0,,371077.0,13069882,2,4,,
545439,13138254,,<h1>First example</h1>\r\n\r\n<p>In the follow...,,,13,,2012-10-30 11:43:22.100000+00:00,,2012-10-30 13:42:52.667000+00:00,2012-10-30 13:42:52.667000+00:00,,1468366.0,,1468366.0,13137761,2,5,,
545440,13108713,,<p>Your painting code is in the wrong place an...,,,14,,2012-10-28 12:15:33.643000+00:00,,2012-10-28 12:20:45.430000+00:00,2012-10-28 12:20:45.430000+00:00,,505088.0,,505088.0,13108683,2,0,,
545441,12877493,,<p>Disable erase background event. When wxWidg...,,,14,,2012-10-13 22:12:34.420000+00:00,,2012-10-14 13:09:48.107000+00:00,2012-10-14 13:09:48.107000+00:00,,16582.0,,16582.0,12877307,2,1,,
545442,13314421,,<p>There are a few possible solutions to this:...,,,14,,2012-11-09 19:11:37.557000+00:00,,2012-11-09 22:02:16.970000+00:00,2012-11-09 22:02:16.970000+00:00,,1336150.0,,1336150.0,13314368,2,6,,
545443,12813949,,<p>You can just add up sizes recursively (the ...,,,14,,2012-10-10 07:16:24.880000+00:00,,2013-06-09 15:57:20+00:00,2013-06-09 15:57:20+00:00,,73070.0,,73070.0,12813826,2,106,,
545444,12792279,,<p>You can skip the <code>match</code> part an...,,,15,,2012-10-09 03:03:11.970000+00:00,,2012-10-09 03:21:45.337000+00:00,2012-10-09 03:21:45.337000+00:00,,464744.0,,464744.0,12792244,2,2,,
545445,12985753,,<p><strong>Edit:</strong> so you just ran into...,,,15,,2012-10-20 06:04:35.747000+00:00,,2012-10-20 06:46:52.683000+00:00,2012-10-20 06:46:52.683000+00:00,user529758,,user529758,,12985593,2,3,,
545446,13103768,,"<p>Outside your while loop, you need to first ...",,,16,,2012-10-27 20:11:36.447000+00:00,,2012-10-31 20:14:51.820000+00:00,2012-10-31 20:14:51.820000+00:00,,251173.0,,251173.0,13103726,2,0,,
545447,12924191,,"<p>You should use the <a href=""http://www.open...",,,16,,2012-10-16 22:06:12.517000+00:00,,2012-10-17 05:34:32.353000+00:00,2012-10-17 05:34:32.353000+00:00,user1696837,,,1736304.0,12909102,2,1,,
545448,13032255,,<p>C++ doesn't support variable-length arrays....,,,16,,2012-10-23 14:03:04.430000+00:00,,2012-10-23 14:09:01.400000+00:00,2012-10-23 14:09:01.400000+00:00,,673730.0,,673730.0,13032222,2,1,,
545449,12867283,,<p>If you can make the same call via the Graph...,,,16,,2012-10-12 21:22:03.470000+00:00,,2012-10-12 21:22:03.470000+00:00,,,,,321505.0,12867108,2,2,,
545450,12809902,,<p>You can restrict the data returned by faceb...,,,17,,2012-10-09 23:32:29.333000+00:00,,2013-05-26 10:55:17.287000+00:00,2013-05-26 10:55:17.287000+00:00,,828705.0,,828705.0,12809224,2,3,,
545451,12806484,,<p>You are looking for <code>std::getline()</c...,,,17,,2012-10-09 18:49:26.777000+00:00,,2019-01-17 15:59:35.583000+00:00,2019-01-17 15:59:35.583000+00:00,,480982.0,,505088.0,12806450,2,30,,
545452,13295880,,"<p>Try this,</p>\r\n\r\n<pre><code> gA &lt;- g...",,,18,,2012-11-08 19:00:15.410000+00:00,,2016-06-13 00:01:09.240000+00:00,2016-06-13 00:01:09.240000+00:00,,471093.0,,471093.0,13294952,2,127,,
545453,12905427,,"<p><a href=""https://github.com/nodeapps/http-s...",,,19,,2012-10-15 23:27:40.400000+00:00,,2016-06-05 16:27:34.247000+00:00,2016-06-05 16:27:34.247000+00:00,,24874.0,,24874.0,12905426,2,379,,
545454,13326561,,<p>so as H2CO3 already mentioned you can use t...,,,21,,2012-11-10 22:12:49.893000+00:00,,2012-11-10 22:57:10.737000+00:00,2012-11-10 22:57:10.737000+00:00,,892256.0,,1385119.0,13326464,2,3,,
545455,13371886,,<p>It is a simple permutation cipher. Essentia...,,,22,,2012-11-14 01:48:15.130000+00:00,,2012-11-14 20:06:12.873000+00:00,2012-11-14 20:06:12.873000+00:00,,363033.0,,363033.0,13371784,2,4,,
545456,12879395,,"<p>As found <a href=""http://mathworld.wolfram....",,,28,,2012-10-14 04:46:53.387000+00:00,,2012-10-15 12:40:05.570000+00:00,2012-10-15 12:40:05.570000+00:00,,1085062.0,,1085062.0,12877582,2,1,,

In [74]:
# let's drop any answers that do not have corresponding questions in our questions dataframe
tmpid=pd.DataFrame(dfPostQuestionsFiltered['id']) # temporary dataframe to hold ids from questions for merge operation
tmpid.columns=['tempqid']
dfPostAnswersFiltered=pd.merge(dfPostAnswersFiltered, tmpid, how='inner',left_on='parent_id',right_on='tempqid')
del dfPostAnswersFiltered['tempqid']
del tmpid

Index(['id', 'title', 'body', 'accepted_answer_id', 'answer_count',
       'comment_count', 'community_owned_date', 'creation_date',
       'favorite_count', 'last_activity_date', 'last_edit_date',
       'last_editor_display_name', 'last_editor_user_id', 'owner_display_name',
       'owner_user_id', 'parent_id', 'post_type_id', 'score', 'tags',
       'view_count'],
      dtype='object')

In [86]:
np.shape(dfPostAnswersFiltered)

(261052, 21)

In [89]:
# check the answer body of each answer and extract the images references into a separate column as a list
def extract_image_references(body):
    tmp_body=BeautifulSoup(body,"lxml")
    timgs=[]
    for img in tmp_body('img'):
        timgs.append(img)
    return timgs

sttime=time.time()    

dfPostAnswersFiltered['images_list']=''

dfPostAnswersFiltered['images_list'] = dfPostAnswersFiltered['body'].map(extract_image_references)
print('images finished in',(time.time()-sttime)/60,'minutes')

images finished in 4.315905344486237 minutes

In [90]:
# check the answer body of each answer and extract the code snippets into a separate column as a list
def extract_code_snippets(body):
    tmp_body=BeautifulSoup(body,"lxml")
    tcode_snips=[]
    for code in tmp_body('code'):
        tcode_snips.append(code)
    return tcode_snips

sttime=time.time()    

dfPostAnswersFiltered['code_snippets']=''

dfPostAnswersFiltered['code_snippets'] = dfPostAnswersFiltered['body'].map(extract_code_snippets)
print('code snippets finished in',(time.time()-sttime)/60,'minutes')

code snippets finished in 4.729599332809448 minutes

In [91]:
# create a separate 'cleaned_body' column from the answer 'body' column with all code and all html tags removed
def clean_body_text(body):
    tmp_body=BeautifulSoup(body,"lxml")
    for code in tmp_body('code'):
        code.replace_with('')
    tstr=''
    for string in tmp_body.stripped_strings:
        tstr = tstr + ' ' + string
    return tstr

dfPostAnswersFiltered['cleaned_body']=''

sttime=time.time()    
dfPostAnswersFiltered['cleaned_body'] = dfPostAnswersFiltered['body'].map(clean_body_text)
print('body cleaned in',(time.time()-sttime)/60,'minutes')

body cleaned in 4.306883104642233 minutes

In [92]:
dfPostAnswersFiltered['body'].head()

0    <p>The correct syntax is this one:</p>\r\n\r\n...
1    <p>You can download the plugin manually from t...
2    <p>You can define the lines from the dataset w...
3    <p>The way matplotlib is working is that you h...
4    <p>I have figured out the answer, which is to ...
Name: body, dtype: object

In [93]:
dfPostAnswersFiltered['cleaned_body'].head()

0     The correct syntax is this one: It is working...
1     You can download the plugin manually from the...
2     You can define the lines from the dataset wit...
3     The way matplotlib is working is that you hav...
4     I have figured out the answer, which is to us...
Name: cleaned_body, dtype: object

In [98]:
dfPostAnswersFiltered['images_list'].head()

0    []
1    []
2    []
3    []
4    []
Name: images_list, dtype: object

In [95]:
dfPostAnswersFiltered['code_snippets'].head()

0    [<code>plugin install com.graphaware.es/graph-...
1                                                   []
2           [<code>mapping.get(i, "anchor"),
</code>]
3    [<code>def error_plot(ax, title, x_data, y_dat...
4    [<code>%sql select t1.time, t1.value,coalesce(...
Name: code_snippets, dtype: object

In [107]:
# add an image count column to the answers so that we can filter on answers with images
def countimages(image_list):
    if image_list == []:
        return 0
    else:
        return len(image_list)
    
dfPostAnswersFiltered['images_count']=0
dfPostAnswersFiltered['images_count'] = dfPostAnswersFiltered['images_list'].map(countimages)

In [108]:
dfPostAnswersFiltered['images_count'][dfPostAnswersFiltered['images_count'] > 0].head()

12    3
29    1
32    1
35    1
37    3
Name: images_count, dtype: int64

In [109]:
dfPostAnswersFiltered['id'][dfPostAnswersFiltered['images_count'] > 0].count()

45991

In [110]:
# write the dataframe to a tsv
dfPostAnswersFiltered.to_csv("data/stackoverflow/PostAnswersFiltered_V5_parsed.tsv", sep='\t', index=False)

In [4]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST ANSWERS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfPostAnswersFiltered = pd.read_csv("data/stackoverflow/PostAnswersFiltered_V5_parsed.tsv", sep='\t', keep_default_na=False)

In [202]:
dfPostAnswersFiltered

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,...,owner_user_id,parent_id,post_type_id,score,tags,view_count,images_list,code_snippets,cleaned_body,images_count
0,44632276,,<p>The correct syntax is this one:</p>\r\r\n\r...,,,0,,2017-06-19 13:43:45.580000+00:00,,2017-06-19 13:43:45.580000+00:00,...,5222773.0,43895941,2,0,,,[],[<code>plugin install com.graphaware.es/graph-...,The correct syntax is this one: It is working...,0
1,43934125,,<p>You can download the plugin manually from t...,,,13,,2017-05-12 09:28:09.857000+00:00,,2017-05-12 09:28:09.857000+00:00,...,2662355.0,43895941,2,1,,,[],[],You can download the plugin manually from the...,0
2,44632434,,<p>You can define the lines from the dataset w...,,,0,,2017-06-19 13:51:27.790000+00:00,,2017-06-19 13:51:27.790000+00:00,...,3951036.0,44621561,2,0,,,[],"[<code>mapping.get(i, ""anchor""),\r\r\n</code>]",You can define the lines from the dataset wit...,0
3,44633649,,<p>The way matplotlib is working is that you h...,,,0,,2017-06-19 14:47:46.830000+00:00,,2017-06-19 14:47:46.830000+00:00,...,4124317.0,44633422,2,0,,,[],"[<code>def error_plot(ax, title, x_data, y_dat...",The way matplotlib is working is that you hav...,0
4,44633675,,"<p>I have figured out the answer, which is to ...",,,0,,2017-06-19 14:48:42.900000+00:00,,2017-06-19 14:48:42.900000+00:00,...,8050923.0,44624707,2,0,,,[],"[<code>%sql select t1.time, t1.value,coalesce(...","I have figured out the answer, which is to us...",0
5,44635048,,<p>To further a_guest answer - To enable see t...,,,0,,2017-06-19 15:56:06.457000+00:00,,2017-06-19 15:56:06.457000+00:00,...,1704227.0,44632018,2,0,,,[],[],To further a_guest answer - To enable see the...,0
6,44632901,,<p>The problem is that the Python process fini...,,,3,,2017-06-19 14:12:13.690000+00:00,,2017-06-19 14:12:13.690000+00:00,...,3767239.0,44632018,2,2,,,[],"[<code>for</code>, <code>-i</code>, <code>pyth...",The problem is that the Python process finish...,0
7,49985313,,<p>You can keep the window open by creating a ...,,,0,,2018-04-23 15:59:00.010000+00:00,,2018-04-23 15:59:00.010000+00:00,...,6605826.0,44632018,2,1,,,[],"[<code>QApplication</code>, <code>exec_()</cod...",You can keep the window open by creating a at...,0
8,44636285,,<p>Since you've mentioned that the transformat...,,,0,,2017-06-19 17:10:08.570000+00:00,,2017-06-19 17:10:08.570000+00:00,...,8060278.0,18506201,2,0,,,[],[<code>lambda=3.79\r\r\nm2=lm(resp^((lambda-1)...,Since you've mentioned that the transformatio...,0
9,18507004,,"<pre><code>plotexpl &lt;- seq(1,4,length.out=1...",,,3,,2013-08-29 09:24:47.800000+00:00,,2013-08-29 09:24:47.800000+00:00,...,1412059.0,18506201,2,2,,,[],"[<code>plotexpl &lt;- seq(1,4,length.out=10)\r...",I won't discuss the statistical issues here (...,0
10,44636462,,<p>What range/data is selected at the time the...,,,0,,2017-06-19 17:22:09.553000+00:00,,2017-06-19 17:22:09.553000+00:00,...,478884.0,44632742,2,0,,,[],"[<code>Sub make_chart(Fam, Data, Row_Start)\r\...",What range/data is selected at the time the c...,0
11,44637233,,<blockquote>\r\r\n <p>other times they genera...,,,0,,2017-06-19 18:10:38.517000+00:00,,2017-06-19 18:17:44.853000+00:00,...,4926357.0,44632742,2,0,,,[],"[<code>region</code>, <code>ChartArea.Clear</c...",other times they generate with both series an...,0
12,44637579,,<p>Well I did this by simply copy the texture ...,,,0,,2017-06-19 18:31:54.673000+00:00,,2017-06-19 21:09:34.603000+00:00,...,2521214.0,44619304,2,0,,,"[<img alt=""rendered sprite"" src=""https://i.sta...",[<code>// [constants]\r\r\nconst int sxs=128; ...,Well I did this by simply copy the texture pi...,3
13,44659255,,<p>Big thanks to Spektre for all the effort he...,,,0,,2017-06-20 17:11:16.137000+00:00,,2017-06-20 17:16:50.187000+00:00,...,8125567.0,44619304,2,1,,,[],[<code>import pygame\r\r\n\r\r\nfrom pygame.lo...,Big thanks to Spektre for all the effort he m...,0
14,44638617,,<p>You don't appear to be using <code>mlt.text...,,,0,,2017-06-19 19:39:24.230000+00:00,,2017-06-19 19:39:24.230000+00:00,...,5548599.0,44638406,2,0,,,[],"[<code>mlt.text()</code>, <code>text()</code>,...",You don't appear to be using correctly. See t...,0
15,44639041,,<p>Python turtle was designed to either be emb...,,,0,,2017-06-19 20:06:46.950000+00:00,,2017-06-19 20:06:46.950000+00:00,...,5771269.0,44634947,2,0,,,[],[<code>from random import randint\r\r\nfrom tk...,Python turtle was designed to either be embed...,0
16,44642203,,"<p>thank you for your attention, i did solve i...",,,0,,2017-06-20 01:07:20.283000+00:00,,2017-06-20 01:07:20.283000+00:00,...,3341452.0,44555246,2,0,,,[],[],"thank you for your attention, i did solve it ...",0
17,44645398,,<p>I spent whole day implementing it. My main ...,,,0,,2017-06-20 06:28:56.110000+00:00,,2017-06-20 06:28:56.110000+00:00,...,1328863.0,10042786,2,0,,,[],[],I spent whole day implementing it. My main cr...,0
18,45014838,,"<p>This may be a bit late for the OP, but ther...",,,0,,2017-07-10 14:33:11.160000+00:00,,2017-07-10 14:33:11.160000+00:00,...,400086.0,10042786,2,1,,,[],[],"This may be a bit late for the OP, but there ...",0
19,25093272,,"<p>This answer I found on <a href=""https://dev...",,,6,,2014-08-02 08:44:30.170000+00:00,,2015-02-26 19:09:50.390000+00:00,...,2474507.0,10042786,2,32,,,[],"[<code>&lt;meta prefix=""og: http://ogp.me/ns#""...",This answer I found on LinkedIn forums might ...,0
20,46641594,,<p>I found this simple fix which worked for me...,,,1,,2017-10-09 08:10:02.483000+00:00,,2017-10-09 08:10:02.483000+00:00,...,8744596.0,10042786,2,7,,,[],[],I found this simple fix which worked for me a...,0
21,11331967,,"<p>Have you tried adding <code>prefix=""og: htt...",,,0,,2012-07-04 15:30:15.607000+00:00,,2015-02-26 19:08:48.440000+00:00,...,217696.0,10042786,2,9,,,[],"[<code>prefix=""og: http://ogp.me/ns#""</code>]",Have you tried adding to the HTML tag?,0
22,49939696,,<p>LinkedIn is also caching previews. If OpenG...,,,1,,2018-04-20 10:35:07.057000+00:00,,2018-04-20 10:35:07.057000+00:00,...,1373324.0,10042786,2,4,,,[],[<code>https://your-website.com/?1</code>],LinkedIn is also caching previews. If OpenGra...,0
23,51800092,,<p>I was having the same issue last night. Sp...,,,0,,2018-08-11 13:22:53.443000+00:00,,2018-08-11 13:22:53.443000+00:00,...,8773858.0,10042786,2,5,,,[],[],I was having the same issue last night. Spen...,0
24,48477331,,"<p>If @Kym's answer works for you, and you don...",,,0,,2018-01-27 15:31:20.270000+00:00,,2018-01-27 15:31:20.270000+00:00,...,8126852.0,10042786,2,1,,,[],[],"If @Kym's answer works for you, and you don't...",0
25,53300213,,<p>For me solution was to put all the <code>&l...,,,0,,2018-11-14 12:25:43.090000+00:00,,2018-11-14 12:25:43.090000+00:00,...,2884309.0,10042786,2,0,,,[],"[<code>&lt;meta&gt;</code>, <code>prefix</code...",For me solution was to put all the tags (with...,0
26,54845243,,<p>In my case I did exactly this and it worked...,,,0,,2019-02-23 19:18:01.307000+00:00,,2019-02-23 19:28:46.050000+00:00,...,9061422.0,10042786,2,0,,,[],[<code>&lt;title&gt; aanalytics &lt;/title&gt;...,In my case I did exactly this and it worked f...,0
27,55107387,,"<p>I ran into this recently, spent a huge amou...",,,1,,2019-03-11 17:32:54.687000+00:00,,2019-03-11 17:32:54.687000+00:00,...,2989397.0,10042786,2,1,,,[],[],"I ran into this recently, spent a huge amount...",0
28,44647485,,<p>It seems that the arguments <code>color</co...,,,0,,2017-06-20 08:14:17.367000+00:00,,2017-06-20 09:54:11.427000+00:00,...,4366229.0,32895876,2,0,,,[],"[<code>color</code>, <code>alpha</code>, <code...",It seems that the arguments and need to be pa...,0
29,32901506,,"<p>In your case, you do not need to put a <cod...",,,1,,2015-10-02 06:15:43.853000+00:00,,2015-10-02 06:22:00.093000+00:00,...,3482528.0,32895876,2,0,,,"[<img alt=""enter image description here"" src=""...","[<code>where</code>, <code>time</code>, <code>...","In your case, you do not need to put a condit...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261022,13149393,,<p>You have a <code>&lt;noscript&gt;</code> t...,,,8,,2012-10-31 00:06:50.140000+00:00,,2012-10-31 00:06:50.140000+00:00,...,21062.0,13149307,2,2,,,[],[<code>&lt;noscript&gt;</code>],You have a tag in the head section which is i...,0
261023,12809687,,<p>I'd suggest storing the whole polygon as a ...,,,8,,2012-10-09 23:06:19.287000+00:00,,2012-10-10 02:00:12.453000+00:00,...,568209.0,12809201,2,3,,,[],[<code>use tempdb;\r\r\ncreate table tally (i ...,I'd suggest storing the whole polygon as a ge...,0
261024,13125690,,<p>Given that the intersection of the lines ar...,,,8,,2012-10-29 16:25:44.937000+00:00,,2012-10-30 15:24:23.830000+00:00,...,33727.0,13123665,2,3,,,[],"[<code>{\r\r\n name: 'line1',\r\r\n ...",Given that the intersection of the lines are ...,0
261025,13109376,,<p>Not sure I understand your question entirel...,,,8,,2012-10-28 13:56:22.637000+00:00,,2012-10-28 13:56:22.637000+00:00,...,391554.0,13109151,2,5,,,[],"[<code>XYMultipleSeriesRenderer</code>, <code>...","Not sure I understand your question entirely,...",0
261026,12769870,,"<p>Text objects have an <a href=""http://www.ma...",,,8,,2012-10-07 14:57:04.850000+00:00,,2012-10-07 14:57:04.850000+00:00,...,97160.0,12769822,2,6,,,[],"[<code>[left,bottom,width,height]\r\r\n</code>]","Text objects have an ""Extent"" property: Exten...",0
261027,12804556,,<p>Something like this might work. I've moved...,,,9,,2012-10-09 16:38:00.577000+00:00,,2012-10-09 17:48:37.090000+00:00,...,527096.0,12804394,2,1,,,[],"[<code>FB.getLoginStatus</code>, <code>callBac...",Something like this might work. I've moved t...,0
261028,12971735,,"<p>As you can see from JSON, location is not a...",,,9,,2012-10-19 09:55:02.090000+00:00,,2012-10-19 09:55:02.090000+00:00,...,521347.0,12971702,2,1,,,[],[],"As you can see from JSON, location is not a J...",0
261029,13021876,,<p>The binning is quite easy if you have pytho...,,,9,,2012-10-23 00:15:35.710000+00:00,,2012-10-23 13:06:27.283000+00:00,...,748858.0,13017130,2,2,,,[],[<code>#Call this script as:\r\r\n#python this...,The binning is quite easy if you have python ...,0
261030,13301919,,<p>Do you want something like:</p>\r\r\n\r\r\n...,,,9,,2012-11-09 04:00:07.457000+00:00,,2012-11-09 05:03:00.603000+00:00,...,748858.0,13301671,2,2,,,[],[<code>plot 'datafile' u 2:3:1 with labels\r\r...,Do you want something like: ... I'm not reall...,0
261031,13209424,,<p>It works if you create <code>arcTween</code...,,,9,,2012-11-03 12:58:12.530000+00:00,,2012-11-03 12:58:12.530000+00:00,...,1172002.0,13208875,2,8,,,[],[<code>arcTween</code>],It works if you create inline and add an inte...,0
261032,12999223,,"<p>Seeing as this seems homework, I'm not goin...",,,10,,2012-10-21 15:29:14.737000+00:00,,2012-10-21 15:29:14.737000+00:00,...,1661362.0,12995730,2,1,,,[],[],"Seeing as this seems homework, I'm not going ...",0
261033,13295386,,"<p><a href=""http://schemas.opengis.net/kml/2.2...",,,10,,2012-11-08 18:27:58.810000+00:00,,2012-11-08 18:27:58.810000+00:00,...,407651.0,13262605,2,1,,,[],[<code>&lt;!-- import atom:author and atom:lin...,ogckml22.xsd imports two other schema documen...,0
261034,12822764,,<p>Some clarifications:</p>\r\r\n\r\r\n<ul>\r\...,,,10,,2012-10-10 15:14:53.427000+00:00,,2012-10-10 18:01:21.383000+00:00,...,321505.0,12802423,2,2,,,[],"[<code>/me/accounts</code>, <code>manage_pages...",Some clarifications: A #200 error is a permis...,0
261035,13136890,,<p>There are many Python alternatives.</p>\r\r...,,,10,,2012-10-30 10:18:30.620000+00:00,,2012-11-02 09:14:01.133000+00:00,...,1256394.0,13136247,2,9,,,[],"[<code>from seqdiag import parser, builder, dr...",There are many Python alternatives. If you wa...,0
261036,13136482,,<p>There are several perl modules which do thi...,,,12,,2012-10-30 09:55:53.720000+00:00,,2012-10-30 09:55:53.720000+00:00,...,784338.0,13136247,2,2,,,[],[<code>use UML::State;\r\r\n\r\r\nmy $diagram ...,There are several perl modules which do this ...,0
261037,13150000,,"<p>I will give an answer in two acts, using tw...",,,10,,2012-10-31 01:25:00.933000+00:00,,2015-04-02 21:28:55.573000+00:00,...,1281879.0,13148835,2,12,,,"[<img alt=""enter image description here"" src=""...",[<code>#!/usr/bin/python\r\r\n\r\r\nimport Ima...,"I will give an answer in two acts, using two ...",1
261038,12980958,,"<p>The answer would be ""3"", since you want to ...",,,11,,2012-10-19 19:15:41.833000+00:00,,2012-10-19 19:27:49.987000+00:00,...,1080891.0,12980822,2,2,,,[],[],"The answer would be ""3"", since you want to st...",0
261039,13083454,,"<p>At the beginning, just set the needed maxim...",,,11,,2012-10-26 08:32:05.813000+00:00,,2012-10-26 09:57:17.630000+00:00,...,391554.0,13082889,2,2,,,[],"[<code>renderer.setXLabels(20);\r\r\n</code>, ...","At the beginning, just set the needed maximum...",0
261040,12775087,,"<p>As Ben suggested, <code>cairo_pdf()</code> ...",,,11,,2012-10-08 03:53:06.130000+00:00,,2012-10-18 17:54:26.193000+00:00,...,1664024.0,12768176,2,21,,,"[<img alt=""ggplot2 graph with custom font fami...","[<code>cairo_pdf()</code>, <code>family</code>...","As Ben suggested, is your friend. It also al...",1
261041,13316126,,"<p>If I remember right, there were questions o...",,,11,,2012-11-09 21:14:56.727000+00:00,,2013-06-01 15:04:22.360000+00:00,...,1320535.0,13297155,2,61,,,"[<img alt=""enter image description here"" src=""...","[<code>print.ggplot</code>, <code>getAnywhere(...","If I remember right, there were questions on ...",2
261042,12769698,,"<p>Regarding (1): </p>\r\r\n\r\r\n<p>First, wh...",,,12,,2012-10-07 14:31:27.737000+00:00,,2012-10-10 18:50:50.510000+00:00,...,1219295.0,12769353,2,3,,,[],"[<code>pnpoly</code>, <code>points_inside_poly...","Regarding (1): First, why are you using chunk...",0
261043,12940339,,<p>Using <code>preg_match_all</code> with more...,,,12,,2012-10-17 17:52:58.163000+00:00,,2012-10-18 01:51:51.523000+00:00,...,875362.0,12939909,2,3,,,[],"[<code>preg_match_all</code>, <code>$image[n]<...",Using with more than one subpattern in the re...,0
261044,13042922,,<p>It would be to your advantage to have a rea...,,,12,,2012-10-24 04:11:58.110000+00:00,,2012-10-24 04:11:58.110000+00:00,...,992484.0,13042778,2,3,,,[],[],It would be to your advantage to have a read ...,0
261045,12763851,,"<p>the grid is a 35-bit number, so you can sto...",,,13,,2012-10-06 21:02:57.263000+00:00,,2012-10-06 21:02:57.263000+00:00,...,235354.0,12763838,2,1,,,[],[],"the grid is a 35-bit number, so you can store...",0
261046,13293635,,<p>When you are creating your Open Graph custo...,,,13,,2012-11-08 16:46:57.157000+00:00,,2012-11-09 11:05:09.323000+00:00,...,850947.0,13292346,2,1,,,"[<img alt=""https://developers.facebook.com/att...",[],When you are creating your Open Graph custom ...,1
261047,13138254,,<h1>First example</h1>\r\r\n\r\r\n<p>In the fo...,,,13,,2012-10-30 11:43:22.100000+00:00,,2012-10-30 13:42:52.667000+00:00,...,1468366.0,13137761,2,5,,,[],"[<code>d</code>, <code>s &lt; t</code>, <code>...","First example In the following notation, I us...",0
261048,13314421,,<p>There are a few possible solutions to this:...,,,14,,2012-11-09 19:11:37.557000+00:00,,2012-11-09 22:02:16.970000+00:00,...,1336150.0,13314368,2,6,,,[],"[<code>set(gcf, 'Position', get(0, 'ScreenSize...",There are a few possible solutions to this: R...,0
261049,12924191,,"<p>You should use the <a href=""http://www.open...",,,16,,2012-10-16 22:06:12.517000+00:00,,2012-10-17 05:34:32.353000+00:00,...,1736304.0,12909102,2,1,,,[],[],You should use the PKCS7_verify function to v...,0
261050,12867283,,<p>If you can make the same call via the Graph...,,,16,,2012-10-12 21:22:03.470000+00:00,,2012-10-12 21:22:03.470000+00:00,...,321505.0,12867108,2,2,,,[],"[<code>page/id</code>, <code>try {\r\r\n $f...",If you can make the same call via the Graph A...,0
261051,12809902,,<p>You can restrict the data returned by faceb...,,,17,,2012-10-09 23:32:29.333000+00:00,,2013-05-26 10:55:17.287000+00:00,...,828705.0,12809224,2,3,,,[],"[<code>since</code>, <code>since</code>, <code...",You can restrict the data returned by faceboo...,0

In [13]:
# retrieving user ids for owners of the answers retrieved above

sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.users` WHERE id IN
    (SELECT owner_user_id FROM `bigquery-public-data.stackoverflow.posts_answers` WHERE parent_id IN 
        (SELECT id FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%plot%' 
            OR tags LIKE '%graph%'
            OR tags LIKE '%chart%'
            OR tags LIKE '%visualiz%'
            OR tags LIKE '%choropleth%'
            OR tags LIKE '%drawing%'
            OR tags LIKE '%line%'
            OR tags LIKE '%geospatial%'
            OR tags LIKE '%diagram%')))
"""
dfUsersFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [49]:
np.shape(dfUsersFiltered)

(304366, 13)

In [50]:
dfUsersFiltered

,id,display_name,about_me,age,creation_date,last_access_date,location,reputation,up_votes,down_votes,views,profile_image_url,website_url
0,1228,Will,<p>Downvoted a post? Want to let the author kn...,None,2008-08-13 13:58:55.613000+00:00,2019-08-30 19:32:14.180000+00:00,United States,114479,4072,8499,61068,None,https://idownvotedbecau.se
1,2009,hometoast,<p>(your about me is currently blank)</p>,None,2008-08-19 19:16:03.210000+00:00,2019-08-29 14:39:17.043000+00:00,"Mountain Top, PA",9604,1400,72,892,None,http://devtoast.com
2,2684,Martin Marconcini,<p>I do Android development with Kotlin/Java a...,None,2008-08-24 14:38:27.090000+00:00,2019-08-31 20:36:33.830000+00:00,"Almere, NL",17343,2555,159,5171,https://i.stack.imgur.com/Z9oZ0.jpg?s=128&g=1,https://professorneurus.wordpress.com
3,5049,macbirdie,"<p>Freelancer, doing primarily iOS development...",None,2008-09-07 15:03:23.483000+00:00,2019-08-27 14:14:57.663000+00:00,"Poznan, Poland",14626,344,49,3603,None,https://macbirdie.net
4,6651,Alex Angas,None,None,2008-09-15 12:25:40.173000+00:00,2019-08-30 16:49:12.890000+00:00,"London, United Kingdom",35087,3339,271,3365,None,https://alexangas.com
5,8562,mdb,None,None,2008-09-15 16:20:52.917000+00:00,2017-11-14 13:45:05.013000+00:00,Netherlands,45600,1084,65,1841,None,None
6,8912,Ted Naleid,None,None,2008-09-15 17:12:19.533000+00:00,2019-08-29 13:28:19.343000+00:00,United States,22733,1251,26,1292,None,http://naleid.com/
7,9936,Martin Cote,<p>Graphics Engineer at Unity3D.</p>,None,2008-09-15 20:30:09.543000+00:00,2019-08-23 18:37:35.430000+00:00,"Montreal, Canada",22119,316,72,1305,None,None
8,13820,Sridhar Iyer,Wired and Weird,None,2008-09-16 20:57:40.933000+00:00,2019-08-30 19:03:38.590000+00:00,"Santa Clara, CA",2021,176,22,687,None,http://sridharv.net
9,17413,Nifle,<p><code>A rather lazy sysadmin and sometimes ...,None,2008-09-18 08:34:03.827000+00:00,2019-08-30 12:50:59.610000+00:00,Sweden,8624,2964,422,1470,None,http://www.kiva.org/
10,24806,Simon Howard,None,None,2008-10-03 12:31:23.757000+00:00,2019-08-31 20:38:51.360000+00:00,None,8384,237,124,835,None,https://soulsphere.org/
11,26877,JJS,<p>Software developer specializing in Microsof...,None,2008-10-10 16:02:08.603000+00:00,2019-08-30 15:04:15.380000+00:00,United States,4465,731,28,395,None,http://jeremysimmons.net/
12,28736,chilltemp,None,None,2008-10-16 21:19:31.893000+00:00,2019-08-30 16:51:10.843000+00:00,"Baltimore, MD",5688,1153,52,309,None,None
13,38210,Colwin,None,None,2008-11-17 11:31:20.333000+00:00,2019-08-31 17:28:34.263000+00:00,"Pune, Maharashtra, India",2083,132,86,232,https://i.stack.imgur.com/Gteee.jpg,None
14,42921,Eamon Nerbonne,<p>My work and hobby concern programming: I'm ...,None,2008-12-03 17:44:54.473000+00:00,2019-08-20 09:38:59.263000+00:00,"Groningen, The Netherlands",36329,1632,112,2392,None,http://eamon.nerbonne.org/
15,43677,bezmax,<p>Maksim Bezsažnyj is an ambitious software d...,None,2008-12-05 15:24:24.503000+00:00,2019-08-31 19:29:51.780000+00:00,"Toronto, ON, Canada",20183,937,389,1104,None,http://bezmax.com/
16,43832,Tom Harrington,<p>I am no longer actively answering questions...,None,2008-12-05 22:19:06.867000+00:00,2019-06-21 17:45:33.870000+00:00,"Colorado, USA",55299,403,57,4659,None,http://www.atomicbird.com/
17,53543,Crashworks,<p>Eleven milliseconds or bust.</p>,None,2009-01-09 21:59:47.787000+00:00,2019-08-30 21:57:22.703000+00:00,None,33150,1404,145,3670,None,http://assemblyrequired.crashworks.org
18,60117,ajma,<p>TODO</p>,None,2009-01-29 08:46:51.833000+00:00,2018-03-10 20:09:05.410000+00:00,"Redmond, WA, United States",8688,385,27,1172,None,http://www.andrewma.com
19,64626,Suroot,<p>I'm a big fan of C/C++/C#/VHDL and moreover...,None,2009-02-10 15:47:50.950000+00:00,2014-06-04 19:27:15.333000+00:00,"Myrtle Beach, SC",3811,122,33,614,None,http://imacodemonkey.blogspot.com/
20,70365,CiscoIPPhone,None,None,2009-02-24 13:41:50.780000+00:00,2019-08-30 17:22:47.863000+00:00,United Kingdom,8486,570,142,773,None,None
21,77047,Chris Tonkinson,None,None,2009-03-12 04:38:30.627000+00:00,2019-08-22 01:38:58+00:00,United States,8037,923,36,794,None,https://chris.tonkinson.com/
22,101130,WizKid,<p>Software Engineer at Facebook. Mostly codin...,None,2009-05-04 20:30:20.957000+00:00,2019-09-01 05:18:08.343000+00:00,"San Francisco, CA",4562,308,345,5128,https://graph.facebook.com/690267162/picture?t...,http://extensions.hesslow.se
23,108009,Stefan,"<p>I like code, beer, rock climbing and travel...",None,2009-05-15 23:48:05.510000+00:00,2019-03-03 20:17:00+00:00,"Würzburg, Germany",4249,224,38,379,None,http://slieb.org
24,113608,Pablo Albornoz,<p>Still (always?) learning. Working on Django...,None,2009-05-28 08:40:39.473000+00:00,2019-08-31 05:56:31.503000+00:00,"Santiago, Chile",4753,145,39,474,None,http://fixmycode.me
25,115833,BjoernD,<p>I'm a software development engineer at Amaz...,None,2009-06-02 07:49:04.133000+00:00,2019-08-28 08:06:47.883000+00:00,"Dresden, Germany",4081,713,23,462,None,http://tudos.org/~doebel
26,132509,Alec Gorge,None,None,2009-05-27 15:13:57.260000+00:00,2019-08-29 21:40:33.143000+00:00,Indiana,12294,486,28,1605,None,http://alecgorge.com
27,139855,legalize,<p>I was a Direct3D Microsoft MVP for 10 years...,None,2009-07-17 01:22:50.773000+00:00,2019-08-22 23:36:17.257000+00:00,"Salt Lake City, UT",1786,197,54,274,None,http://legalizeadulthood.wordpress.com
28,148381,DaveJohnston,<p>Hello</p>,None,2009-07-31 09:15:19.333000+00:00,2019-08-31 12:35:26.970000+00:00,"Glasgow, United Kingdom",7716,509,158,792,None,http://www.dajohnston.co.uk
29,163961,Nettogrof,"<p>A real Geek: programming(mostly in Java), g...",None,2009-08-27 04:45:41.967000+00:00,2019-08-01 15:01:40.453000+00:00,"Montreal, Canada",1967,376,65,180,None,http://suicidechess.ca
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304336,823441,Brian Hoover,"<p>Architect, teacher, programmer, technical l...",None,2011-06-30 16:33:15.573000+00:00,2019-08-30 21:56:54.283000+00:00,"San Francisco, CA",7172,412,18,582,https://i.stack.imgur.com/DiLa3.jpg?s=128&g=1,http://bhoover10001.github.io/
304337,1007887,efwjames,"<p>UX, UI, Design, HTML5, CSS3, Javascript, An...",None,2011-10-21 21:30:11.543000+00:00,2019-08-23 17:14:49.173000+00:00,"Washington, DC, United States",779,449,18,273,https://i.stack.imgur.com/nD1UB.png?s=128&g=1,http://efwjames.com
304338,1313169,Nicolas Garnier,"<p><a href=""https://plus.google.com/1086357523...",None,2012-04-04 14:56:48.837000+00:00,2019-08-29 10:22:05.867000+00:00,"Zurich, Switzerland",10033,214,18,2208,None,http://developers.google.com
304339,2545042,Sam,"<p>A self-taught, skilled, highly motivated an...",None,2013-07-03 04:51:34.023000+00:00,2019-08-29 09:44:02.923000+00:00,Australia,2704,86,18,228,https://i.stack.imgur.com/cnFsg.png?s=128&g=1,None
304340,3027706,webomjaipur,<p>​​<strong>Career Summary</strong></p>\n\n<u...,None,2013-11-24 16:39:42.897000+00:00,2019-08-31 15:06:46.003000+00:00,India,1180,1215,18,262,https://i.stack.imgur.com/KBin5.jpg?s=128&g=1,None
304341,3894119,Andy Aldo,None,None,2014-07-31 04:40:31.883000+00:00,2019-08-25 09:21:04.743000+00:00,Kuala Lumpur Federal Territory of Kuala Lumpur...,745,351,18,43,https://www.gravatar.com/avatar/fbc11920a94562...,None
304342,4783262,pablito.aven,None,None,2015-04-13 14:06:07.527000+00:00,2019-08-30 21:11:11.790000+00:00,None,858,80,18,93,https://www.gravatar.com/avatar/f7c8a23702207a...,None
304343,10784,Robert Wagner,None,None,2008-09-16 01:50:35.340000+00:00,2019-08-28 22:02:50.297000+00:00,None,13292,354,18,818,None,None
304344,699385,Danny,"<p>Bioinformatician, data scientists, statisti...",None,2011-04-08 21:33:53.863000+00:00,2019-08-30 18:21:56.693000+00:00,None,1150,325,18,59,https://i.stack.imgur.com/mPKIY.jpg?s=128&g=1,None
304345,875321,Anthony Alberto,"<ul>\n<li>My twitter : <a href=""https://twitte...",None,2011-08-02 19:13:33.873000+00:00,2018-08-13 13:24:56.917000+00:00,"Montreal, Canada",9599,163,18,421,None,https://github.com/anthonyalberto
304346,2620293,Timtech,None,None,2013-07-25 19:55:54.657000+00:00,2019-08-16 20:31:01.020000+00:00,"Virginia, United States",1011,848,18,158,None,http://timtechsoftware.com
304347,3626659,Alupotha,<p>I love technologies.. that's all :)</p>,None,2014-05-11 23:20:10.053000+00:00,2019-09-01 02:36:56.307000+00:00,"Kandy, Sri Lanka",6314,573,18,441,None,http://securehttp.blogspot.com
304348,4630491,Max,None,None,2015-03-04 04:24:48.860000+00:00,2019-08-19 13:49:21.613000+00:00,"Tampa, FL, United States",861,503,18,196,https://lh5.googleusercontent.com/-tTs9nCNmnRI...,None
304349,168610,davbryn,<p>iPhone developer\nC++ Programmer</p>,None,2009-09-04 15:51:32.770000+00:00,2019-08-30 15:53:55.650000+00:00,United Kingdom,6645,50,18,275,https://i.stack.imgur.com/JGCpk.png,http://n/a
304350,250540,BarsMonster,"<p>Software/Hardware geek (C++, FPGA/Verilog, ...",None,2010-01-14 08:06:02.567000+00:00,2019-08-23 16:52:31.607000+00:00,Russia,4911,112,18,938,None,http://3.14.by
304351,364843,buckbova,None,None,2010-06-11 18:38:40.983000+00:00,2014-02-15 20:31:07.280000+00:00,None,1209,56,18,63,None,None
304352,1300012,JimmyRare,<p>I'm a frontend developer working mostly wit...,None,2012-03-29 06:35:03.967000+00:00,2019-08-30 18:20:24.840000+00:00,"Norrköping, Sweden",3391,254,18,172,https://i.stack.imgur.com/5aSjA.jpg,None
304353,5175942,MacroMarc,None,None,2015-07-31 01:10:11.177000+00:00,2019-08-27 14:28:07.217000+00:00,"London, United Kingdom",2847,112,18,457,https://i.stack.imgur.com/MiN2o.jpg,None
304354,10070647,Twenty,<p>Coding in C# is my passion.</p>,None,2018-07-12 12:36:55.453000+00:00,2019-08-31 09:52:46.487000+00:00,Austria,704,79,18,112,https://i.stack.imgur.com/gR676.png?s=128&g=1,https://twenty-four.dev
304355,10761855,Vadim Hulevich,<p>My experience with technologies:</p>\n\n<p>...,None,2018-12-07 21:24:20.067000+00:00,2019-08-30 14:19:15.607000+00:00,Belarus,1281,47,18,133,https://www.gravatar.com/avatar/f922c17d0f8748...,None
304356,11129768,pavelbere,"<p>20 Years old developer, working at WiBeats ...",None,2019-02-28 09:21:36.263000+00:00,2019-08-29 17:56:59.463000+00:00,"Alessandria, AL, Italy",615,330,18,40,https://graph.facebook.com/587398841642371/pic...,None
304357,12916,Jesse Glick,None,None,2008-09-16 16:13:54.640000+00:00,2019-08-30 18:28:19.163000+00:00,"Chapel Hill, NC, United States",17899,932,18,2880,None,None
304358,116932,pagid,"<p>Web addict, former TYPO3 Core member, Ruby,...",None,2009-06-03 21:56:38.407000+00:00,2019-05-09 21:13:30.870000+00:00,Germany,7324,622,18,483,None,None
304359,1156452,thatjeffsmith,<p>I aim to make Oracle Database easier to use...,None,2012-01-18 14:37:43.323000+00:00,2019-08-31 21:26:44.870000+00:00,"Cary, NC",9765,273,18,2036,https://i.stack.imgur.com/okUnm.jpg?s=128&g=1,https://www.thatjeffsmith.com
304360,1326107,MSA,None,None,2012-04-11 08:46:37.760000+00:00,2019-08-30 15:31:27.750000+00:00,None,2016,205,18,390,https://i.stack.imgur.com/OU1Tr.jpg?s=128&g=1,None
304361,1856916,WalkingRandomly,<p>I love mathematics and mathematical softwar...,None,2008-09-16 08:50:34.643000+00:00,2019-08-30 10:23:15.483000+00:00,United Kingdom,2951,285,18,311,None,http://www.walkingrandomly.com
304362,2644224,Sickest,<p>me</p>,None,2013-08-02 01:39:43.053000+00:00,2019-08-20 03:15:24.977000+00:00,"California, United States",919,121,18,143,https://www.gravatar.com/avatar/07b2dd8714ad33...,None
304363,3336780,Riaan van Zyl,<p>Full-time Microsoft Developer.</p>\n\n<p>Ho...,None,2014-02-21 10:34:44.503000+00:00,2019-08-28 14:16:51.563000+00:00,South Africa,161,174,18,71,https://i.stack.imgur.com/subRJ.jpg,None
304364,3615207,stinger,<p>I love computer stuff and death metal bands...,None,2014-05-08 07:00:05.340000+00:00,2019-08-30 13:01:34.707000+00:00,"Minsk, Belarus",1811,160,18,130,https://i.stack.imgur.com/h8aNr.jpg?s=128&g=1,None
304365,10455554,user10455554,None,None,2018-10-04 08:42:59.053000+00:00,2019-08-30 09:14:27.540000+00:00,None,188,332,18,8,https://www.gravatar.com/avatar/106fd5da93a896...,None

In [51]:
# write the dataframe to a tsv
dfUsersFiltered.to_csv("data/stackoverflow/UsersFiltered_V3.tsv", sep='\t')

In [4]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW USERS FOR ABOVE ANSWERS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfUsersFiltered = pd.read_csv("data/stackoverflow/UsersFiltered_V3.tsv", sep='\t')

In [15]:
# retrieving the comments that belong to the questions retrieved above

# NOTE - the below select may only retrieve comments related to questions??

# is a separate select needed to retrieve comments related to the answers?

sql = """
SELECT * FROM `bigquery-public-data.stackoverflow.comments` WHERE post_id IN 
    (SELECT id FROM `bigquery-public-data.stackoverflow.posts_questions` WHERE (tags LIKE '%plot%' 
        OR tags LIKE '%graph%'
        OR tags LIKE '%chart%'
        OR tags LIKE '%visualiz%'
        OR tags LIKE '%choropleth%'
        OR tags LIKE '%drawing%'
        OR tags LIKE '%line%'
        OR tags LIKE '%geospatial%'
        OR tags LIKE '%diagram%'))
"""
dfCommentsFiltered = pandas_gbq.read_gbq(sql, project_id=project_id)

In [16]:
np.shape(dfCommentsFiltered)

(1184056, 7)

In [17]:
dfCommentsFiltered

,id,text,creation_date,post_id,user_id,user_display_name,score
0,41452359,SOLVED! Check this https://github.com/ikimuhen...,2014-10-16 09:50:36.890000+00:00,26350205,1833505.0,None,4
1,41453409,You also get this problem when you restore a b...,2014-10-16 10:23:14.340000+00:00,2043382,10245.0,None,4
2,41464240,"Do you think `-12.80010128657071, 1121.2874782...",2014-10-16 15:09:57.510000+00:00,22773651,1238965.0,None,4
3,41472601,Pretty much all encryption algorithms are goin...,2014-10-16 19:27:46.807000+00:00,26412089,869736.0,None,4
4,41473301,Surely F(S) = 9999 is not what you're looking ...,2014-10-16 19:48:05.153000+00:00,26412312,2144669.0,None,4
5,41474727,"""We are not allowed to do any changes with res...",2014-10-16 20:32:31.033000+00:00,26413343,1274820.0,None,4
6,41490904,I think that kind of question is better to ask...,2014-10-17 10:13:03.323000+00:00,26419181,1451635.0,None,4
7,41499177,The jqChart plugin isn't loaded... check your ...,2014-10-17 14:23:53.250000+00:00,26427123,1686485.0,None,5
8,41503605,Hmmm... it looks like you are cancelling the e...,2014-10-17 16:22:45.360000+00:00,26429055,2718864.0,None,5
9,41568509,This question appears to be off-topic because ...,2014-10-20 12:06:44.173000+00:00,26462355,47961.0,None,4
10,41586943,Been a little while since I had a copy of matl...,2014-10-20 20:57:08.917000+00:00,26474634,2715819.0,None,5
11,41598809,ideally you would store the image on disk and ...,2014-10-21 07:55:03.007000+00:00,26480557,2662355.0,None,4
12,41604851,"`fgets(string, 1000, ptr_file)` must be `fgets...",2014-10-21 11:08:33.440000+00:00,26485204,1606345.0,None,4
13,41616556,This question appears to be off-topic because ...,2014-10-21 16:15:51.790000+00:00,26491162,18017.0,None,7
14,41619711,"Does `str_replace(""ÿþ"", """", $trackartist1);` w...",2014-10-21 17:52:05.503000+00:00,26493053,660921.0,None,4
15,41622763,reproducible example please?,2014-10-21 19:29:54.840000+00:00,26494643,190277.0,None,5
16,41622887,"Just take a subset of the data, see `?[` or `?...",2014-10-21 19:33:40.313000+00:00,26494643,1033808.0,None,4
17,41626141,This question appears to be off-topic because ...,2014-10-21 21:19:49.203000+00:00,26496476,2422776.0,None,4
18,41641721,This link is pretty helpful: http://misc.flogi...,2014-10-22 10:32:44.073000+00:00,5947742,474563.0,None,23
19,41652582,There isn't a `:clear` command in GHCi. If you...,2014-10-22 15:31:36.587000+00:00,26510938,1139697.0,None,7
20,41653557,If a black outline is what you want. Draw the ...,2014-10-22 15:55:09.687000+00:00,26511682,4146185.0,None,4
21,41655005,use access right? break inheritance of read/wr...,2014-10-22 16:32:57.450000+00:00,26512337,157833.0,None,5
22,41674180,you need cygwin (possibly). You are trying to ...,2014-10-23 07:05:19.983000+00:00,26522789,1770601.0,None,4
23,41688914,It seems that your script tries to read from s...,2014-10-23 15:11:04.427000+00:00,26531144,296974.0,None,4
24,41708731,"Your CSS only has `-moz-` prefix, which only w...",2014-10-24 06:01:15.697000+00:00,26542326,188331.0,None,4
25,41711356,That's the standard behaviour of program optio...,2014-10-24 08:07:16.300000+00:00,26542155,775806.0,None,5
26,41717443,Is this meant to be C or C++?,2014-10-24 11:53:10.770000+00:00,26547329,2732806.0,None,6
27,41729009,Updated post with things I've tried. \nWould b...,2014-10-24 17:59:04.853000+00:00,26553321,4140789.0,None,4
28,41729551,@AirsourceLtd This question is most indeed abo...,2014-10-24 18:18:18.263000+00:00,26491162,2034787.0,None,5
29,41731533,Love how SO has a habit of closing people's fa...,2014-10-24 19:26:12.577000+00:00,12905426,563329.0,None,22
...,...,...,...,...,...,...,...
1184026,36112743,"Call it for A to B, then for B to C, then...",2014-05-08 10:53:19.607000+00:00,23529970,NaN,user467105,1
1184027,36118260,I think that's something you'll have to decide...,2014-05-08 13:04:39.643000+00:00,23529970,NaN,user467105,1
1184028,36130696,Dude! How can I thank you ??? That worked PERF...,2014-05-08 17:54:55.373000+00:00,23540070,NaN,user3580316,1
1184029,36332134,"Private keys, as name suggests, imho are inten...",2014-05-14 12:45:17.353000+00:00,23655052,NaN,user1659862,1
1184030,36370653,Maybe this can help: http://stackoverflow.com/...,2014-05-15 09:58:14.840000+00:00,23674820,NaN,user1693593,1
1184031,36575900,I'm part of the team that created Nevron Chart...,2014-05-21 12:13:20.487000+00:00,1946553,NaN,user2641607,1
1184032,36603826,"@fadden, a useful lead: according to this fant...",2014-05-22 04:05:28.570000+00:00,23792897,NaN,user3467994,1
1184033,36605198,This great document explains PorterDuff Modes ...,2014-05-22 05:25:08.480000+00:00,10245681,NaN,user3467994,1
1184034,36640842,"@MarcB True, but of course if you want to repr...",2014-05-22 21:10:38.340000+00:00,23817064,NaN,user395760,1
1184035,36783487,I think I understand your problem now. When yo...,2014-05-27 14:21:31.913000+00:00,23888901,NaN,user1019830,1
1184036,36783641,No. Not that I know of. It's the way the brows...,2014-05-27 14:24:57.340000+00:00,23888901,NaN,user1019830,1
1184037,36836774,"@AntoJurković hmm. well if you search for ""haw...",2014-05-28 19:02:46.763000+00:00,23919606,NaN,user1112598,1
1184038,36863730,@Methnani Bilel it worked. Thanks a ton! :),2014-05-29 13:26:28.137000+00:00,23934013,NaN,user3502675,1
1184039,36864514,@geocodezip I've edited the question with a gi...,2014-05-29 13:46:07.870000+00:00,23919606,NaN,user1112598,1
1184040,37285802,`awk 'END {print NR}'`,2014-06-11 09:55:50.013000+00:00,24159552,NaN,user3442743,1
1184041,37330868,Not at all an answer to your question but: Cod...,2014-06-12 12:16:34.137000+00:00,24183849,NaN,user467105,1
1184042,37369688,interesting way of reading a file :P,2014-06-13 11:23:51.507000+00:00,24204122,NaN,user1558455,1
1184043,37484041,Do you have any code you can show?,2014-06-17 12:44:28.753000+00:00,24264130,NaN,user707650,1
1184044,37500380,I solved it. Thanks.,2014-06-17 20:03:51.363000+00:00,24250094,NaN,user3236167,1
1184045,37579514,"Actually, I just installed Java 3D, rather tha...",2014-06-19 18:56:56.393000+00:00,24250094,NaN,user3236167,1
1184046,37579989,Updated the post with the code. The last line ...,2014-06-19 19:09:36.287000+00:00,24314353,NaN,user3236167,1
1184047,37695415,Just a suggestion: it would probably be easier...,2014-06-23 20:45:53.947000+00:00,24374970,NaN,user837703,1
1184048,37725735,Make `ax1` an attribute of the class: `self.ax...,2014-06-24 15:55:13.343000+00:00,24390874,NaN,user707650,1
1184049,37739181,You can use anything to solve anything; it's j...,2014-06-25 00:06:07.860000+00:00,24398231,NaN,user2134086,1
1184050,37743312,You can download the stylesheets for the exist...,2014-06-25 04:58:41.727000+00:00,24400450,NaN,user1864610,1
1184051,36377223,Use CLLocation's distanceFromLocation method t...,2014-05-15 12:31:24.303000+00:00,23676349,NaN,user467105,2
1184052,36608154,You may use [CacheGrind](http://valgrind.org/d...,2014-05-22 07:08:15.990000+00:00,23799938,NaN,user142650,2
1184053,36327335,"What about `barplot(sort(cropmean, decreasing ...",2014-05-14 09:46:35.250000+00:00,23652691,NaN,Sergio,3
1184054,37044752,Try Nevron Diagram for .NET:\nhttps://www.nevr...,2014-06-04 07:05:07.717000+00:00,6298380,NaN,user896851,3
1184055,37739289,"In your first sentence: if ""do P and NP coinci...",2014-06-25 00:15:15.973000+00:00,24398231,NaN,user824425,3

In [18]:
# write the dataframe to a tsv
dfCommentsFiltered.to_csv("data/stackoverflow/CommentsFiltered_v3.tsv", sep='\t')

In [41]:
# USE THIS CODE TO LOAD THE STACK OVERFLOW POST COMMENTS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfCommentsFiltered = pd.read_csv("data/stackoverflow/CommentsFiltered.tsv", sep='\t')

In [42]:
dfCommentsFiltered

,Unnamed: 0,id,text,creation_date,post_id,user_id,user_display_name,score
0,0,13959910,Don't worry about extra objects unless there i...,2012-05-24 19:03:24.103000+00:00,10743622,NaN,user166390,6
1,1,14116297,"If you're going to use NodeJS, you might as we...",2012-05-31 20:28:18.247000+00:00,10840689,NaN,user1106925,5
2,2,14834466,"WTF, you want to write your own virtual filesy...",2012-07-01 04:15:00.443000+00:00,11279477,NaN,user405725,6
3,3,13253544,"Sorry about the semicolons, I did put them in ...",2012-04-24 13:46:43.277000+00:00,10298983,NaN,user818700,0
4,4,13254271,"@Pointy - I'm so sorry, it's obviously too lat...",2012-04-24 14:11:36.220000+00:00,10298983,NaN,user818700,0
5,5,13255022,Ahhhh.. Now I see. Thank you very much. I real...,2012-04-24 14:37:07.523000+00:00,10298983,NaN,user818700,0
6,6,13256213,Here's a complete example: http://codepad.org/...,2012-04-24 15:18:30.447000+00:00,10290177,NaN,user393964,0
7,7,13279186,"I'm certainly surprised by this, and it does't...",2012-04-25 12:52:39.417000+00:00,10315746,NaN,user24359,0
8,8,13279391,"Er, I mean `Payments`",2012-04-25 12:59:19.757000+00:00,10315746,NaN,user24359,0
9,9,13283132,@dasblinkenlight great thanks. I guess this is...,2012-04-25 15:09:25.203000+00:00,10318302,NaN,user517491,0
10,10,13294136,getLatLong evaluates to undefined there. What'...,2012-04-25 23:20:36.513000+00:00,10325141,NaN,user166390,0
11,11,13299256,"Thinking about it a bit more, approximation wo...",2012-04-26 06:42:10.947000+00:00,10328302,NaN,user1254163,0
12,12,13299587,"Thanks, could you clarify just a bit more?",2012-04-26 07:01:08.473000+00:00,10328302,NaN,user1254163,0
13,13,13349030,"@RobTaylor, thanks, that was the answer!",2012-04-28 01:15:46.203000+00:00,10356249,NaN,user349026,0
14,14,13353005,"I fix this, no result",2012-04-28 10:09:40.510000+00:00,10362497,NaN,user1085536,0
15,15,13356459,When you need to crunch lots of data. Ask a v...,2012-04-28 15:17:45.123000+00:00,10364690,NaN,user554546,0
16,16,13360761,"Did you try substracting two? If it works, it ...",2012-04-28 20:40:26.977000+00:00,10367336,NaN,user529758,0
17,17,13392990,If you need pseudo-code in java. Please check ...,2012-04-30 16:41:35.510000+00:00,2445380,NaN,user1245222,0
18,18,13397179,i need that plotLine on the xAxis to affect ju...,2012-04-30 20:15:18.847000+00:00,10389794,NaN,user1170618,0
19,19,13399991,"As far as I remember it worked fine, it was ju...",2012-04-30 22:53:54.873000+00:00,5292700,NaN,user206705,0
20,20,13412484,"PeterP, I think the root cause of most of your...",2012-05-01 14:47:12.087000+00:00,10382727,NaN,user694833,0
21,21,13415888,You mean the part they could travel together?,2012-05-01 17:08:42.250000+00:00,10401339,NaN,user180326,0
22,22,13436789,How is mapView declared and created? Show how...,2012-05-02 13:27:31.307000+00:00,10410431,NaN,user467105,0
23,23,13446583,Please check what tags relate to before you us...,2012-05-02 19:59:18.940000+00:00,10420327,NaN,user577537,0
24,24,13446620,"In fact, is this a programming question, or do...",2012-05-02 20:00:26.583000+00:00,10420327,NaN,user577537,0
25,25,13454793,"Hi, I wish to store just the data. and later ...",2012-05-03 06:14:14.093000+00:00,10425984,NaN,user1357933,0
26,26,13455047,That means the client must have the Excel inst...,2012-05-03 06:29:25.630000+00:00,10425984,NaN,user1357933,0
27,27,13455153,"Yep, I thought he should have a Excel installe...",2012-05-03 06:36:15.940000+00:00,10425984,NaN,user1357933,0
28,28,13455434,"If it's CLI, treat it like ... CLI. Just launc...",2012-05-03 06:52:54.417000+00:00,10426332,NaN,user166390,0
29,29,13457347,"Stack Overflow is for programming questions, i...",2012-05-03 08:32:37.013000+00:00,10420327,NaN,user577537,0
...,...,...,...,...,...,...,...,...
1781382,1781382,92195296,Max of what? You're getting a single row number.,2018-10-03 15:48:05.933000+00:00,52630943,NaN,user4039065,2
1781383,1781383,92222177,If you're struggling then you've written somet...,2018-10-04 11:01:47.900000+00:00,52645043,NaN,user4039065,2
1781384,1781384,92244715,Type `=textjoin()` into a cell. Do you get a `...,2018-10-05 00:49:12.140000+00:00,52656870,NaN,user4039065,2
1781385,1781385,92280566,Have you accepted the vb overhead and tried `p...,2018-10-06 04:07:02.387000+00:00,52675562,NaN,user4039065,2
1781386,1781386,92345084,Homework questions are welcome here so long as...,2018-10-08 20:13:28.433000+00:00,52709423,NaN,user4039065,2
1781387,1781387,92372894,countif not good enough?,2018-10-09 14:46:33.007000+00:00,52723771,NaN,user4039065,2
1781388,1781388,92680303,possible duplicate of [TEXTJOIN for xl2010/xl2...,2018-10-18 22:31:40.197000+00:00,52883256,NaN,user4039065,2
1781389,1781389,92695899,you can do this with the HYPERLINK function.,2018-10-19 11:42:28.943000+00:00,52891640,NaN,user4039065,2
1781390,1781390,92700913,... and [Is the . in .Range necessary when def...,2018-10-19 14:11:51.083000+00:00,52893738,NaN,user4039065,2
1781391,1781391,92703506,Lots of hits for this message on the internet....,2018-10-19 15:26:13.893000+00:00,52895386,NaN,user1531971,2
1781392,1781392,92789638,How is this not the simplest COUNTIF question?,2018-10-23 02:45:42.043000+00:00,52940245,NaN,user4039065,2
1781393,1781393,92796187,Doesn't `=sumproduct(--((COUNTIF*COUNTIF)>0))`...,2018-10-23 08:06:00.657000+00:00,52944014,NaN,user4039065,2
1781394,1781394,92800753,"Use a series with a step, not an autofill.",2018-10-23 10:05:37.653000+00:00,52946233,NaN,user4039065,2
1781395,1781395,92866495,Ping me if you [edit] your question to show yo...,2018-10-25 01:31:09.460000+00:00,52979742,NaN,user4039065,2
1781396,1781396,92923984,Seen this?\r\nhttps://stackoverflow.com/questi...,2018-10-26 13:53:32.163000+00:00,53007623,NaN,user2261597,2
1781397,1781397,92939774,If that was a POSIX datetime the result would ...,2018-10-27 03:18:43.720000+00:00,53018396,NaN,user4039065,2
1781398,1781398,92940232,Get rid of `On Error Resume Next` and try it a...,2018-10-27 04:33:35.060000+00:00,53018619,NaN,user4039065,2
1781399,1781399,92945684,DateValue takes a string and returns a true date.,2018-10-27 12:03:13.977000+00:00,53021679,NaN,user4039065,2
1781400,1781400,91178470,The behavior you're trying to achieve is handl...,2018-08-31 11:02:26.433000+00:00,52114044,NaN,user4039065,3
1781401,1781401,91682982,It looks like you're copying the whole row for...,2018-09-17 13:51:24.587000+00:00,52369143,NaN,user4039065,3
1781402,1781402,91760754,My guess is that fx reads the string masquerad...,2018-09-19 14:45:55.423000+00:00,52408304,NaN,user4039065,3
1781403,1781403,91787056,You would likely be interested in [this](https...,2018-09-20 09:39:06.633000+00:00,52421920,NaN,user4039065,3
1781404,1781404,92190527,"The $ variety (e.g. Left$, Mid$, etc) are meas...",2018-10-03 13:47:13.183000+00:00,52628282,NaN,user4039065,3
1781405,1781405,92322228,What's wrong with sumif/sumifs?,2018-10-08 08:07:51.933000+00:00,52697828,NaN,user4039065,3
1781406,1781406,92367004,Does that actually work? Those text-that-look-...,2018-10-09 12:22:47.200000+00:00,52720731,NaN,user4039065,3
1781407,1781407,92596122,*Is my code running badly because I use DoEven...,2018-10-16 16:32:17.607000+00:00,52839776,NaN,user2261597,3
1781408,1781408,92685037,"What is `Range(Range(""G2:G14614""), Range(""G"" &...",2018-10-19 04:50:57.337000+00:00,52886028,NaN,user4039065,3
1781409,1781409,92702053,Looks like twenty-five minutes and forty-seven...,2018-10-19 14:44:27.907000+00:00,52894675,NaN,user4039065,3
1781410,1781410,92888112,If you are talking about fields/properties/met...,2018-10-25 14:14:20.467000+00:00,52991408,NaN,user2819245,3
1781411,1781411,92943075,This would be a good time to learn that you sh...,2018-10-27 09:11:38.137000+00:00,53019966,NaN,user4039065,3

### Pipeline for Stack Exchange Data Science Community Question and Answers Posts Starts Here

In [115]:
# Use this code to load raw Data Science Stack Exchange questions and answers to Pandas dfs -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to

dfDSPosts = pd.read_csv("Data/Stack Exchange Data Science/Posts_From_Data_Science_Stack_Exchange.csv", keep_default_na=False)

dfDSQues=dfDSPosts[dfDSPosts['PostTypeId']==1]
dfDSAns=dfDSPosts[dfDSPosts['PostTypeId']==2]

del dfDSPosts

In [120]:
np.shape(dfDSQues)

(20502, 22)

In [121]:
np.shape(dfDSAns)

(22666, 22)

In [122]:
dfDSQues.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
2,54306,1,,,2019-06-22 19:34:13,,0,548,<p>I am working on a project that uses object ...,73678,...,,2019-06-24 04:33:04,2019-06-24 04:33:04,Transfer learning on yolo using keras,<deep-learning><keras><cnn><object-detection><...,0,1,,,
3,54307,1,,,2019-06-22 20:22:13,,0,32,<p>I'm trying to develop a neural network mode...,76495,...,,2019-06-22 20:50:13,2019-06-22 20:50:13,loss function for model that predicts a matrix,<machine-learning><keras><game>,0,0,,,
4,54313,1,54326,,2019-06-23 01:25:13,,0,126,"<p><a href=""https://github.com/Hyeokreal/Actor...",69646,...,,2019-06-25 14:16:13,2019-06-25 14:16:13,A2C Continuous for Pendulum-v0 working impleme...,<neural-network><distribution><gaussian><opena...,1,0,,,
6,54315,1,,,2019-06-23 02:44:03,,0,97,<p>I just resized the image dataset with Pillo...,76386,...,,2019-06-23 05:43:38,2019-06-23 05:43:38,Image is in JPEG but Torchvision shows image e...,<pytorch><image-preprocessing>,0,0,,,
7,54316,1,,,2019-06-23 03:44:17,,0,12,<p>I've trained and developed a Haar Cascade c...,75423,...,,,2019-06-23 03:44:17,Can Haar cascades be used for object tracking ...,<machine-learning><object-detection>,0,0,,,

In [123]:
dfDSAns.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,54303,2,,54237,2019-06-22 18:41:15,,1,,<p>You say you use linear regression. There ar...,71442,...,,,2019-06-22 18:41:15,,,,0,,,
1,54304,2,,54293,2019-06-22 19:06:46,,0,,<p>There are many points that you should check...,71675,...,,2019-06-23 16:04:51,2019-06-23 16:04:51,,,,5,,,
5,54314,2,,54281,2019-06-23 01:49:40,,1,,"<p>First, the remark from the wikipedia articl...",55122,...,,,2019-06-23 01:49:40,,,,5,,,
10,54319,2,,53478,2019-06-23 05:23:02,,1,,<p>As We should not remove any data ... we can...,76129,...,,,2019-06-23 05:23:02,,,,0,,,
14,54323,2,,54263,2019-06-23 09:18:46,,1,,"<p>We have </p>\n\n<p><span class=""math-contai...",38892,...,,,2019-06-23 09:18:46,,,,0,,,

In [134]:
# let's delete questions without answers 
dfDSQues['AnswerCount'][dfDSQues['AnswerCount'] != '0'].count()

14879

In [135]:
dfDSQues = dfDSQues[dfDSQues['AnswerCount'] != '0' ]

In [136]:
np.shape(dfDSQues)

(14879, 22)

In [139]:
# let's also delete questions without accepted answers
dfDSQues['Id'][dfDSQues['AcceptedAnswerId'] == ''].count()

8185

In [140]:
dfDSQues = dfDSQues[dfDSQues['AcceptedAnswerId'] != '']

In [141]:
np.shape(dfDSQues)

(6694, 22)

In [142]:
# read the model tags file to be used to create the tag features from the tagtext field in the questions file, which
# has all tag values concatenated without any separators

# NOTE: Used shortened version of model tag list below

dfModelTags = pd.read_csv("data/stackoverflow/modeltags_shortened.csv")

In [143]:
dfModelTags

          tagtext
0          python
1           scala
2          matlab
3      matplotlib
4       animation
5              d3
6         ggplot2
7            plot
8           graph
9           chart
10     highcharts
11             3d
12           maps
13        drawing
14         plotly
15      bar-chart
16  visualization
17        seaborn
18     geospatial
19      pie-chart
20       graphviz
21        diagram
22          radar

In [144]:
# add a new column to hold tags from the modeltags table that occur in the queion tags field

dfDSQues['new_tags']=''

C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [145]:
# find occurences of model tag values in tags filed, and append them to tbe new_tags field
def parsetags(qtag):
    tstr=''
    for i in dfModelTags['tagtext']:
        if i in qtag:
            tstr=tstr + i + " "
    return tstr

dfDSQues['new_tags'] = dfDSQues['Tags'].map(parsetags)

C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [146]:
dfDSQues['new_tags']

4
17
24
27
30
49
53              python
56              python
58
61
63
65              python
69
84       visualization
86
90              python
101
103
109             python
114
117
119
122              scala
123
125
134
138
140
149
155
              ...
43483
43484           python
43488
43489
43490
43493
43501
43506           python
43512
43516
43518
43520
43521
43522            scala
43526
43537
43545           python
43552
43556
43564
43580
43589
43593
43597           python
43607           python
43611
43612
43627
43640
43644
Name: new_tags, Length: 6694, dtype: object

In [148]:
dfDSQues['Tags']

4        <neural-network><distribution><gaussian><opena...
17         <deep-learning><training><recurrent-neural-net>
24                                 <machine-learning><svm>
27                                      <r><data-cleaning>
30                         <machine-learning><probability>
49       <machine-learning><deep-learning><supervised-l...
53                            <python><time-series><excel>
56       <machine-learning><python><data-mining><numpy>...
58           <deep-learning><keras><loss-function><metric>
61                                  <dataset><csv><matrix>
63       <machine-learning><categorical-data><beginner>...
65          <python><neural-network><deep-learning><keras>
69                                              <features>
84       <visualization><machine-learning-model><data-s...
86       <machine-learning><neural-network><data-scienc...
90       <machine-learning><python><data-mining><numpy>...
101                                   <data-cleaning><sql>
103      <regression><linear-regression><feature-engine...
109      <machine-learning><python><data><data-analysis...
114                               <education><open-source>
117                             <data-mining><definitions>
119                    <machine-learning><bigdata><libsvm>
122        <bigdata><scalability><efficiency><performance>
123                               <nosql><relational-dbms>
125      <data-mining><clustering><octave><k-means><cat...
134                              <data-mining><clustering>
138              <nosql><tools><processing><apache-hadoop>
140                                           <bigdata><r>
149                      <r><databases><efficiency><tools>
155                                     <apache-hadoop><r>
                               ...
43483                                   <pyspark><jupyter>
43484             <machine-learning><python><dataset><csv>
43488                                     <decision-trees>
43489                                     <neural-network>
43490    <machine-learning><neural-network><activation-...
43493                                     <neural-network>
43501    <machine-learning><image-classification><train...
43506             <python><scikit-learn><cross-validation>
43512                                                  <r>
43516                       <clustering><nlp><text-mining>
43518                                                  <r>
43520     <scikit-learn><pandas><categorical-data><labels>
43521                                             <orange>
43522                                <apache-spark><scala>
43526              <machine-learning><logistic-regression>
43537                                    <model-selection>
43545       <python><scikit-learn><naive-bayes-classifier>
43552              <machine-learning><logistic-regression>
43556                <machine-learning><linear-regression>
43564    <machine-learning><classification><clustering>...
43580            <machine-learning><unsupervised-learning>
43589    <classification><clustering><unsupervised-lear...
43593                            <classification><xgboost>
43597    <machine-learning><python><regression><decisio...
43607                                     <python><pandas>
43611                           <neural-network><beginner>
43612    <machine-learning><parameter><hyperparameter><...
43627                           <machine-learning><pandas>
43640    <machine-learning><deep-learning><gradient-des...
43644                   <machine-learning><neural-network>
Name: Tags, Length: 6694, dtype: object

In [150]:
# Here is a separate process to check for references to the r language in the question body
# and set a separate 'r' column in the questions df to be used to update new_tags
#
# we cannot use the same process used on the tags above, since it will almost always find occurrences of 'r'
# in the tags field that are just parts of other terms (for example, the "r" in "chart")
#
# So, here we look for standalone references to r in the question body instead
#
dfDSQues['r'] = ''

def testforr(x):
    if (' r ' in x) or (' r,' in x) or (' r.' in x) or (' r:' in x):
        return 'r '
    else:
        return ''

dfDSQues['r'] = dfDSQues['Body'].map(testforr)

In [151]:
# now, update new_tags, appending the 'r' for questions referencing r in the question body
dfDSQues['new_tags'] = dfDSQues['new_tags'] + dfDSQues['r']

In [152]:
dfDSQues['new_tags'][dfDSQues['r']=='r ']

2172     python r
2390            r
3188            r
3681     python r
3827            r
5035            r
6090     python r
6326            r
6397            r
7327            r
8033            r
8474            r
10174           r
10562           r
10815    python r
11947           r
12010           r
15514    python r
15971           r
16782           r
20475    python r
21000    python r
25241           r
26324           r
27178           r
29892           r
30533           r
33416           r
34077           r
37844           r
41343           r
41706           r
41891           r
42824    python r
Name: new_tags, dtype: object

In [153]:
# drop the 'r' column, as it is no longer needed
del dfDSQues['r']

In [155]:
dfDSQues.iloc[0]

Id                                                                   54313
PostTypeId                                                               1
AcceptedAnswerId                                                     54326
ParentId
CreationDate                                           2019-06-23 01:25:13
DeletionDate
Score                                                                    0
ViewCount                                                              126
Body                     <p><a href="https://github.com/Hyeokreal/Actor...
OwnerUserId                                                          69646
OwnerDisplayName
LastEditorUserId                                                     69646
LastEditorDisplayName
LastEditDate                                           2019-06-25 14:16:13
LastActivityDate                                       2019-06-25 14:16:13
Title                    A2C Continuous for Pendulum-v0 working impleme...
Tags                     <neural-network><distribution><gaussian><opena...
AnswerCount                                                              1
CommentCount                                                             0
FavoriteCount
ClosedDate
CommunityOwnedDate
new_tags
Name: 4, dtype: object

In [156]:
# now, let's drop any questions that do not have tags we are interested in

dfDSQues['Id'][dfDSQues['new_tags'] == ''].count()

5109

In [157]:
dfDSQues = dfDSQues[dfDSQues['new_tags'] != '']

In [158]:
np.shape(dfDSQues)

(1585, 23)

In [159]:
# let's now create a separate question body column, 'cleaned_question_body', that removes all the code and all HTL tags
# from the question body
# We might use the cleaned_question_body as a feature in one of the similarity models
def clean_ques_body_text(body):
    tmp_body=BeautifulSoup(body,"lxml")
    for code in tmp_body('code'):
        code.replace_with('')
    tstr=''
    for string in tmp_body.stripped_strings:
        tstr = tstr + ' ' + string
    return tstr

dfDSQues['cleaned_question_body']=''

sttime=time.time()    
dfDSQues['cleaned_question_body'] = dfDSQues['Body'].map(clean_ques_body_text)
print('question body cleaned in',(time.time()-sttime)/60,'minutes')

C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\jeffb\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

question body cleaned in 0.1575226863225301 minutes

In [160]:
dfDSQues['Body'].head()

53    <p>I have a excel data with time stamp format ...
56    <p>I am learning <a href="https://en.wikipedia...
65    <p>I have trained an ANN model for a regressio...
84    <p>I'm getting confused as how to proceed for ...
90    <p>I am learning <a href="https://en.wikipedia...
Name: Body, dtype: object

In [161]:
dfDSQues['cleaned_question_body'].head()

53     I have a excel data with time stamp format li...
56     I am learning SVD by following this MIT cours...
65     I have trained an ANN model for a regression ...
84     I'm getting confused as how to proceed for th...
90     I am learning SVD by following this MIT cours...
Name: cleaned_question_body, dtype: object

In [162]:
print('questions with cleaned_question_body == Nan',len(dfDSQues['cleaned_question_body'][dfDSQues['cleaned_question_body'].isna()]))

questions with cleaned_question_body == Nan 0

In [163]:
print('questions with cleaned_question_body == "" ',len(dfDSQues['cleaned_question_body'][dfDSQues['cleaned_question_body'] == '']))

questions with cleaned_question_body == ""  3

In [164]:
# write the dataframe to a tsv
dfDSQues.to_csv("data/stackoverflow/DataSciQues_parsed.tsv", sep='\t', index=False)

In [165]:
# write the dataframe to a csv
dfDSQues.to_csv("data/stackoverflow/DataSciQues_parsed.csv",index=False)

In [21]:
# USE THIS CODE TO LOAD THE DATA SCIENCE QUESTIONS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfDSQues = pd.read_csv("data/stackoverflow/DataSciQues_parsed.tsv", sep='\t', keep_default_na=False)

In [6]:
dfDSQues

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,new_tags,cleaned_question_body
0,54374,1,54456,,2019-06-24 09:33:19,,1,590,<p>I have a excel data with time stamp format ...,76265,...,2019-08-06 15:33:14,Changing Timestamp format for Date-Time in Exc...,<python><time-series><excel>,1,1,,,,python,I have a excel data with time stamp format li...
1,54377,1,54378,,2019-06-24 09:53:27,,1,112,"<p>I am learning <a href=""https://en.wikipedia...",74719,...,2019-06-24 21:49:49,"is there a way to normalize [-3,1] to ${\begin...",<machine-learning><python><data-mining><numpy>...,1,0,2,,,python,I am learning SVD by following this MIT cours...
2,54386,1,54389,,2019-06-24 11:55:07,,0,53,<p>I have trained an ANN model for a regressio...,67537,...,2019-06-24 13:03:43,Predict using a saved regression model,<python><neural-network><deep-learning><keras>,1,3,,,,python,I have trained an ANN model for a regression ...
3,54407,1,54419,,2019-06-24 16:57:57,,0,49,<p>I'm getting confused as how to proceed for ...,76590,...,2019-06-25 02:38:11,How to predict number of orders for coming wee...,<visualization><machine-learning-model><data-s...,1,2,,,,visualization,I'm getting confused as how to proceed for th...
4,54413,1,54418,,2019-06-24 22:11:19,,1,125,"<p>I am learning <a href=""https://en.wikipedia...",74719,...,2019-06-25 02:48:41,Why does np.linalg.eig produce an opposite-sig...,<machine-learning><python><data-mining><numpy>...,1,0,0,,,python,I am learning SVD by following this MIT cours...
5,54436,1,54505,,2019-06-25 07:29:41,,0,727,"<pre class=""lang-py prettyprint-override""><cod...",76521,...,2019-06-26 00:25:12,ValueError: pos_label=1 is not a valid label: ...,<machine-learning><python><data><data-analysis...,1,0,,,,python,My training data contains the categorical fea...
6,19,1,37,,2014-05-14 03:56:20,,86,13211,<p>Lots of people use the term <em>big data</e...,84,...,2018-05-01 13:04:43,How big is big data?,<bigdata><scalability><efficiency><performance>,12,5,25,,,scala,Lots of people use the term big data in a rat...
7,116,1,121,,2014-05-17 09:16:18,,25,2818,<p>I have a database from my Facebook applicat...,173,...,2016-04-28 06:18:44,Machine learning techniques for estimating use...,<machine-learning><dimensionality-reduction><p...,6,3,12,,,python,I have a database from my Facebook applicatio...
8,23969,1,23998,,2017-10-22 07:36:15,,13,44412,<p>I'm looking to solve the following problem:...,21254,...,2019-09-02 13:55:46,Sentence similarity prediction,<python><nlp><scikit-learn><similarity><text>,5,3,12,,,python,I'm looking to solve the following problem: I...
9,23990,1,23992,,2017-10-23 02:37:45,,4,426,"<p>I am studying the blog: <a href=""http://www...",35597,...,2017-10-31 04:10:06,Understand clearly the figure: Illustration of...,<python><deep-learning><nlp><sentiment-analysi...,1,0,3,,,python,I am studying the blog: Understanding Convolu...
10,14355,1,14366,,2016-10-04 13:54:26,,0,560,<p>I started tinkering with sklearn kmeans las...,24930,...,2016-10-05 16:51:29,Quick start using python and sklearn kmeans?,<python><scikit-learn><k-means>,1,3,,,,python,I started tinkering with sklearn kmeans last ...
11,14385,1,14388,,2016-10-05 19:03:58,,2,1355,<p>I have a dataset with election results and ...,17636,...,2016-10-05 21:05:34,Pearson correlation method using absolute valu...,<python><statistics><correlation>,1,4,,,,python,I have a dataset with election results and cr...
12,44155,1,44167,,2019-01-17 16:30:51,,2,72,<p>Is there a way to more efficiently filter a...,66039,...,2019-01-17 22:16:42,Filtering Pandas Dataframe Results without sav...,<python><pandas>,2,0,,,,python,Is there a way to more efficiently filter a r...
13,44192,1,44217,,2019-01-18 10:52:14,,3,3155,<p>Seaborn library in python suggests to use e...,57237,...,2019-01-18 19:40:48,What is the difference between regplot and lmp...,<regression><visualization><seaborn>,1,0,1,,,visualization seaborn,Seaborn library in python suggests to use eit...
14,44219,1,62220,,2019-01-18 20:08:23,,2,396,<p>I would greatly appreciate if you could let...,26019,...,2019-10-25 14:43:20,How to use SMOTENC inside the Pipeline?,<python><scikit-learn><imbalanced-learn><smotenc>,1,6,0,,,python,I would greatly appreciate if you could let m...
15,44224,1,44226,,2019-01-19 08:44:20,,3,156,<p>I have seen that a lot of people write code...,58761,...,2019-01-20 02:27:10,Why do a lot of people use ipython notebook ov...,<python><statistics><data><ipython>,2,2,,,,python,I have seen that a lot of people write code i...
16,44246,1,44247,,2019-01-19 18:55:30,,1,54,<p>There is a scientific document that impleme...,47359,...,2019-01-19 19:27:53,What is exactly meant by neural network that c...,<python><neural-network><tensorflow><convnet>,1,0,,,,python,There is a scientific document that implement...
17,34038,1,34124,,2018-07-05 13:13:41,,1,63,"<p>Based on answers to <a href=""https://datasc...",82,...,2019-06-07 21:41:55,Can I create random forest with RandomForestCl...,<python><classification><scikit-learn><random-...,1,6,1,,,python,"Based on answers to this question, I should b..."
18,34039,1,34045,,2018-07-05 13:14:49,,3,7704,<p>I am new to regex. I am working on a projec...,30693,...,2018-07-10 06:10:52,regex to remove repeating words in a sentence,<python><nlp><regex>,2,0,3,,,python,I am new to regex. I am working on a project ...
19,34052,1,34059,,2018-07-05 17:17:10,,0,251,<p>I am running a logisitic regression model u...,54055,...,2018-07-06 04:35:45,Local minima in Stochastic Gradient Descent,<python><keras>,1,0,,,,python,I am running a logisitic regression model usi...
20,34069,1,34081,,2018-07-05 23:00:44,,0,26,<h2><strong>Recall Definition</strong></h2>\r\...,2893,...,2018-07-06 10:31:07,Does recall has different interpretation when ...,<python><classification><information-retrieval...,1,0,,,,python,Recall Definition In terms of classification ...
21,34072,1,34097,,2018-07-06 00:33:12,,0,37,<p>I have a dataset with 8 features (columns)....,35386,...,2018-07-06 13:43:41,Giving a score (from 1 - 5) using weights,<machine-learning><python><data-mining><datase...,1,2,,,,python,I have a dataset with 8 features (columns). E...
22,34088,1,34111,,2018-07-06 09:58:53,,1,312,<p>I am working on graphs/networks where nodes...,50123,...,2018-07-06 20:31:33,Graph & Network Mining: clustering/community d...,<machine-learning><classification><unsupervise...,1,0,,,,graph,I am working on graphs/networks where nodes a...
23,14406,1,14409,,2016-10-06 21:27:28,,10,3975,<p>I have a dataset in following structure ins...,23714,...,2019-06-07 17:35:08,Visualizing items frequently purchased together,<python><r><data-mining><visualization><associ...,4,0,4,,,python visualization,I have a dataset in following structure inser...
24,14429,1,14663,,2016-10-09 13:23:56,,11,11820,<p>I am making a simple neural network using t...,19067,...,2016-10-20 14:20:47,Tensorflow neural network TypeError: Fetch arg...,<machine-learning><python><neural-network><ten...,1,0,3,,,python,I am making a simple neural network using ten...
25,14435,1,14441,,2016-10-10 06:17:43,,7,7690,<p>I need to get the probability for each poin...,24994,...,2019-07-16 05:32:36,How to get the probability of belonging to clu...,<python><clustering><k-means>,3,0,3,,,python,I need to get the probability for each point ...
26,14457,1,14459,,2016-10-11 14:21:45,,1,233,<p>I'm currently working on a project involvin...,24830,...,2016-10-11 16:26:35,Regression in Predicting Tenancy Lengths,<python><neural-network><predictive-modeling><...,1,0,1,,,python,I'm currently working on a project involving ...
27,14458,1,14525,,2016-10-11 15:02:43,,0,383,<p>I have this dataset (just a sample):</p>\r\...,23811,...,2016-10-15 14:17:17,Create data visualization for unstructured dat...,<visualization><association-rules><market-bask...,2,7,,,,visualization,I have this dataset (just a sample): The prod...
28,14467,1,14468,,2016-10-12 07:25:55,,5,8384,"<p>In this <a href=""https://github.com/jocicma...",14360,...,2017-09-12 23:48:48,What does Theano dimension ordering mean?,<python><keras><theano>,1,0,1,,,python,"In this code , line 13 is commented as Theano..."
29,34181,1,34195,,2018-07-09 09:09:46,,1,2810,<p>I want to create a dataset from three numpy...,53283,...,2018-07-09 13:13:55,Appending to numpy array for creating dataset,<python><deep-learning><numpy>,1,2,,,,python,I want to create a dataset from three numpy m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1555,33766,1,33771,,2018-06-28 12:52:40,,0,479,<h2>Question:</h2>\r\n\r\n<p>I want to compare...,53928,...,2018-06-29 12:15:16,How to compare fast the value with the ones of...,<python><bigdata><numpy>,1,4,,,,python r,Question: I want to compare every item in a 3...
1556,33780,1,33783,,2018-06-28 19:19:33,,0,14351,<p>I have my dataset that has multiple feature...,50896,...,2018-12-17 16:04:09,Scatter plot for binary class dataset with two...,<python><pandas><plotting><numpy><matplotlib>,3,4,,,,python matplotlib plot,I have my dataset that has multiple features ...
1557,13550,1,13551,,2016-08-19 12:16:40,,2,13593,<p>I am learning python and trying myself out ...,23452,...,2018-08-30 15:26:17,Problems with accuracy.score sklearn,<python><scikit-learn><error-handling>,2,0,,,,python,I am learning python and trying myself out at...
1558,13567,1,13575,,2016-08-20 06:51:26,,18,12318,<p>I am working on a fictional dataset with 25...,23600,...,2017-03-02 19:08:25,Ways to deal with longitude/latitude feature,<machine-learning><python><feature-engineering...,1,7,12,2016-08-20 17:20:30,,python,I am working on a fictional dataset with 25 f...
1559,13580,1,13582,,2016-08-20 19:19:05,,-1,235,<p>I know how to split the dataset into train ...,15412,...,2016-08-20 20:56:40,Splitting Data in scikit-learn,<machine-learning><python><dataset><scikit-learn>,1,2,,,,python,I know how to split the dataset into train an...
1560,13633,1,13635,,2016-08-24 07:41:53,,1,47,<p>I used the Neural Network Toolbox in matlab...,8013,...,2016-08-24 09:19:38,Query regarding neural network model,<neural-network><supervised-learning><matlab><...,1,8,,,,matlab,I used the Neural Network Toolbox in matlab t...
1561,54210,1,54219,,2019-06-21 10:15:52,,1,138,"<p>First, thank you.</p>\r\n\r\n<p>I'm using T...",76413,...,2019-06-21 12:41:55,is there a way to customize my loss function t...,<python><tensorflow>,1,0,,,,python,"First, thank you. I'm using Tensorflow 1.13 w..."
1562,33836,1,33852,,2018-06-30 17:12:09,,1,71,<p>I wanted to build a DQN. So I followed this...,54401,...,2018-07-01 15:48:43,"Tflearn ""nan"" weight matrices",<reinforcement-learning><python><q-learning>,1,0,,,,python,I wanted to build a DQN. So I followed this c...
1563,33863,1,33867,,2018-07-02 05:08:58,,1,52,<p>I have the following dataset where each row...,35386,...,2018-07-02 09:08:31,Recommending products to buy,<machine-learning><python><scikit-learn><keras...,1,0,,2018-07-03 21:54:10,,python,I have the following dataset where each row r...
1564,33868,1,33870,,2018-07-02 09:29:37,,0,343,<p>I want to implement PCA on a dataset(retail...,54450,...,2018-07-02 10:05:55,How to use multiple encoders(one-hot and numer...,<python><pca><encoding>,1,0,,,,python,I want to implement PCA on a dataset(retail) ...
1565,33879,1,33886,,2018-07-02 10:47:51,,3,8597,"<p>Based on the following dataframe, I am tryi...",54442,...,2018-07-02 20:08:53,panda grouping by month with transpose,<python><pandas>,2,0,,,,python,"Based on the following dataframe, I am trying..."
1566,33910,1,33925,,2018-07-02 21:51:21,,4,12612,<p>I am new to data science and trying get som...,49884,...,2019-01-25 16:20:04,Number of features of the model must match the...,<python><scikit-learn><feature-selection><trai...,1,1,,,,python,I am new to data science and trying get some ...
1567,13701,1,14426,,2016-08-26 18:03:38,,0,1088,<p>I'm trying to do a algorithm in Spark Mllib...,23811,...,2016-10-09 08:49:45,Items in a transaction must be unique but got ...,<apache-spark><scala><market-basket-analysis>,1,0,,,,scala,I'm trying to do a algorithm in Spark Mllib. ...
1568,13730,1,13733,,2016-08-29 12:49:26,,1,1207,<p>Imagine that I've the following dataset:</p...,23811,...,2017-12-21 15:20:53,Market Basket Analysis - Data Modelling,<apache-spark><scala><market-basket-analysis>,2,0,1,,,scala,Imagine that I've the following dataset: I ne...
1569,13749,1,13777,,2016-08-30 10:43:32,,0,2254,<p>I've a data set with this fields:</p>\r\n\r...,23811,...,2016-08-31 10:01:00,Apply GroupByKey to identify the Frequently Pr...,<apache-spark><scala><association-rules>,1,4,,,,scala,I've a data set with this fields: And I'm try...
1570,54273,1,54276,,2019-06-22 07:49:47,,5,90,<p>I am working on classification of time seri...,74166,...,2019-06-24 04:39:23,How can I know if my conv1D model is overfitte...,<python><keras><convnet>,3,0,1,,,python,I am working on classification of time series...
1571,33928,1,33929,,2018-07-03 11:08:49,,0,166,<p>I am trying to fit this model in keras but ...,44680,...,2018-07-03 11:16:21,Same input size but cannot fit the model in keras,<python><deep-learning><keras><tensorflow>,1,2,,,,python,I am trying to fit this model in keras but ge...
1572,33958,1,33963,,2018-07-04 00:03:57,,-2,440,<p>I'm trying to do some intent extraction/rec...,50899,...,2019-06-12 03:17:20,Rasa_Nlu SpaCy installing dependencies,<python><nlp>,1,1,,2018-07-04 15:43:21,,python,I'm trying to do some intent extraction/recog...
1573,13818,1,13819,,2016-09-02 11:05:02,,2,7560,<p>How Can I save a DataFrame as a CSV in HDFS...,23714,...,2018-09-12 15:22:02,value saveAsTextFile is not a member of org.ap...,<apache-spark><scala>,3,0,1,,,scala,How Can I save a DataFrame as a CSV in HDFS? ...
1574,13868,1,13869,,2016-09-05 22:26:27,,-2,877,<p>The code below measures precision and recal...,24095,...,2016-09-06 10:03:41,I need to measure Performance : AUC for this c...,<python><scikit-learn><nltk>,1,2,,2016-09-07 07:09:23,,python,The code below measures precision and recall ...
1575,13894,1,22559,,2016-09-07 15:14:56,,16,40680,"<p>In the <a href=""https://blog.keras.io/build...",14360,...,2019-07-01 14:05:17,How to get predictions with predict_generator ...,<machine-learning><python><deep-learning><kera...,3,6,3,,,python,In the Keras blog on training convnets from s...
1576,13907,1,13916,,2016-09-08 08:51:08,,1,638,<p>I am trying to learn topics distribution fo...,13518,...,2016-09-09 12:32:37,Getting uniform distribution over topics from ...,<python><text-mining><lda><gensim>,1,0,,,,python,I am trying to learn topics distribution for ...
1577,13909,1,14003,,2016-09-08 20:29:31,,1,955,"<p>I tried using kind=""box"" but am not sure if...",24114,...,2016-09-14 20:40:29,Python Seaborn: How can one obtain a box plot ...,<python><visualization>,1,0,0,,,python visualization,"I tried using kind=""box"" but am not sure if t..."
1578,13992,1,14008,,2016-09-14 12:56:58,,2,1439,<pre><code>import org.apache.spark.SparkContex...,24157,...,2016-09-15 07:00:20,Task not serializable Error,<bigdata><apache-spark><scala>,3,1,1,,,scala,This is the code that I have written in Spark...
1579,14021,1,14023,,2016-09-15 17:08:55,,1,6097,<p>I have a csv file with around 130 columns a...,24355,...,2017-07-16 06:44:57,importing csv data in python,<machine-learning><python><dataset><csv>,3,2,1,,,python,I have a csv file with around 130 columns and...
1580,14046,1,14047,,2016-09-16 23:17:05,,1,3983,<p>I was working through a tutorial on the tit...,24411,...,2019-11-01 14:53:31,"sklearn.cross_validation.cross_val_score ""cv"" ...",<python><scikit-learn><cross-validation>,2,0,,,,python,I was working through a tutorial on the titan...
1581,14072,1,14080,,2016-09-18 21:20:50,,0,6034,<p>I've two dataframes. The first have the som...,23811,...,2016-09-19 07:04:48,Join two dataframes - Spark Mllib,<apache-spark><scala>,1,0,,,,scala,I've two dataframes. The first have the some ...
1582,14102,1,14123,,2016-09-20 05:40:10,,5,3214,<p>OK this is my first time in ML and for star...,10879,...,2018-01-30 21:27:37,Naive Bayes: Divide by Zero error,<python><scikit-learn><naive-bayes-classifier>,2,2,3,,,python,OK this is my first time in ML and for starte...
1583,14165,1,14176,,2016-09-22 21:52:17,,0,858,<p>Is there a way to take a set of data that c...,13165,...,2016-09-23 17:27:01,Can I use categorical data and Decision Trees ...,<machine-learning><python><regression><decisio...,1,0,1,,,python,Is there a way to take a set of data that con...
1584,14179,1,14182,,2016-09-23 22:48:05,,0,494,<p>I have reduced the data set to only the col...,23800,...,2017-03-31 08:32:25,Pivot DataFrame while calculating new values,<python><pandas>,2,0,,,,python,I have reduced the data set to only the colum...

In [167]:
np.shape(dfDSAns)

(22666, 22)

In [168]:
dfDSAns

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,54303,2,,54237,2019-06-22 18:41:15,,1,,<p>You say you use linear regression. There ar...,71442,...,,,2019-06-22 18:41:15,,,,0,,,
1,54304,2,,54293,2019-06-22 19:06:46,,0,,<p>There are many points that you should check...,71675,...,,2019-06-23 16:04:51,2019-06-23 16:04:51,,,,5,,,
5,54314,2,,54281,2019-06-23 01:49:40,,1,,"<p>First, the remark from the wikipedia articl...",55122,...,,,2019-06-23 01:49:40,,,,5,,,
10,54319,2,,53478,2019-06-23 05:23:02,,1,,<p>As We should not remove any data ... we can...,76129,...,,,2019-06-23 05:23:02,,,,0,,,
14,54323,2,,54263,2019-06-23 09:18:46,,1,,"<p>We have </p>\n\n<p><span class=""math-contai...",38892,...,,,2019-06-23 09:18:46,,,,0,,,
15,54324,2,,54292,2019-06-23 09:25:55,,1,,"<p>Usually the <a href=""https://en.wikipedia.o...",34269,...,,,2019-06-23 09:25:55,,,,0,,,
16,54326,2,,54313,2019-06-23 10:14:40,,2,,"<blockquote>\n <p>Again, the entropy equation...",76511,...,,,2019-06-23 10:14:40,,,,1,,,
18,54328,2,,54327,2019-06-23 11:15:52,,0,,<p>Generally we track loss on validation set d...,75738,...,,,2019-06-23 11:15:52,,,,0,,,
19,54329,2,,54273,2019-06-23 11:18:15,,0,,<p>Did you try keeping a separate test set (on...,66788,...,,,2019-06-23 11:18:15,,,,0,,,
21,54331,2,,54320,2019-06-23 11:41:47,,0,,<p>This might be happening because of high lea...,75738,...,,,2019-06-23 11:41:47,,,,0,,,
25,54338,2,,54337,2019-06-23 16:08:27,,2,,"<p>In optimization, we have something called c...",38892,...,,,2019-06-23 16:08:27,,,,0,,,
28,54344,2,,44800,2019-06-23 18:20:31,,-1,,<p>You can use the ml_metrics library. For ins...,76531,...,,2019-06-23 19:05:26,2019-06-23 19:05:26,,,,0,,,
29,54345,2,,54343,2019-06-23 19:25:54,,0,,<p>I found that this works (though I'm interes...,76484,...,,,2019-06-23 19:25:54,,,,2,,,
32,54348,2,,26009,2019-06-23 21:43:40,,2,,<p>There is a common assumption that data that...,1330,...,,,2019-06-23 21:43:40,,,,0,,,
33,54349,2,,54346,2019-06-23 22:18:28,,1,,<p>It's more of a <em>theoretical</em> distrib...,34269,...,,2019-06-26 21:42:25,2019-06-26 21:42:25,,,,6,,,
38,54354,2,,54352,2019-06-24 00:52:25,,1,,"<p>I believe, RandmForest and Logistic regress...",76540,...,,,2019-06-24 00:52:25,,,,0,,,
39,54357,2,,54351,2019-06-24 01:32:08,,0,,<p>Looks to me like a sequence labeling proble...,64377,...,,,2019-06-24 01:32:08,,,,2,,,
40,54358,2,,54341,2019-06-24 01:44:40,,1,,"<p>I don't think you need any ML, in the best ...",64377,...,,,2019-06-24 01:44:40,,,,6,,,
42,54360,2,,53995,2019-06-24 03:18:01,,0,,<p>According to all answers(Thank you) and my ...,43765,...,,,2019-06-24 03:18:01,,,,0,,,
43,54361,2,,46624,2019-06-24 03:21:13,,0,,<p><strong>weight for each node?</strong> <sp...,74421,...,,2019-06-24 03:27:31,2019-06-24 03:27:31,,,,0,,,
46,54365,2,,54364,2019-06-24 06:29:01,,0,,<p>Your question needs a wide explanation.</p>...,73441,...,,2019-06-24 10:02:41,2019-06-24 10:02:41,,,,0,,,
51,54371,2,,54369,2019-06-24 08:52:21,,0,,<p>I'm assuming you understand the original ga...,75738,...,,,2019-06-24 08:52:21,,,,3,,,
52,54373,2,,54341,2019-06-24 09:20:21,,1,,<p>agree with Erwan! Let say you can use regex...,37572,...,,,2019-06-24 09:20:21,,,,0,,,
55,54376,2,,54296,2019-06-24 09:44:46,,6,,"<p>As the other answers previously said, in pr...",34269,...,,,2019-06-24 09:44:46,,,,0,,,
57,54378,2,,54377,2019-06-24 09:56:38,,6,,"<p>You have already computed that, but you've ...",28175,...,,2019-06-24 12:09:20,2019-06-24 12:09:20,,,,0,,,
62,54383,2,,54296,2019-06-24 11:13:00,,2,,<p>In addition to just initialization (as the ...,47371,...,,,2019-06-24 11:13:00,,,,0,,,
64,54385,2,,53478,2019-06-24 11:54:17,,1,,"<p>Consider using the <a href=""https://en.wiki...",47371,...,,,2019-06-24 11:54:17,,,,0,,,
68,54389,2,,54386,2019-06-24 13:03:43,,1,,<p>Use <code>sklearn.preprocessing.OneHotEncod...,69822,...,,,2019-06-24 13:03:43,,,,0,,,
70,54391,2,,54390,2019-06-24 13:30:36,,2,,<p>There are <strong>feature learning algorith...,69822,...,,,2019-06-24 13:30:36,,,,0,,,
71,54392,2,,54390,2019-06-24 14:05:02,,5,,<h3>In short</h3>\n\n<p>The classification is ...,34269,...,,,2019-06-24 14:05:02,,,,0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43600,14171,2,,14152,2016-09-23 08:38:41,,4,,<p>Your training and test errors are affected ...,2576,...,,,2016-09-23 08:38:41,,,,0,,,
43602,14173,2,,14167,2016-09-23 10:42:56,,2,,"<p>This can happen, but only with very small a...",23911,...,,,2016-09-23 10:42:56,,,,0,,,
43604,14175,2,,9480,2016-09-23 15:52:05,,1,,<p>I have had to perform that type of operatio...,12527,...,,2018-03-30 14:41:58,2018-03-30 14:41:58,,,,0,,,
43605,14176,2,,14165,2016-09-23 17:27:01,,1,,"<p>Yes, most software implementations of trees...",12515,...,,,2016-09-23 17:27:01,,,,0,,,
43606,14177,2,,14172,2016-09-23 19:13:09,,2,,<p><strong>Binning</strong></p>\n\n<p>One easy...,2724,...,,2016-09-23 19:19:40,2016-09-23 19:19:40,,,,2,,,
43609,14182,2,,14179,2016-09-24 04:10:42,,1,,"<p>The magic word is ""<a href=""http://pandas.p...",381,...,,2016-10-01 18:29:32,2016-10-01 18:29:32,,,,4,,,
43610,14183,2,,14181,2016-09-24 05:11:13,,0,,<p>Which normalization function to use and whe...,24409,...,,2017-04-13 12:44:20,2016-09-24 05:11:13,,,,0,,,
43614,14194,2,,14187,2016-09-24 13:50:41,,26,,<p>Hyperparameters and parameters are often us...,15412,...,,2018-12-06 04:56:57,2018-12-06 04:56:57,,,,1,,,
43615,14195,2,,14184,2016-09-24 13:56:28,,1,,<p>You may or may not apply neural network to ...,15412,...,,,2016-09-24 13:56:28,,,,0,,,
43616,14197,2,,14184,2016-09-24 16:50:28,,1,,"<p>Before deciding on the model, I would recom...",18540,...,,,2016-09-24 16:50:28,,,,1,,,
43618,14199,2,,14198,2016-09-24 18:04:58,,2,,"<p>Yes, as demonstrated in the documentation: ...",381,...,,,2016-09-24 18:04:58,,,,1,,,
43619,14200,2,,14161,2016-09-24 18:55:11,,1,,"<p>I believe this is the answer: <a href=""http...",9053,...,,,2016-09-24 18:55:11,,,,0,,,
43620,14201,2,,14184,2016-09-24 19:07:03,,1,,<p>The basics of machine learning is this. Is...,24649,...,,,2016-09-24 19:07:03,,,,0,,,
43623,14204,2,,14203,2016-09-25 11:57:31,,0,,"<p>I don't know this particular dataset, but t...",23122,...,,,2016-09-25 11:57:31,,,,0,,,
43625,14206,2,,14203,2016-09-25 13:17:43,,0,,<p>This is most likely a database file. You ca...,15412,...,,,2016-09-25 13:17:43,,,,0,,,
43626,14207,2,,14202,2016-09-25 13:21:24,,1,,<p>There are many but some of the resources ar...,15412,...,,,2016-09-25 13:21:24,,,,0,,,
43628,14210,2,,14208,2016-09-25 16:10:21,,3,,"<p>""Zero-meaned"" means the vector has been tra...",12876,...,,2016-09-25 16:12:04,2016-09-25 16:12:04,,,,2,,,
43629,14211,2,,14208,2016-09-25 16:10:36,,2,,<p>Mean centering is one of many related techn...,11098,...,,,2016-09-25 16:10:36,,,,1,,,
43630,14212,2,,13629,2016-09-25 16:35:11,,1,,<p>The weights learned have no straightforward...,11098,...,,2017-03-10 09:42:41,2016-09-25 16:43:16,,,,1,,,
43631,14214,2,,14203,2016-09-25 18:41:03,,1,,"<p>It's an SFrame, not a CSV; you need GraphLa...",381,...,,,2016-09-25 18:41:03,,,,0,,,
43633,14217,2,,14216,2016-09-25 21:19:26,,1,,<p>You can do a log transformation on your dat...,15412,...,,2017-05-23 12:38:53,2016-09-25 21:19:26,,,,2,,,
43635,14221,2,,14220,2016-09-26 07:55:32,,3,,<p>I think what you're seeing is normal behavi...,676,...,,2016-09-26 08:26:44,2016-09-26 08:26:44,,,,2,,,
43638,14224,2,,13587,2016-09-26 14:45:10,,5,,<blockquote>\n <p>If this is correct then eve...,23416,...,,2016-09-26 14:54:02,2016-09-26 14:54:02,,,,0,,,
43639,14225,2,,11693,2016-09-26 15:04:11,,0,,<p>Just averaging them might not be good becau...,23416,...,,,2016-09-26 15:04:11,,,,1,,,
43641,14227,2,,14226,2016-09-26 19:21:48,,1,,<p>The different layers you describe can all h...,836,...,,2016-09-26 19:29:16,2016-09-26 19:29:16,,,,1,,,
43643,14229,2,,14112,2016-09-26 23:42:24,,1,,<p>You could define a window (distance between...,23305,...,,,2016-09-26 23:42:24,,,,2,,,
43645,14232,2,,14231,2016-09-27 06:16:53,,2,,<p>There are two approaches that can be taken:...,836,...,,2016-09-27 07:04:51,2016-09-27 07:04:51,,,,12,,,
43647,14234,2,,14187,2016-09-27 08:43:52,,20,,<p>In addition to the answer above.</p>\n\n<p>...,22012,...,,,2016-09-27 08:43:52,,,,0,,,
43648,14235,2,,11699,2016-09-27 09:08:15,,6,,<p><strong>Max Pooling</strong></p>\n\n<p>So s...,23416,...,,,2016-09-27 09:08:15,,,,0,,,
43649,14236,2,,14223,2016-09-27 10:10:40,,1,,<p>These learning curves seem unusual - the tr...,676,...,,,2016-09-27 10:10:40,,,,3,,,

In [170]:
tmpid

       tempqid
53       54374
56       54377
65       54386
84       54407
90       54413
109      54436
122         19
205        116
230      23969
241      23990
369      14355
391      14385
400      44155
429      44192
452      44219
457      44224
476      44246
540      34038
541      34039
549      34052
557      34069
560      34072
572      34088
615      14406
632      14429
637      14435
652      14457
653      14458
661      14467
748      34181
...        ...
42824    33766
42834    33780
42865    13550
42878    13567
42890    13580
42934    13633
43009    54210
43028    33836
43048    33863
43051    33868
43061    33879
43080    33910
43130    13701
43150    13730
43165    13749
43232    54273
43259    33928
43277    33958
43348    13818
43378    13868
43395    13894
43405    13907
43406    13909
43465    13992
43484    14021
43506    14046
43522    14072
43545    14102
43597    14165
43607    14179

[1585 rows x 1 columns]

In [180]:
 pd.to_numeric(dfDSAns['ParentId'], downcast='integer')

0        54237
1        54293
5        54281
10       53478
14       54263
15       54292
16       54313
18       54327
19       54273
21       54320
25       54337
28       44800
29       54343
32       26009
33       54346
38       54352
39       54351
40       54341
42       53995
43       46624
46       54364
51       54369
52       54341
55       54296
57       54377
62       54296
64       53478
68       54386
70       54390
71       54390
         ...
43600    14152
43602    14167
43604     9480
43605    14165
43606    14172
43609    14179
43610    14181
43614    14187
43615    14184
43616    14184
43618    14198
43619    14161
43620    14184
43623    14203
43625    14203
43626    14202
43628    14208
43629    14208
43630    13629
43631    14203
43633    14216
43635    14220
43638    13587
43639    11693
43641    14226
43643    14112
43645    14231
43647    14187
43648    11699
43649    14223
Name: ParentId, Length: 22666, dtype: int32

In [181]:
# let's drop any answers that do not have corresponding questions in our questions dataframe
tmpid=pd.DataFrame(dfDSQues['Id']) # temporary dataframe to hold ids from questions for merge operation
tmpid.columns=['tempqid']
dfDSAns=pd.merge(dfDSAns, tmpid, how='inner',left_on=pd.to_numeric(dfDSAns['ParentId'], downcast='integer'),right_on='tempqid')
del dfDSAns['tempqid']
del tmpid

In [183]:
np.shape(dfDSAns)

(2410, 22)

In [184]:
# check the answer body of each answer and extract the images references into a separate column as a list
def extract_image_references(body):
    tmp_body=BeautifulSoup(body,"lxml")
    timgs=[]
    for img in tmp_body('img'):
        timgs.append(img)
    return timgs

sttime=time.time()    

dfDSAns['images_list']=''

dfDSAns['images_list'] = dfDSAns['Body'].map(extract_image_references)
print('images finished in',(time.time()-sttime)/60,'minutes')

images finished in 0.018283510208129884 minutes

In [185]:
# check the answer body of each answer and extract the code snippets into a separate column as a list
def extract_code_snippets(body):
    tmp_body=BeautifulSoup(body,"lxml")
    tcode_snips=[]
    for code in tmp_body('code'):
        tcode_snips.append(code)
    return tcode_snips

sttime=time.time()    

dfDSAns['code_snippets']=''

dfDSAns['code_snippets'] = dfDSAns['Body'].map(extract_code_snippets)
print('code snippets finished in',(time.time()-sttime)/60,'minutes')

code snippets finished in 0.0185501495997111 minutes

In [187]:
# create a separate 'cleaned_body' column from the answer 'body' column with all code and all html tags removed
def clean_body_text(body):
    tmp_body=BeautifulSoup(body,"lxml")
    for code in tmp_body('code'):
        code.replace_with('')
    tstr=''
    for string in tmp_body.stripped_strings:
        tstr = tstr + ' ' + string
    return tstr

dfDSAns['cleaned_body']=''

sttime=time.time()    
dfDSAns['cleaned_body'] = dfDSAns['Body'].map(clean_body_text)
print('body cleaned in',(time.time()-sttime)/60,'minutes')

body cleaned in 0.01733266512552897 minutes

In [188]:
dfDSAns['Body'].head()

0    <p>As We should not remove any data ... we can...
1    <p>Consider using the <a href="https://en.wiki...
2    <p>You could take an <a href="https://en.wikip...
3    <p>Did you try keeping a separate test set (on...
4    <p>From the curves you are showing <strong>yes...
Name: Body, dtype: object

In [189]:
dfDSAns['cleaned_body'].head()

0     As We should not remove any data ... we can u...
1     Consider using the Earth Mover's Distance (i....
2     You could take an Information Theory approach...
3     Did you try keeping a separate test set (on t...
4     From the curves you are showing yes . Over-fi...
Name: cleaned_body, dtype: object

In [190]:
dfDSAns['images_list'].head()

0    []
1    []
2    []
3    []
4    []
Name: images_list, dtype: object

In [191]:
dfDSAns['code_snippets'].head()

0    [<code> import numpy as np
 import pandas ...
1                                                   []
2    [<code>&gt;&gt;&gt; from scipy.stats import en...
3                                                   []
4                                                   []
Name: code_snippets, dtype: object

In [192]:
# add an image count column to the answers so that we can filter on answers with images
def countimages(image_list):
    if image_list == []:
        return 0
    else:
        return len(image_list)
    
dfDSAns['images_count']=0
dfDSAns['images_count'] = dfDSAns['images_list'].map(countimages)

In [193]:
dfDSAns['images_count'][dfDSAns['images_count'] > 0].head()

18    2
33    1
45    1
54    1
56    1
Name: images_count, dtype: int64

In [195]:
dfDSAns['Id'][dfDSAns['images_count'] > 0].count()

197

In [196]:
# write the dataframe to a tsv
dfDSAns.to_csv("data/stackoverflow/DataSciAns_parsed.tsv", sep='\t', index=False)

In [22]:
# USE THIS CODE TO LOAD THE DATA SCIENCE ANSWERS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfDSAns = pd.read_csv("data/stackoverflow/DataSciAns_parsed.tsv", sep='\t', keep_default_na=False)

In [23]:
dfDSAns

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,images_list,code_snippets,cleaned_body,images_count
0,54319,2,,53478,2019-06-23 05:23:02,,1,,<p>As We should not remove any data ... we can...,76129,...,,,0,,,,[],[<code> import numpy as np \r\n import pand...,As We should not remove any data ... we can u...,0
1,54385,2,,53478,2019-06-24 11:54:17,,1,,"<p>Consider using the <a href=""https://en.wiki...",47371,...,,,0,,,,[],[],Consider using the Earth Mover's Distance (i....,0
2,54256,2,,53478,2019-06-21 21:55:54,,5,,"<p>You could take an <a href=""https://en.wikip...",1330,...,,,2,,,,[],[<code>&gt;&gt;&gt; from scipy.stats import en...,You could take an Information Theory approach...,0
3,54329,2,,54273,2019-06-23 11:18:15,,0,,<p>Did you try keeping a separate test set (on...,66788,...,,,0,,,,[],[],Did you try keeping a separate test set (on t...,0
4,54276,2,,54273,2019-06-22 08:10:13,,4,,<p>From the curves you are showing <strong>yes...,34269,...,,,6,,,,[],[],From the curves you are showing yes . Over-fi...,0
5,54298,2,,54273,2019-06-22 17:01:05,,-4,,<p><strong>Over-fitting happens when validatio...,71675,...,,,0,,,,[],[],Over-fitting happens when validation accuracy...,0
6,54378,2,,54377,2019-06-24 09:56:38,,6,,"<p>You have already computed that, but you've ...",28175,...,,,0,,,,[],"[<code>result = np.linalg.norm(v1,ord=2,axis=1...","You have already computed that, but you've no...",0
7,54389,2,,54386,2019-06-24 13:03:43,,1,,<p>Use <code>sklearn.preprocessing.OneHotEncod...,69822,...,,,0,,,,[],[<code>sklearn.preprocessing.OneHotEncoder</co...,Use for example and transfer the one-hot enco...,0
8,54418,2,,54413,2019-06-25 02:38:07,,3,,<p>Any scalar multiple of an eigenvector is al...,55122,...,,,4,,,,[],[],Any scalar multiple of an eigenvector is also...,0
9,54419,2,,54407,2019-06-25 02:38:11,,0,,<p>If you treat this problem as a time-series ...,76540,...,,,1,,,,[],[],If you treat this problem as a time-series on...,0
10,21,2,,19,2014-05-14 05:44:29,,33,,"<p>As you rightly note, these days ""big data"" ...",14,...,,,1,,,,[],[],"As you rightly note, these days ""big data"" is...",0
11,25,2,,19,2014-05-14 07:26:04,,7,,"<p>Big Data is defined by the volume of data, ...",104,...,,,0,,,,[],[],"Big Data is defined by the volume of data, th...",0
12,30,2,,19,2014-05-14 08:03:28,,21,,<p>Total amount of data in the world: 2.8 zeta...,26,...,,,3,,,,[],[],Total amount of data in the world: 2.8 zetaby...,0
13,37,2,,19,2014-05-14 10:41:23,,86,,<p>To me (coming from a relational database ba...,9,...,,,4,,,,[],[],To me (coming from a relational database back...,0
14,15353,2,,19,2016-11-25 22:34:51,,4,,"<p>Data is ""Big Data"" if it is of such volume ...",484,...,,,0,,,,[],[],"Data is ""Big Data"" if it is of such volume th...",0
15,2320,2,,19,2014-10-20 19:40:34,,13,,<p>To me Big Data is primarily about the tools...,4730,...,,,0,,,,[],[],To me Big Data is primarily about the tools (...,0
16,3697,2,,19,2014-12-12 22:48:41,,10,,"<p>Data becomes ""big"" when a single <a href=""h...",6391,...,,,0,,,,[],[],"Data becomes ""big"" when a single commodity co...",0
17,8708,2,,19,2015-11-04 08:11:37,,4,,<p>I think that big data starts at the point w...,13727,...,,,1,,,,[],[],I think that big data starts at the point whe...,0
18,8733,2,,19,2015-11-06 02:18:46,,6,,<p>I'll share what Big Data is like in genomic...,9123,...,,,0,,,,"[<img alt=""enter image description here"" src=""...",[],"I'll share what Big Data is like in genomics,...",2
19,10653,2,,19,2016-03-11 06:31:47,,1,,<p>I tend to agree with what @Dan Levin has al...,13686,...,,,0,,,,[],[],I tend to agree with what @Dan Levin has alre...,0
20,12146,2,,19,2016-06-10 06:31:49,,5,,"<p>There is special thing to graph algorithms,...",14073,...,,,0,,,,[],[],"There is special thing to graph algorithms, y...",0
21,13319,2,,19,2016-08-09 06:35:31,,1,,"<p>""Big data"" is literally just a lot of data....",23241,...,,,0,,,,[],[],"""Big data"" is literally just a lot of data. W...",0
22,121,2,,116,2014-05-17 18:53:30,,16,,<p>One thing to start off with would be k-NN. ...,92,...,,,2,,,,[],[],One thing to start off with would be k-NN. T...,0
23,174,2,,116,2014-05-20 09:24:30,,5,,"<p>Another suggestion is to test the <a href=""...",172,...,,,5,,,,[],[<code>penalty='l1'</code>],Another suggestion is to test the logistic re...,0
24,204,2,,116,2014-05-23 19:28:01,,7,,<p>I recently did a similar project in Python ...,250,...,,,2,,,,[],[],I recently did a similar project in Python (p...,0
25,574,2,,116,2014-06-25 07:22:33,,2,,<p>This is a very interesting problem.</p>\r\n...,1155,...,,,0,,,,[],[],This is a very interesting problem. I faced a...,0
26,582,2,,116,2014-06-25 14:43:53,,4,,"<p>Some research from <a href=""http://www.dong...",743,...,,,0,,,,[],[],Some research from D. Nguyen et al. try to pr...,0
27,3757,2,,116,2014-12-24 13:46:47,,3,,<p>Apart from the fancier methods you could tr...,6550,...,,,0,,,,[],[],Apart from the fancier methods you could try ...,0
28,23984,2,,23927,2017-10-22 19:50:02,,2,,<p>There are critcism's of Tuft's principles. ...,29575,...,,,0,,,,[],[],There are critcism's of Tuft's principles. S...,0
29,23992,2,,23990,2017-10-23 04:21:11,,2,,<ol>\r\n<li><p>Answering this in terms of NLP ...,21608,...,,,4,,,,[],[],Answering this in terms of NLP examples is qu...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,13440,2,,13436,2016-08-16 04:33:44,,0,,<p>SPSS has an AUTORECODE command which will d...,18022,...,,,1,,,,[],[<code>AUTORECODE vr1 to vr100 /into Kvr1 to K...,SPSS has an AUTORECODE command which will do ...,0
2381,13443,2,,13436,2016-08-16 07:39:14,,1,,<p>In R you turn your categorical value into a...,14588,...,,,0,,,,[],[<code>dfr$id = as.numeric(factor(dfr$mycolumn...,In R you turn your categorical value into a f...,0
2382,13503,2,,13409,2016-08-17 18:49:28,,0,,<p>Say your data is in a DataFrame <code>df</c...,23495,...,,,2,,,,[],"[<code>df</code>, <code>column</code>, <code>t...","Say your data is in a DataFrame , and the col...",0
2383,13527,2,,13409,2016-08-18 15:09:27,,0,,<p>Using the notation you gave (i.e. <code>dat...,23283,...,,,1,,,,[],"[<code>data</code>, <code>data.class</code>, <...",Using the notation you gave (i.e. is the data...,0
2384,33760,2,,33725,2018-06-28 11:23:39,,2,,<p>If you goal is simply to halve the size of ...,45264,...,,,1,,,,[],"[<code>pad</code>, <code>mode</code>, <code>fr...",If you goal is simply to halve the size of yo...,0
2385,33771,2,,33766,2018-06-28 14:24:34,,1,,<p>NumPy performs operations in a vectorised m...,32320,...,,,2,,,,[],[<code>np.argwhere( (test == 1) &amp; np.roll(...,NumPy performs operations in a vectorised man...,0
2386,13575,2,,13567,2016-08-20 14:09:22,,23,,<p>Lat long coordinates have a problem that th...,14904,...,,,3,,,,[],[<code>x = cos(lat) * cos(lon)\r\ny = cos(lat)...,Lat long coordinates have a problem that they...,0
2387,13582,2,,13580,2016-08-20 20:56:40,,1,,<p><code>train_test_split</code> is just a uti...,13714,...,,,0,,,,[],"[<code>train_test_split</code>, <code>ShuffleS...","is just a utility function around , which on ...",0
2388,13635,2,,13633,2016-08-24 09:15:29,,1,,"<p>To debug this case, I suggest you try the f...",18540,...,,,0,,,,[],[],"To debug this case, I suggest you try the fol...",0
2389,33852,2,,33836,2018-07-01 15:48:43,,1,,"<p>So, I figured it out. The problem was the l...",54401,...,,,0,,,,[],[<code>mean_squared</code>],"So, I figured it out. The problem was the los...",0
2390,33867,2,,33863,2018-07-02 09:08:31,,1,,<p>This is a classic case of recommendation pr...,53582,...,,,1,,,,[],[],This is a classic case of recommendation prob...,0
2391,33870,2,,33868,2018-07-02 09:47:04,,0,,<p>There is a method that can handle multiple ...,45064,...,,,0,,,,[],[],There is a method that can handle multiple ty...,0
2392,33882,2,,33879,2018-07-02 11:11:35,,4,,"<p>It is sorting, but it doesn't know that it ...",54246,...,,,1,,,,[],"[<code>datetime</code>, <code>January</code>, ...","It is sorting, but it doesn't know that it is...",0
2393,33886,2,,33879,2018-07-02 13:51:47,,6,,<pre><code># make a month column to preserve t...,31571,...,,,0,,,,[],[<code># make a month column to preserve the o...,,0
2394,54219,2,,54210,2019-06-21 12:41:55,,0,,<p>What you want to do to boost the performanc...,34269,...,,,1,,,,[],[<code>from sklearn.utils.class_weight import ...,What you want to do to boost the performance ...,0
2395,33925,2,,33910,2018-07-03 10:21:39,,6,,<p>You are supposed to pass <code>numpy</code>...,54246,...,,,1,,,,[],"[<code>numpy</code>, <code>DecisionTree</code>...",You are supposed to pass arrays and not lists...,0
2396,33929,2,,33928,2018-07-03 11:16:21,,3,,<p><code>ValueError: Error when checking input...,54246,...,,,2,,,,[],[<code>ValueError: Error when checking input: ...,it clearly says that while preprocessing that...,0
2397,33963,2,,33958,2018-07-04 02:10:39,,0,,<p>I found an answer that actually ended up he...,50899,...,,,0,,,,[],[<code>import importlib\r\npackage='spacy'\r\n...,I found an answer that actually ended up help...,0
2398,13777,2,,13749,2016-08-31 10:01:00,,0,,"<p>Since you are using Spark 1.6, I'd rather d...",5177,...,,,0,,,,[],[<code>import sqlContext.implicits._ // not ne...,"Since you are using Spark 1.6, I'd rather do ...",0
2399,13869,2,,13868,2016-09-06 05:39:23,,3,,<p>It is unclear if you are requesting AUC of ...,24000,...,,,0,,,,[],"[<code>auc</code>, <code>precision_recall_curv...",It is unclear if you are requesting AUC of RO...,0
2400,13916,2,,13907,2016-09-09 12:32:37,,1,,<p>I solved this issue. There is a parameter f...,13518,...,,,0,,,,[],[],I solved this issue. There is a parameter for...,0
2401,13994,2,,13992,2016-09-14 13:27:32,,0,,<p>You should broadcast your variable.</p>\r\n...,24320,...,,,1,,,,[],[<code>import org.apache.spark.SparkContext\r\...,You should broadcast your variable.,0
2402,14000,2,,13992,2016-09-14 18:47:28,,3,,"<p>Looking at <a href=""https://stackoverflow.c...",23581,...,,,0,,,,[],[<code>SparkContext</code>],Looking at another question on Stack Overflow...,0
2403,14008,2,,13992,2016-09-15 07:00:20,,2,,<p>I changed my code to this:</p>\r\n\r\n<pre>...,24157,...,,,0,,,,[],[<code>import org.apache.spark.SparkContext\r\...,I changed my code to this: Now when it will g...,0
2404,14003,2,,13909,2016-09-14 20:40:29,,0,,<p>This wouldn't be possible in seaborn withou...,19161,...,,,0,,,,[],"[<code>if kind == ""scatter"":\r\n plot_kws.s...",This wouldn't be possible in seaborn without ...,0
2405,14022,2,,14021,2016-09-15 17:16:02,,13,,"<p>For small data, I think <a href=""http://pan...",381,...,,,2,,,,[],[],"For small data, I think pandas.read_csv is th...",0
2406,14023,2,,14021,2016-09-15 17:16:11,,4,,<p>Use pandas library: </p>\r\n\r\n<pre><code>...,24225,...,,,0,,,,[],[<code>import pandas as pd \r\npd.read_csv('fo...,Use pandas library: Pandas identify the heade...,0
2407,14024,2,,14021,2016-09-15 21:11:00,,0,,"<p>You can also SFrame. First <a href=""https:/...",8517,...,,,2,,,,[],[<code>import graphlab as gl\r\ndata = gl.SFra...,You can also SFrame. First install graph lab ...,0
2408,14080,2,,14072,2016-09-19 07:04:48,,1,,<p>Use this syntax:</p>\r\n\r\n<pre><code>val ...,18540,...,,,0,,,,[],[<code>val joinedDF = students_positive_grande...,Use this syntax:,0
2409,14176,2,,14165,2016-09-23 17:27:01,,1,,"<p>Yes, most software implementations of trees...",12515,...,,,0,,,,[],[],"Yes, most software implementations of trees w...",0

In [24]:
# let's check to see if there duplicate ids in the Stack Overflow and Data Science Stack Exchange datasets before
# combining them
tsoquesids=pd.DataFrame(dfPostQuestionsFiltered['id'])
tsoansids=pd.DataFrame(dfPostAnswersFiltered['id'])
tdsquesids=pd.DataFrame(dfDSQues['Id'])
tdsansids=pd.DataFrame(dfDSAns['Id'])
tmergeques=pd.merge(tsoquesids, tdsquesids, how='inner', left_on='id', right_on='Id')
tmergeans=pd.merge(tsoansids, tdsansids, how='inner', left_on='id', right_on='Id')

In [25]:
tmergeques

      id     Id
0  58649  58649

In [26]:
tmergeans

      id     Id
0  24943  24943
1  52921  52921
2  57408  57408
3  43239  43239
4   2517   2517
5   6087   6087
6  51804  51804
7  14525  14525
8  26700  26700
9  33886  33886

In [18]:
print('length of dataframes without dropping duplicate Ids -- SO ques:',len(dfPostQuestionsFiltered), 'DS ques', len(dfDSQues),'SO ans:',len(dfPostAnswersFiltered), 'DS ans', len(dfDSAns) )

length of dataframes without dropping duplicate Ids -- SO ques: 173698 DS ques 1585 SO ans: 261052 DS ans 2410

In [28]:
# dropping questions with duplicate ids from the Stack Overflow and data science question sets
# also dropping answers that refer back to those duplicate questions
# note: we do not drop answers that happen to have duplicate ids as the risk of getting bad return results
# in our models is minimal for duplicate answers, espcially given the small number of duplicate answer ids
qidstodrop=tmergeques['Id'].values.tolist()
print('duplicate question Ids to be dropped:',qidstodrop)

duplicate question Ids to be dropped: [58649]

In [33]:
for dupqid in qidstodrop:
    
    SOanswithdupqids=dfPostAnswersFiltered['id'][dfPostAnswersFiltered['parent_id']==dupqid].index
    print('dropping',len(SOanswithdupqids),'answers from SO answers that have question parent id =',dupqid)
    dfPostAnswersFiltered.drop(labels=SOanswithdupqids,inplace=True)
    
    DSanswithdupqids=dfDSAns['Id'][dfDSAns['ParentId']==dupqid].index
    print('dropping',len(DSanswithdupqids),'answers from DS answers that have question parent id =',dupqid)
    dfDSAns.drop(labels=DSanswithdupqids,inplace=True)

    print('dropping quesion from SO that has question =',dupqid)
    dfPostQuestionsFiltered.drop(labels=dfPostQuestionsFiltered[dfPostQuestionsFiltered['id']==dupqid].index,inplace=True)

    print('dropping quesion from DS that has question =',dupqid)
    dfDSQues.drop(labels=dfDSQues[dfDSQues['Id']==dupqid].index,inplace=True)

dropping 7 answers from SO answers that have question parent id = 58649
dropping 1 answers from DS answers that have question parent id = 58649
dropping quesion from SO that has question = 58649
dropping quesion from DS that has question = 58649

In [34]:
print('length of dataframes after dropping duplicate question Ids -- SO ques:',len(dfPostQuestionsFiltered), 'DS ques', len(dfDSQues),'SO ans:',len(dfPostAnswersFiltered), 'DS ans', len(dfDSAns) )

length of dataframes after dropping duplicate question Ids -- SO ques: 173697 DS ques 1584 SO ans: 261045 DS ans 2409

In [35]:
dfPostAnswersFiltered.columns

Index(['id', 'title', 'body', 'accepted_answer_id', 'answer_count',
       'comment_count', 'community_owned_date', 'creation_date',
       'favorite_count', 'last_activity_date', 'last_edit_date',
       'last_editor_display_name', 'last_editor_user_id', 'owner_display_name',
       'owner_user_id', 'parent_id', 'post_type_id', 'score', 'tags',
       'view_count', 'images_list', 'code_snippets', 'cleaned_body',
       'images_count'],
      dtype='object')

In [36]:
dfDSAns.columns

Index(['Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId', 'CreationDate',
       'DeletionDate', 'Score', 'ViewCount', 'Body', 'OwnerUserId',
       'OwnerDisplayName', 'LastEditorUserId', 'LastEditorDisplayName',
       'LastEditDate', 'LastActivityDate', 'Title', 'Tags', 'AnswerCount',
       'CommentCount', 'FavoriteCount', 'ClosedDate', 'CommunityOwnedDate',
       'images_list', 'code_snippets', 'cleaned_body', 'images_count'],
      dtype='object')

In [37]:
# drop the columns in the data science answers that are not also in the Stack Overflow answers before merging both
del dfDSAns['DeletionDate']
del dfDSAns['ClosedDate']

In [38]:
# change the column names in data science answers dataset to match those in the Stack Overflow answers dataset
dfDSAns.columns = ['id', 'post_type_id', 'accepted_answer_id', 'parent_id', 'creation_date', 'score', 
                   'view_count', 'body', 'owner_user_id', 'owner_display_name', 'last_editor_user_id', 
                   'last_editor_display_name', 'last_edit_date', 'last_activity_date', 'title', 'tags',
                   'answer_count', 'comment_count', 'favorite_count', 'community_owned_date', 
                   'images_list', 'code_snippets', 'cleaned_body', 'images_count']

In [39]:
dfCombinedAns=dfPostAnswersFiltered.append(dfDSAns,ignore_index=True)

C:\Users\jeffb\Anaconda3\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

In [40]:
dfCombinedAns

,accepted_answer_id,answer_count,body,cleaned_body,code_snippets,comment_count,community_owned_date,creation_date,favorite_count,id,...,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,title,view_count
0,,,<p>The correct syntax is this one:</p>\r\r\n\r...,The correct syntax is this one: It is working...,[<code>plugin install com.graphaware.es/graph-...,0,,2017-06-19 13:43:45.580000+00:00,,44632276,...,,,,5222773.0,43895941,2,0,,,
1,,,<p>You can download the plugin manually from t...,You can download the plugin manually from the...,[],13,,2017-05-12 09:28:09.857000+00:00,,43934125,...,,,,2662355.0,43895941,2,1,,,
2,,,<p>You can define the lines from the dataset w...,You can define the lines from the dataset wit...,"[<code>mapping.get(i, ""anchor""),\r\r\n</code>]",0,,2017-06-19 13:51:27.790000+00:00,,44632434,...,,,,3951036.0,44621561,2,0,,,
3,,,<p>The way matplotlib is working is that you h...,The way matplotlib is working is that you hav...,"[<code>def error_plot(ax, title, x_data, y_dat...",0,,2017-06-19 14:47:46.830000+00:00,,44633649,...,,,,4124317.0,44633422,2,0,,,
4,,,"<p>I have figured out the answer, which is to ...","I have figured out the answer, which is to us...","[<code>%sql select t1.time, t1.value,coalesce(...",0,,2017-06-19 14:48:42.900000+00:00,,44633675,...,,,,8050923.0,44624707,2,0,,,
5,,,<p>To further a_guest answer - To enable see t...,To further a_guest answer - To enable see the...,[],0,,2017-06-19 15:56:06.457000+00:00,,44635048,...,,,,1704227.0,44632018,2,0,,,
6,,,<p>The problem is that the Python process fini...,The problem is that the Python process finish...,"[<code>for</code>, <code>-i</code>, <code>pyth...",3,,2017-06-19 14:12:13.690000+00:00,,44632901,...,,,,3767239.0,44632018,2,2,,,
7,,,<p>You can keep the window open by creating a ...,You can keep the window open by creating a at...,"[<code>QApplication</code>, <code>exec_()</cod...",0,,2018-04-23 15:59:00.010000+00:00,,49985313,...,,,,6605826.0,44632018,2,1,,,
8,,,<p>Since you've mentioned that the transformat...,Since you've mentioned that the transformatio...,[<code>lambda=3.79\r\r\nm2=lm(resp^((lambda-1)...,0,,2017-06-19 17:10:08.570000+00:00,,44636285,...,,,,8060278.0,18506201,2,0,,,
9,,,"<pre><code>plotexpl &lt;- seq(1,4,length.out=1...",I won't discuss the statistical issues here (...,"[<code>plotexpl &lt;- seq(1,4,length.out=10)\r...",3,,2013-08-29 09:24:47.800000+00:00,,18507004,...,,,,1412059.0,18506201,2,2,,,
10,,,<p>What range/data is selected at the time the...,What range/data is selected at the time the c...,"[<code>Sub make_chart(Fam, Data, Row_Start)\r\...",0,,2017-06-19 17:22:09.553000+00:00,,44636462,...,,,,478884.0,44632742,2,0,,,
11,,,<blockquote>\r\r\n <p>other times they genera...,other times they generate with both series an...,"[<code>region</code>, <code>ChartArea.Clear</c...",0,,2017-06-19 18:10:38.517000+00:00,,44637233,...,,4926357.0,,4926357.0,44632742,2,0,,,
12,,,<p>Well I did this by simply copy the texture ...,Well I did this by simply copy the texture pi...,[<code>// [constants]\r\r\nconst int sxs=128; ...,0,,2017-06-19 18:31:54.673000+00:00,,44637579,...,,2521214.0,,2521214.0,44619304,2,0,,,
13,,,<p>Big thanks to Spektre for all the effort he...,Big thanks to Spektre for all the effort he m...,[<code>import pygame\r\r\n\r\r\nfrom pygame.lo...,0,,2017-06-20 17:11:16.137000+00:00,,44659255,...,,8125567.0,,8125567.0,44619304,2,1,,,
14,,,<p>You don't appear to be using <code>mlt.text...,You don't appear to be using correctly. See t...,"[<code>mlt.text()</code>, <code>text()</code>,...",0,,2017-06-19 19:39:24.230000+00:00,,44638617,...,,,,5548599.0,44638406,2,0,,,
15,,,<p>Python turtle was designed to either be emb...,Python turtle was designed to either be embed...,[<code>from random import randint\r\r\nfrom tk...,0,,2017-06-19 20:06:46.950000+00:00,,44639041,...,,,,5771269.0,44634947,2,0,,,
16,,,"<p>thank you for your attention, i did solve i...","thank you for your attention, i did solve it ...",[],0,,2017-06-20 01:07:20.283000+00:00,,44642203,...,,,,3341452.0,44555246,2,0,,,
17,,,<p>I spent whole day implementing it. My main ...,I spent whole day implementing it. My main cr...,[],0,,2017-06-20 06:28:56.110000+00:00,,44645398,...,,,,1328863.0,10042786,2,0,,,
18,,,"<p>This may be a bit late for the OP, but ther...","This may be a bit late for the OP, but there ...",[],0,,2017-07-10 14:33:11.160000+00:00,,45014838,...,,,,400086.0,10042786,2,1,,,
19,,,"<p>This answer I found on <a href=""https://dev...",This answer I found on LinkedIn forums might ...,"[<code>&lt;meta prefix=""og: http://ogp.me/ns#""...",6,,2014-08-02 08:44:30.170000+00:00,,25093272,...,,1145388.0,,2474507.0,10042786,2,32,,,
20,,,<p>I found this simple fix which worked for me...,I found this simple fix which worked for me a...,[],1,,2017-10-09 08:10:02.483000+00:00,,46641594,...,,,,8744596.0,10042786,2,7,,,
21,,,"<p>Have you tried adding <code>prefix=""og: htt...",Have you tried adding to the HTML tag?,"[<code>prefix=""og: http://ogp.me/ns#""</code>]",0,,2012-07-04 15:30:15.607000+00:00,,11331967,...,,1145388.0,,217696.0,10042786,2,9,,,
22,,,<p>LinkedIn is also caching previews. If OpenG...,LinkedIn is also caching previews. If OpenGra...,[<code>https://your-website.com/?1</code>],1,,2018-04-20 10:35:07.057000+00:00,,49939696,...,,,,1373324.0,10042786,2,4,,,
23,,,<p>I was having the same issue last night. Sp...,I was having the same issue last night. Spen...,[],0,,2018-08-11 13:22:53.443000+00:00,,51800092,...,,,,8773858.0,10042786,2,5,,,
24,,,"<p>If @Kym's answer works for you, and you don...","If @Kym's answer works for you, and you don't...",[],0,,2018-01-27 15:31:20.270000+00:00,,48477331,...,,,,8126852.0,10042786,2,1,,,
25,,,<p>For me solution was to put all the <code>&l...,For me solution was to put all the tags (with...,"[<code>&lt;meta&gt;</code>, <code>prefix</code...",0,,2018-11-14 12:25:43.090000+00:00,,53300213,...,,,,2884309.0,10042786,2,0,,,
26,,,<p>In my case I did exactly this and it worked...,In my case I did exactly this and it worked f...,[<code>&lt;title&gt; aanalytics &lt;/title&gt;...,0,,2019-02-23 19:18:01.307000+00:00,,54845243,...,,9061422.0,,9061422.0,10042786,2,0,,,
27,,,"<p>I ran into this recently, spent a huge amou...","I ran into this recently, spent a huge amount...",[],1,,2019-03-11 17:32:54.687000+00:00,,55107387,...,,,,2989397.0,10042786,2,1,,,
28,,,<p>It seems that the arguments <code>color</co...,It seems that the arguments and need to be pa...,"[<code>color</code>, <code>alpha</code>, <code...",0,,2017-06-20 08:14:17.367000+00:00,,44647485,...,,2987273.0,,4366229.0,32895876,2,0,,,
29,,,"<p>In your case, you do not need to put a <cod...","In your case, you do not need to put a condit...","[<code>where</code>, <code>time</code>, <code>...",1,,2015-10-02 06:15:43.853000+00:00,,32901506,...,,3482528.0,,3482528.0,32895876,2,0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263424,,,<p>SPSS has an AUTORECODE command which will d...,SPSS has an AUTORECODE command which will do ...,[<code>AUTORECODE vr1 to vr100 /into Kvr1 to K...,1,,2016-08-16 04:33:44,,13440,...,,18022,,18022,13436,2,0,,,
263425,,,<p>In R you turn your categorical value into a...,In R you turn your categorical value into a f...,[<code>dfr$id = as.numeric(factor(dfr$mycolumn...,0,,2016-08-16 07:39:14,,13443,...,,,,14588,13436,2,1,,,
263426,,,<p>Say your data is in a DataFrame <code>df</c...,"Say your data is in a DataFrame , and the col...","[<code>df</code>, <code>column</code>, <code>t...",2,,2016-08-17 18:49:28,,13503,...,,23495,,23495,13409,2,0,,,
263427,,,<p>Using the notation you gave (i.e. <code>dat...,Using the notation you gave (i.e. is the data...,"[<code>data</code>, <code>data.class</code>, <...",1,,2016-08-18 15:09:27,,13527,...,,,,23283,13409,2,0,,,
263428,,,<p>If you goal is simply to halve the size of ...,If you goal is simply to halve the size of yo...,"[<code>pad</code>, <code>mode</code>, <code>fr...",1,,2018-06-28 11:23:39,,33760,...,,45264,,45264,33725,2,2,,,
263429,,,<p>NumPy performs operations in a vectorised m...,NumPy performs operations in a vectorised man...,[<code>np.argwhere( (test == 1) &amp; np.roll(...,2,,2018-06-28 14:24:34,,33771,...,,,,32320,33766,2,1,,,
263430,,,<p>Lat long coordinates have a problem that th...,Lat long coordinates have a problem that they...,[<code>x = cos(lat) * cos(lon)\r\ny = cos(lat)...,3,,2016-08-20 14:09:22,,13575,...,,29238,,14904,13567,2,23,,,
263431,,,<p><code>train_test_split</code> is just a uti...,"is just a utility function around , which on ...","[<code>train_test_split</code>, <code>ShuffleS...",0,,2016-08-20 20:56:40,,13582,...,,,,13714,13580,2,1,,,
263432,,,"<p>To debug this case, I suggest you try the f...","To debug this case, I suggest you try the fol...",[],0,,2016-08-24 09:15:29,,13635,...,,,,18540,13633,2,1,,,
263433,,,"<p>So, I figured it out. The problem was the l...","So, I figured it out. The problem was the los...",[<code>mean_squared</code>],0,,2018-07-01 15:48:43,,33852,...,,,,54401,33836,2,1,,,
263434,,,<p>This is a classic case of recommendation pr...,This is a classic case of recommendation prob...,[],1,,2018-07-02 09:08:31,,33867,...,,,,53582,33863,2,1,,,
263435,,,<p>There is a method that can handle multiple ...,There is a method that can handle multiple ty...,[],0,,2018-07-02 09:47:04,,33870,...,,,,45064,33868,2,0,,,
263436,,,"<p>It is sorting, but it doesn't know that it ...","It is sorting, but it doesn't know that it is...","[<code>datetime</code>, <code>January</code>, ...",1,,2018-07-02 11:11:35,,33882,...,,,,54246,33879,2,4,,,
263437,,,<pre><code># make a month column to preserve t...,,[<code># make a month column to preserve the o...,0,,2018-07-02 13:51:47,,33886,...,,,,31571,33879,2,6,,,
263438,,,<p>What you want to do to boost the performanc...,What you want to do to boost the performance ...,[<code>from sklearn.utils.class_weight import ...,1,,2019-06-21 12:41:55,,54219,...,,,,34269,54210,2,0,,,
263439,,,<p>You are supposed to pass <code>numpy</code>...,You are supposed to pass arrays and not lists...,"[<code>numpy</code>, <code>DecisionTree</code>...",1,,2018-07-03 10:21:39,,33925,...,,29575,,54246,33910,2,6,,,
263440,,,<p><code>ValueError: Error when checking input...,it clearly says that while preprocessing that...,[<code>ValueError: Error when checking input: ...,2,,2018-07-03 11:16:21,,33929,...,,,,54246,33928,2,3,,,
263441,,,<p>I found an answer that actually ended up he...,I found an answer that actually ended up help...,[<code>import importlib\r\npackage='spacy'\r\n...,0,,2018-07-04 02:10:39,,33963,...,,29575,,50899,33958,2,0,,,
263442,,,"<p>Since you are using Spark 1.6, I'd rather d...","Since you are using Spark 1.6, I'd rather do ...",[<code>import sqlContext.implicits._ // not ne...,0,,2016-08-31 10:01:00,,13777,...,,,,5177,13749,2,0,,,
263443,,,<p>It is unclear if you are requesting AUC of ...,It is unclear if you are requesting AUC of RO...,"[<code>auc</code>, <code>precision_recall_curv...",0,,2016-09-06 05:39:23,,13869,...,,24000,,24000,13868,2,3,,,
263444,,,<p>I solved this issue. There is a parameter f...,I solved this issue. There is a parameter for...,[],0,,2016-09-09 12:32:37,,13916,...,,,,13518,13907,2,1,,,
263445,,,<p>You should broadcast your variable.</p>\r\n...,You should broadcast your variable.,[<code>import org.apache.spark.SparkContext\r\...,1,,2016-09-14 13:27:32,,13994,...,,,,24320,13992,2,0,,,
263446,,,"<p>Looking at <a href=""https://stackoverflow.c...",Looking at another question on Stack Overflow...,[<code>SparkContext</code>],0,,2016-09-14 18:47:28,,14000,...,,-1,,23581,13992,2,3,,,
263447,,,<p>I changed my code to this:</p>\r\n\r\n<pre>...,I changed my code to this: Now when it will g...,[<code>import org.apache.spark.SparkContext\r\...,0,,2016-09-15 07:00:20,,14008,...,,,,24157,13992,2,2,,,
263448,,,<p>This wouldn't be possible in seaborn withou...,This wouldn't be possible in seaborn without ...,"[<code>if kind == ""scatter"":\r\n plot_kws.s...",0,,2016-09-14 20:40:29,,14003,...,,,,19161,13909,2,0,,,
263449,,,"<p>For small data, I think <a href=""http://pan...","For small data, I think pandas.read_csv is th...",[],2,,2016-09-15 17:16:02,,14022,...,,381,,381,14021,2,13,,,
263450,,,<p>Use pandas library: </p>\r\n\r\n<pre><code>...,Use pandas library: Pandas identify the heade...,[<code>import pandas as pd \r\npd.read_csv('fo...,0,,2016-09-15 17:16:11,,14023,...,,24225,,24225,14021,2,4,,,
263451,,,"<p>You can also SFrame. First <a href=""https:/...",You can also SFrame. First install graph lab ...,[<code>import graphlab as gl\r\ndata = gl.SFra...,2,,2016-09-15 21:11:00,,14024,...,,,,8517,14021,2,0,,,
263452,,,<p>Use this syntax:</p>\r\n\r\n<pre><code>val ...,Use this syntax:,[<code>val joinedDF = students_positive_grande...,0,,2016-09-19 07:04:48,,14080,...,,,,18540,14072,2,1,,,
263453,,,"<p>Yes, most software implementations of trees...","Yes, most software implementations of trees w...",[],0,,2016-09-23 17:27:01,,14176,...,,,,12515,14165,2,1,,,

In [41]:
np.shape(dfPostAnswersFiltered)

(261045, 24)

In [42]:
np.shape(dfDSAns)

(2409, 24)

In [43]:
np.shape(dfCombinedAns)

(263454, 24)

In [44]:
dfPostQuestionsFiltered.columns

Index(['id', 'title', 'body', 'accepted_answer_id', 'answer_count',
       'comment_count', 'community_owned_date', 'creation_date',
       'favorite_count', 'last_activity_date', 'last_edit_date',
       'last_editor_display_name', 'last_editor_user_id', 'owner_display_name',
       'owner_user_id', 'parent_id', 'post_type_id', 'score', 'tags',
       'view_count', 'new_tags', 'cleaned_question_body'],
      dtype='object')

In [45]:
dfDSQues.columns

Index(['Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId', 'CreationDate',
       'DeletionDate', 'Score', 'ViewCount', 'Body', 'OwnerUserId',
       'OwnerDisplayName', 'LastEditorUserId', 'LastEditorDisplayName',
       'LastEditDate', 'LastActivityDate', 'Title', 'Tags', 'AnswerCount',
       'CommentCount', 'FavoriteCount', 'ClosedDate', 'CommunityOwnedDate',
       'new_tags', 'cleaned_question_body'],
      dtype='object')

In [46]:
# drop the columns in the data science answers that are not also in the Stack Overflow answers before merging both
del dfDSQues['DeletionDate']
del dfDSQues['ClosedDate']

In [48]:
# change the column names in data science answers dataset to match those in the Stack Overflow answers dataset
dfDSQues.columns = ['id', 'post_type_id', 'accepted_answer_id', 'parent_id', 'creation_date', 'score', 
                   'view_count', 'body', 'owner_user_id', 'owner_display_name', 'last_editor_user_id', 
                   'last_editor_display_name', 'last_edit_date', 'last_activity_date', 'title', 'tags',
                   'answer_count', 'comment_count', 'favorite_count', 'community_owned_date', 
                   'new_tags', 'cleaned_question_body']

In [49]:
dfCombinedQues=dfPostQuestionsFiltered.append(dfDSQues,ignore_index=True)

C:\Users\jeffb\Anaconda3\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

In [50]:
dfCombinedQues

,accepted_answer_id,answer_count,body,cleaned_question_body,comment_count,community_owned_date,creation_date,favorite_count,id,last_activity_date,...,last_editor_user_id,new_tags,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,title,view_count
0,56196332.0,1,<p>I have configured and set up a fully functi...,I have configured and set up a fully function...,0,,2019-05-18 04:35:44.290000+00:00,,56195999,2019-05-18 05:45:46.330000+00:00,...,7916354.0,graph,,7916354.0,,1,2,reactjserror-handlinggraphqlapollographql-js,Apollo client doesn't display an error message,256
1,56212940.0,1,<p>I want to use a mutation in an event handle...,I want to use a mutation in an event handler....,0,,2019-05-19 22:47:04.330000+00:00,,56212612,2019-05-19 23:57:38.440000+00:00,...,,graph,,10688712.0,,1,0,reactjsgraphqlreact-hooksmutation,Calling a hook (useMutation) inside an event h...,261
2,56206915.0,2,<p>I have useQuery and useMutation from react-...,I have useQuery and useMutation from react-ap...,0,,2019-05-19 04:52:19.730000+00:00,,56204854,2019-07-15 12:45:21.457000+00:00,...,,graph,,10116367.0,,1,0,javascriptreactjsgraphqlreact-apolloreact-hooks,How do I chain useQuery and useMutation in Gra...,262
3,56197449.0,1,<p>I'm coding in R and I have the following da...,I'm coding in R and I have the following data...,0,,2019-05-17 15:01:14.930000+00:00,,56189061,2019-05-18 08:58:44.763000+00:00,...,,plot plotly,,9537627.0,,1,0,rplotly,Customize lines based on specific criteria wit...,11
4,56203343.0,1,<p>I am graphing the internet connection in my...,I am graphing the internet connection in my a...,0,,2019-05-18 22:17:19.290000+00:00,,56203260,2019-05-18 22:32:10.980000+00:00,...,,python graph,,8598201.0,,1,0,pythonlistgraphsumiteration,How do I sum a list with its previous entries ...,11
5,56220931.0,1,<p>I have the following script</p>\r\r\n\r\r\n...,I have the following script Expected Behavior...,0,,2019-05-20 09:43:44.660000+00:00,,56218250,2019-05-20 12:22:29.497000+00:00,...,,matplotlib plot,,2749397.0,,1,0,matplotlib,Modify y data in a line,11
6,56275655.0,1,"<p>I'm using Google's <a href=""https://develop...",I'm using Google's geochart . I'm using the n...,0,,2019-05-23 12:33:33.063000+00:00,,56275333,2019-05-23 12:51:20.197000+00:00,...,,chart visualization,,930151.0,,1,0,chartsgoogle-visualizationgeo,Display Google Geochart in log scale,11
7,55973074.0,1,<p>I am trying to create create a calculator(f...,I am trying to create create a calculator(for...,0,,2019-05-03 15:22:50.823000+00:00,,55972829,2019-05-03 15:36:57.783000+00:00,...,,plot plotly,,10067658.0,,1,0,javascriptplotly.js,Data displayed upon submission of a form is vi...,12
8,56095454.0,1,<p>I am trying to draw a line from google char...,I am trying to draw a line from google chart ...,0,,2019-05-12 01:01:47.690000+00:00,,56095434,2019-05-12 01:16:52.103000+00:00,...,,visualization,,11375519.0,,1,0,phpmysqlgoogle-visualization,Every row given must be either null or an arra...,12
9,56260575.0,1,"<p>For a bar or column chart in Highcharts, is...","For a bar or column chart in Highcharts, is t...",0,,2019-05-22 15:33:03.250000+00:00,,56260378,2019-05-22 15:44:21.623000+00:00,...,,chart highcharts,,614263.0,,1,0,chartshighchartsstatistics,Make Highcharts pick a smart y-axis min,13
10,56191181.0,2,<p>I would like to make a column chart which t...,I would like to make a column chart which tak...,0,,2019-05-17 17:30:36.020000+00:00,,56191057,2019-05-17 17:40:26.183000+00:00,...,,ggplot2 plot chart bar-chart,,9393218.0,,1,0,rggplot2bar-chart,I would like to create a column chart where ea...,14
11,56271481.0,1,<p>I create a bar plot with python : </p>\r\r\...,I create a bar plot with python : My question...,0,,2019-05-23 08:48:25.737000+00:00,,56271400,2019-05-23 08:54:18.917000+00:00,...,,python chart bar-chart,,11482231.0,,1,0,python-3.xbar-chart,Change the width of the plot,14
12,56291205.0,1,<p>I have a line chart with <code>xAxis</code>...,I have a line chart with values as timestamps...,0,,2019-05-24 10:37:47.387000+00:00,,56290967,2019-05-24 10:53:10.670000+00:00,...,,chart highcharts,,1722794.0,,1,0,highcharts,Highcharts custom attribute with datetime line...,14
13,56298852.0,1,<p>I'm running two .py files. One creates one ...,I'm running two .py files. One creates one ra...,0,,2019-05-24 19:51:08.473000+00:00,,56298788,2019-05-24 19:57:40.767000+00:00,...,,python matplotlib plot,,9948523.0,,1,0,python-3.xmatplotlibdynamicwritefile,How to write and save each line separately on ...,14
14,56027042.0,1,<p>I can't get to display a google gauge chart...,"I can't get to display a google gauge chart, ...",0,,2019-05-07 16:20:26.053000+00:00,,56026765,2019-05-07 16:40:15.513000+00:00,...,5090771.0,chart visualization,,1967683.0,,1,1,jquerychartsgoogle-visualization,Can't display gauge chart inside a jquery get,15
15,56183832.0,1,<p>I can't get the theme or slice colors to ch...,I can't get the theme or slice colors to chan...,0,,2019-05-16 15:30:37.923000+00:00,,56172013,2019-05-17 09:47:34.307000+00:00,...,,graph,,2630240.0,,1,0,phpjpgraph,How to Change Theme On 3D Pie for JpChart,15
16,56245660.0,1,<p>I want to reference a specific part of a sh...,I want to reference a specific part of a shap...,0,,2019-05-21 15:04:03.047000+00:00,,56241219,2019-05-21 20:07:11.600000+00:00,...,,graph graphviz,,4864040.0,,1,0,graphvizdot,How to reference/name specific part of a shape?,15
17,56074853.0,1,<p>I am trying to display the charts using Ang...,I am trying to display the charts using Angul...,0,,2019-05-10 08:01:42.817000+00:00,,56073199,2019-05-10 09:40:21.497000+00:00,...,,chart,,11253744.0,,1,0,angularjszingchart,How to get animated charts in a fluid like man...,16
18,56133438.0,1,<p>I would like to select multiple series in t...,I would like to select multiple series in the...,0,,2019-05-13 13:44:16.190000+00:00,,56113691,2019-05-14 15:00:56.090000+00:00,...,,chart,,11458934.0,,1,0,javascriptrshinydashboardr-highcharter,How to select multiple series in the legend - ...,16
19,56172534.0,1,<p>I am plotting maps of interactions between ...,I am plotting maps of interactions between re...,0,,2019-05-16 12:51:12.077000+00:00,,56169033,2019-05-16 16:02:10.797000+00:00,...,787480.0,plot,,11509868.0,,1,1,gnuplot,How to be sure that my scale axis does not var...,16
20,56176120.0,1,<p>I want to make a plot that would show distr...,I want to make a plot that would show distrib...,0,,2019-05-16 20:13:55.440000+00:00,,56175964,2019-05-17 04:25:31.907000+00:00,...,8449629.0,ggplot2 plot,,11396571.0,,1,0,rggplot2geom-bar,Geom bar - dodging a population consisting of ...,16
21,56241940.0,1,<p>I have added image as marker in highchart a...,I have added image as marker in highchart and...,0,,2019-05-21 15:29:26.273000+00:00,,56241666,2019-05-21 15:45:32.557000+00:00,...,,chart highcharts,,3970774.0,,1,0,javascripthighcharts,Highchart Marker image hides if large dataset ...,16
22,56265233.0,1,<p>I would like to bold some of the values in ...,I would like to bold some of the values in my...,0,,2019-05-22 19:57:14.390000+00:00,,56264098,2019-05-22 22:11:20.800000+00:00,...,,chart bar-chart,,4495722.0,,1,0,textlabelbar-chartbokehaxis,Can I bold invididual elements in y_range of a...,16
23,55972739.0,1,"<p>I currently new to this chart, I just wante...","I currently new to this chart, I just wanted ...",0,,2019-05-03 15:00:49.223000+00:00,,55972445,2019-05-03 15:17:18.907000+00:00,...,,chart highcharts,,6314424.0,,1,0,jsonajaxhighcharts,How can i set the json encode result to the hi...,17
24,56085359.0,1,<p>I'm creating a figure in matplotlib with tw...,I'm creating a figure in matplotlib with two ...,0,,2019-05-10 17:25:36.090000+00:00,,56082261,2019-05-10 22:04:50.067000+00:00,...,,python matplotlib plot,,11395993.0,,1,0,pythonimagematplotlibscaleaxis,Changing extent of image and matching plot wit...,17
25,56084939.0,1,<p>I would like to retain the relative size di...,I would like to retain the relative size diff...,0,,2019-05-10 20:12:05.173000+00:00,,56084249,2019-05-11 04:00:05.593000+00:00,...,8449629.0,ggplot2 plot,,10719713.0,,1,0,rggplot2scatter-plot,How to change the range of point sizes when po...,17
26,56210341.0,1,<p>I am having troubles annotating my line cha...,I am having troubles annotating my line chart...,0,,2019-05-19 16:06:54.143000+00:00,,56209617,2019-05-19 17:29:46.737000+00:00,...,,python matplotlib plot,,7158458.0,,1,0,pythonmatplotlib,Annotating line chart,17
27,56258707.0,1,"<p>I am using Xcode 10, Swift 5 and I am tryin...","I am using Xcode 10, Swift 5 and I am trying ...",0,,2019-05-22 13:48:57.233000+00:00,,56258396,2019-05-22 15:19:33.493000+00:00,...,,graph,,8540450.0,,1,1,swiftfacebook-graph-api,How to set user name to UITextField from FBSDK...,17
28,56279039.0,1,<p>I have the a function to create stacked bar...,I have the a function to create stacked bar p...,0,,2019-05-23 15:48:43.310000+00:00,,56278880,2019-05-23 19:00:22.390000+00:00,...,4932316.0,python matplotlib plot chart bar-chart,,8839068.0,,1,0,pythonmatplotlibbar-chart,set plot background colour when `axes` is not ...,17
29,55986667.0,1,<p>I know if I want to make 2 index inequal in...,I know if I want to make 2 index inequal in a...,0,,2019-05-04 16:58:58.763000+00:00,,55984838,2019-05-04 20:46:36.003000+00:00,...,,r,,9272398.0,,1,0,linear-programmingamplglpk,how I can make two index inequal in ampl?,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175251,33771.0,1,<h2>Question:</h2>\r\n\r\n<p>I want to compare...,Question: I want to compare every item in a 3...,4,,2018-06-28 12:52:40,,33766,2018-06-29 12:15:16,...,53928,python r,,53928,,1,0,<python><bigdata><numpy>,How to compare fast the value with the ones of...,479
175252,33783.0,3,<p>I have my dataset that has multiple feature...,I have my dataset that has multiple features ...,4,,2018-06-28 19:19:33,,33780,2018-12-17 16:04:09,...,,python matplotlib plot,,50896,,1,0,<python><pandas><plotting><numpy><matplotlib>,Scatter plot for binary class dataset with two...,14351
175253,13551.0,2,<p>I am learning python and trying myself out ...,I am learning python and trying myself out at...,0,,2016-08-19 12:16:40,,13550,2018-08-30 15:26:17,...,,python,,23452,,1,2,<python><scikit-learn><error-handling>,Problems with accuracy.score sklearn,13593
175254,13575.0,1,<p>I am working on a fictional dataset with 25...,I am working on a fictional dataset with 25 f...,7,,2016-08-20 06:51:26,12,13567,2017-03-02 19:08:25,...,23600,python,,23600,,1,18,<machine-learning><python><feature-engineering...,Ways to deal with longitude/latitude feature,12318
175255,13582.0,1,<p>I know how to split the dataset into train ...,I know how to split the dataset into train an...,2,,2016-08-20 19:19:05,,13580,2016-08-20 20:56:40,...,,python,,15412,,1,-1,<machine-learning><python><dataset><scikit-learn>,Splitting Data in scikit-learn,235
175256,13635.0,1,<p>I used the Neural Network Toolbox in matlab...,I used the Neural Network Toolbox in matlab t...,8,,2016-08-24 07:41:53,,13633,2016-08-24 09:19:38,...,8013,matlab,,8013,,1,1,<neural-network><supervised-learning><matlab><...,Query regarding neural network model,47
175257,54219.0,1,"<p>First, thank you.</p>\r\n\r\n<p>I'm using T...","First, thank you. I'm using Tensorflow 1.13 w...",0,,2019-06-21 10:15:52,,54210,2019-06-21 12:41:55,...,,python,,76413,,1,1,<python><tensorflow>,is there a way to customize my loss function t...,138
175258,33852.0,1,<p>I wanted to build a DQN. So I followed this...,I wanted to build a DQN. So I followed this c...,0,,2018-06-30 17:12:09,,33836,2018-07-01 15:48:43,...,,python,Flajt,54401,,1,1,<reinforcement-learning><python><q-learning>,"Tflearn ""nan"" weight matrices",71
175259,33867.0,1,<p>I have the following dataset where each row...,I have the following dataset where each row r...,0,,2018-07-02 05:08:58,,33863,2018-07-02 09:08:31,...,,python,,35386,,1,1,<machine-learning><python><scikit-learn><keras...,Recommending products to buy,52
175260,33870.0,1,<p>I want to implement PCA on a dataset(retail...,I want to implement PCA on a dataset(retail) ...,0,,2018-07-02 09:29:37,,33868,2018-07-02 10:05:55,...,54450,python,,54450,,1,0,<python><pca><encoding>,How to use multiple encoders(one-hot and numer...,343
175261,33886.0,2,"<p>Based on the following dataframe, I am tryi...","Based on the following dataframe, I am trying...",0,,2018-07-02 10:47:51,,33879,2018-07-02 20:08:53,...,26019,python,,54442,,1,3,<python><pandas>,panda grouping by month with transpose,8597
175262,33925.0,1,<p>I am new to data science and trying get som...,I am new to data science and trying get some ...,1,,2018-07-02 21:51:21,,33910,2019-01-25 16:20:04,...,,python,,49884,,1,4,<python><scikit-learn><feature-selection><trai...,Number of features of the model must match the...,12612
175263,14426.0,1,<p>I'm trying to do a algorithm in Spark Mllib...,I'm trying to do a algorithm in Spark Mllib. ...,0,,2016-08-26 18:03:38,,13701,2016-10-09 08:49:45,...,,scala,,23811,,1,0,<apache-spark><scala><market-basket-analysis>,Items in a transaction must be unique but got ...,1088
175264,13733.0,2,<p>Imagine that I've the following dataset:</p...,Imagine that I've the following dataset: I ne...,0,,2016-08-29 12:49:26,1,13730,2017-12-21 15:20:53,...,471,scala,,23811,,1,1,<apache-spark><scala><market-basket-analysis>,Market Basket Analysis - Data Modelling,1207
175265,13777.0,1,<p>I've a data set with this fields:</p>\r\n\r...,I've a data set with this fields: And I'm try...,4,,2016-08-30 10:43:32,,13749,2016-08-31 10:01:00,...,5177,scala,,23811,,1,0,<apache-spark><scala><association-rules>,Apply GroupByKey to identify the Frequently Pr...,2254
175266,54276.0,3,<p>I am working on classification of time seri...,I am working on classification of time series...,0,,2019-06-22 07:49:47,1,54273,2019-06-24 04:39:23,...,29169,python,,74166,,1,5,<python><keras><convnet>,How can I know if my conv1D model is overfitte...,90
175267,33929.0,1,<p>I am trying to fit this model in keras but ...,I am trying to fit this model in keras but ge...,2,,2018-07-03 11:08:49,,33928,2018-07-03 11:16:21,...,,python,,44680,,1,0,<python><deep-learning><keras><tensorflow>,Same input size but cannot fit the model in keras,166
175268,33963.0,1,<p>I'm trying to do some intent extraction/rec...,I'm trying to do some intent extraction/recog...,1,,2018-07-04 00:03:57,,33958,2019-06-12 03:17:20,...,29169,python,,50899,,1,-2,<python><nlp>,Rasa_Nlu SpaCy installing dependencies,440
175269,13819.0,3,<p>How Can I save a DataFrame as a CSV in HDFS...,How Can I save a DataFrame as a CSV in HDFS? ...,0,,2016-09-02 11:05:02,1,13818,2018-09-12 15:22:02,...,8432,scala,,23714,,1,2,<apache-spark><scala>,value saveAsTextFile is not a member of org.ap...,7560
175270,13869.0,1,<p>The code below measures precision and recal...,The code below measures precision and recall ...,2,,2016-09-05 22:26:27,,13868,2016-09-06 10:03:41,...,24000,python,,24095,,1,-2,<python><scikit-learn><nltk>,I need to measure Performance : AUC for this c...,877
175271,22559.0,3,"<p>In the <a href=""https://blog.keras.io/build...",In the Keras blog on training convnets from s...,6,,2016-09-07 15:14:56,3,13894,2019-07-01 14:05:17,...,20372,python,,14360,,1,16,<machine-learning><python><deep-learning><kera...,How to get predictions with predict_generator ...,40680
175272,13916.0,1,<p>I am trying to learn topics distribution fo...,I am trying to learn topics distribution for ...,0,,2016-09-08 08:51:08,,13907,2016-09-09 12:32:37,...,,python,,13518,,1,1,<python><text-mining><lda><gensim>,Getting uniform distribution over topics from ...,638
175273,14003.0,1,"<p>I tried using kind=""box"" but am not sure if...","I tried using kind=""box"" but am not sure if t...",0,,2016-09-08 20:29:31,0,13909,2016-09-14 20:40:29,...,24114,python visualization,,24114,,1,1,<python><visualization>,Python Seaborn: How can one obtain a box plot ...,955
175274,14008.0,3,<pre><code>import org.apache.spark.SparkContex...,This is the code that I have written in Spark...,1,,2016-09-14 12:56:58,1,13992,2016-09-15 07:00:20,...,11097,scala,,24157,,1,2,<bigdata><apache-spark><scala>,Task not serializable Error,1439
175275,14023.0,3,<p>I have a csv file with around 130 columns a...,I have a csv file with around 130 columns and...,2,,2016-09-15 17:08:55,1,14021,2017-07-16 06:44:57,...,,python,,24355,,1,1,<machine-learning><python><dataset><csv>,importing csv data in python,6097
175276,14047.0,2,<p>I was working through a tutorial on the tit...,I was working through a tutorial on the titan...,0,,2016-09-16 23:17:05,,14046,2019-11-01 14:53:31,...,29169,python,,24411,,1,1,<python><scikit-learn><cross-validation>,"sklearn.cross_validation.cross_val_score ""cv"" ...",3983
175277,14080.0,1,<p>I've two dataframes. The first have the som...,I've two dataframes. The first have the some ...,0,,2016-09-18 21:20:50,,14072,2016-09-19 07:04:48,...,,scala,,23811,,1,0,<apache-spark><scala>,Join two dataframes - Spark Mllib,6034
175278,14123.0,2,<p>OK this is my first time in ML and for star...,OK this is my first time in ML and for starte...,2,,2016-09-20 05:40:10,3,14102,2018-01-30 21:27:37,...,10879,python,,10879,,1,5,<python><scikit-learn><naive-bayes-classifier>,Naive Bayes: Divide by Zero error,3214
175279,14176.0,1,<p>Is there a way to take a set of data that c...,Is there a way to take a set of data that con...,0,,2016-09-22 21:52:17,1,14165,2016-09-23 17:27:01,...,,python,,13165,,1,0,<machine-learning><python><regression><decisio...,Can I use categorical data and Decision Trees ...,858
175280,14182.0,2,<p>I have reduced the data set to only the col...,I have reduced the data set to only the colum...,0,,2016-09-23 22:48:05,,14179,2017-03-31 08:32:25,...,23800,python,,23800,,1,0,<python><pandas>,Pivot DataFrame while calculating new values,494

In [51]:
np.shape(dfPostQuestionsFiltered)

(173697, 22)

In [52]:
np.shape(dfDSQues)

(1584, 22)

In [53]:
np.shape(dfCombinedQues)

(175281, 22)

In [54]:
# write the combined questions dataframe to a tsv
dfCombinedQues.to_csv("data/stackoverflow/SODSQues_parsed.tsv", sep='\t', index=False)

In [55]:
# write the combined questions dataframe to a csv
dfCombinedQues.to_csv("data/stackoverflow/SODSQues_parsed.csv", index=False)

In [22]:
# USE THIS CODE TO LOAD THE SO + DATA SCIENCE QUESTIONS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfCombinedQues = pd.read_csv("data/stackoverflow/SODSQues_parsed.tsv", sep='\t', keep_default_na=False)

In [56]:
# write the combined answers dataframe to a tsv
dfCombinedAns.to_csv("data/stackoverflow/SODSAns_parsed.tsv", sep='\t', index=False)

In [22]:
# USE THIS CODE TO LOAD THE SO + DATA SCIENCE ANSWERS TO A PANDAS DATAFRAME -- Note that you may have to change the path to the .tsv 
# file in the statement below depending on the location you downladed the .tsv to
dfCombinedAns = pd.read_csv("data/stackoverflow/SODSAns_parsed.tsv", sep='\t', keep_default_na=False)